### ISSUE TITLE
VKD3D Not working in latest Proton Experimental and 6.3-3

### ISSUE THREAD

**Issue by kodatarule** [ValveSoftware/Proton#4807] opened 2021-05-04 17:46 UTC
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: RTX 3070
- Driver/LLVM version: 465.27
- Kernel version: 5.11.16-149-tkg-upds
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/kodatarule/5e8fb29872fbf79e9da0791612e9d84f
- Proton version:Proton Experimental (and Proton 6.3-3 also is affected)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
It says that there is no d3d12 device and even if a game is able to launch it launches it with d3d11.

## Reproduction

Try to run any d3d12 application.
![Screenshot_20210504_203802](https://user-images.githubusercontent.com/65848953/117046673-a3deb000-ad19-11eb-8762-91945c385579.png)
![Screenshot_20210504_203939](https://user-images.githubusercontent.com/65848953/117046682-a50fdd00-ad19-11eb-81f3-9539208c5935.png)
[steam-564310.log](https://github.com/ValveSoftware/Proton/files/6423001/steam-564310.log)
[steam-673130.log](https://github.com/ValveSoftware/Proton/files/6423006/steam-673130.log)

**Comment by misyltoad** [comment] 2021-05-04 18:13
~~I actually have this same issue. I've worked around it by enabling DXVK_LOG_LEVEL=info or disabling fsync and using esync (server sync doesn't work either)~~

~~Caused by the vulkan luid commit for xwayland. Seems like there's some race going on.~~

**Comment by misyltoad** [comment] 2021-05-04 18:18
Scratch this, my issue is unrelated to this, I did not read the issue in it's entirety.

**Comment by kodatarule** [comment] 2021-05-05 06:24
UPDATE: It appears that something might've broke vkd3d for specific games, because I was able to launch gears 5 and get to the usual xbox game studio and mangohud confirmed I'm using vkd3d 2.3.1 
Interesting find by user ZereoX while trying F1 2020, he states that the game shows that the windows version doesn't support D3D12 and linked me to this specific change: https://github.com/ValveSoftware/wine/commit/a2adb204b2c2e8a2a54ed7c8cd20075c6822f722

**Comment by DomiStyle** [comment] 2021-05-05 08:05
Ghostrunner is broken too when starting in DirectX 12 mode.

**Comment by alasky17** [comment] 2021-05-05 17:06
@kodatarule It looks like this was a wine regression: https://bugs.winehq.org/show_bug.cgi?id=51080
Fix commit will be in the next Proton release :)

**Comment by aeikum** [comment] 2021-05-07 20:52
This should be resolved in today's Proton Experimental release. We'll move the fix over to 6.3 soon.

**Comment by aeikum** [comment] 2021-05-13 15:52
This issue is hopefully fixed in the Proton 6.3-4 RC candidate, see #4821.

**Comment by kodatarule** [comment] 2021-05-13 17:53
Yep seems resolved with Proton 6.3-4 RC!

**Comment by aeikum** [comment] 2021-05-14 16:52
Thanks everyone for reporting and testing. 6.3-4 is released now, so I'll close this issue.

**Closed as completed by aeikum** 2021-05-14 16:52 UTC
