### ISSUE TITLE
Games not working if installed on different NTFS HDD

### ISSUE THREAD

**Issue by Hekel1989** [ValveSoftware/Proton#104] opened 2018-08-22 14:24 UTC
Hi Team,
I've just tested Steam Play on my machine, and steam play crashes as soon you click on "Play" if my games are installed on a NTFS hard disk.

I've tried with Eternal and Dark Souls 3 and they crashed instantly.

I've then re downloaded them to the default steam location (which is on my OS's HDD, ext4), and they both work perfectly.

I'm unsure whether it's because of the non default location of the game or NTFS, but I'd be inclined to think NTFS is not the culprit here, as all my other games launched with Lutris+wine+DXVK from that NTFS hard disk all work fine.

PC:

Ubuntu 18.04.01
GTX 1080 with latest nvidia drivers (396.XX)
i5 3750k, 16gb DDR3 RAM

Any idea what it might be?

**Comment by jarrard** [comment] 2018-08-22 14:26
Think you will need to produce some error logs.

**Comment by Hekel1989** [comment] 2018-08-22 14:41
@jarrard could you please assist? what log would they need and how would you produce them? thanks :)

**Comment by aeikum** [comment] 2018-08-22 14:44
NTFS is known to have issues on Linux, this isn't really a supported configuration. You might find some help at #35 and #11.

**Comment by salty-horse** [comment] 2018-08-22 17:52
Even if it's not a supported configuration, can there be a FAQ entry about it?

At the very least, proton's (and/or Steam's) error message can be more helpful by detecting the issue and providing some guidelines.

**Comment by mirh** [comment] 2018-08-22 22:02
https://github.com/ValveSoftware/Proton/issues/82#issuecomment-415162671

**Comment by regataos** [comment] 2018-08-22 22:10
Do you have the "fuseiso" package installed on your Ubuntu?

**Comment by linkjay** [comment] 2018-08-22 23:07
Please check out #35 , specifically my first part where I mention ntfs-3g. Read on further in the issue for help if more file permission errors occur. 

https://github.com/ValveSoftware/Proton/issues/35#issuecomment-414935724

Thanks for sharing my fix, aeikum!

**Comment by jpalaciosdev** [comment] 2018-08-23 08:53
It's a problem with proton and the names of some directories contained in the wineprefix created for each game when both resides in a NTFS formated partition.

I commented it in https://github.com/ValveSoftware/Proton/issues/82#issuecomment-415099440

**Comment by jarrard** [comment] 2018-08-24 03:15
Those who change permissions to the drives might get a popup on launch to enter password for mounting your internal drives. A solution for me with KDE5/Arch setup is below.

**First** be sure your part of group storage with: useradd -G storage _USERNAME_

**Second** make a file in **/etc/polkit-1/rules.d/** called _10-mount-system.rules_:
ie. _sudo gedit /etc/polkit-1/rules.d/10-mount-system.rules_    
(I use gedit because.. but nano or anything will do fine)

Put the below text in the file and save+reboot, it should no longer ask for password to mount drives on desktop launch.
```
polkit.addRule(function(action, subject) {
     if (action.id == "org.freedesktop.udisks2.filesystem-mount-system" &&
          subject.active &&
          subject.isInGroup("storage")) {
          return polkit.Result.YES;
     }
});
```

**Comment by cprn** [comment] 2019-06-27 21:42
Are you sure this is an NTFS issue? I just installed a game, let the Proton prefix creation and dependency installation script complete, confirmed it works. I then moved it to a different library within the same filesystem (ext4) and the game stopped working complaining about missing drives. Then I forced a different Proton version (which created a new prefix) and it was working again (from new location).

I might be entirely wrong but I think some paths in the prefix aren't changed when the game is moved between libraries.

**Comment by mirh** [comment] 2019-06-27 21:53
NTFS handling has been greatly reworked from last year till this April. 
Whatever this bug was, my 2c would be it's fixed now.

**Comment by edoantonioco** [comment] 2019-11-07 23:33
I can reproduce this bug in manjaro. I installed mirrors edge in a ntfs partition, didnt worked in proton (it worked in wine but thats not relevant). So I moved it to an ext4 partition and now it works

**Comment by jarrard** [comment] 2019-11-07 23:58
1) NTFS requires certain configuration adjustments in the mount options which are covered in the proton wiki (read it!)
2) Proton does not execute well off ntfs drives, that is the proton base install, be sure it's in your .steam folder steamapps on the linux main drive and not installed on any NTFS or external drives (it auto installs to my ntfs if I install proton after adding the ntfs drives).

**Closed as completed** 2020-04-09 14:20 UTC

**Comment by edoantonioco** [comment] 2020-04-09 14:39
I fixed this bug, time ago, I would hope this get fixed in steam so it will work properly by default

**Comment by kiobu** [comment] 2020-04-12 00:33
So theoretically a game installed on an NTFS drive _should_ work with Proton now?

**Comment by mirh** [comment] 2020-04-12 10:29
As long as it's mounted with the [right options](https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows) prolly?
