### ISSUE TITLE
Mirror's edge: cursor does not show up in steam overlay

### ISSUE THREAD

**Issue by TomJansen** [ValveSoftware/Proton#678] opened 2018-08-26 14:54 UTC
#### Your system information

* Steam client version (build number or date): Aug 23 2018 at 19:47:27
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Running and playing Mirror's Edge with Proton works fine. However, when you enable the Steam Overlay, the cursor does not show up. You can click stuff but it is just that the cursor icon is gone. The in-game cursor works fine however.

#### Steps for reproducing this issue:

1. Run Mirror's Edge with Proton
2. Access the Steam Overlay

**Comment by pprotonrep** [comment] 2018-08-26 15:24
See https://github.com/ValveSoftware/Proton/issues/168 for an issue related to the overlay and missing mouse cursor

**Comment by kisak-valve** [comment] 2018-08-26 19:06
Closing as a duplicate of #168.

**Closed as completed by kisak-valve** 2018-08-26 19:06 UTC
