### ISSUE TITLE
No Mouse cursor in Steam Overlay in Proton / Windows Games

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#435] opened 2018-08-24 19:57 UTC
I tried 5 games and when I press Shift+Tab, the Ingame Overlay pops up but there is no mouse cursor (or it seems to be invisible)

Works in native Linux games.

My Setup:
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD FX(tm)-8350 Eight-Core Processor           
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux Mint 19 Tara (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-33-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Mutter (Muffin)
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1c82
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.08" x 11.42" (23.07" diag)
                                            51.0cm x 29.0cm (58.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 4096 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7994 Mb

Miscellaneous:
    UI Language:  English
    LANG:  sk_SK.UTF-8
    Total Hard Disk Space Available:  505611 Mb
    Largest Free Hard Disk Block:  191015 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by d10sfan** [comment] 2018-08-24 20:02
Seeing this on alot of games as well. Some games work, only if you're on a menu so their's already a mouse cursor.

**Comment by ArekPiekarz** [comment] 2018-08-24 20:06
Can you list the games you tested? Otherwise it may be hard to reproduce the issue.

**Comment by tfaller** [comment] 2018-08-24 20:10
There is already an open issue for this problem.
Please take a look at #168

**Comment by Zero86Sk** [comment] 2018-08-24 20:15
I tested in no particular order:
Sonic Adventure DX
Sonic All-Stars Racing Transformed
Worms Ultimate Mayhem

I noticed that these games hide the system mouse cursor

In games like Pac-Man Championship Edition DX+ and 2 where the game has the system mouse cursor it works fine.

Will continue to test it with more games

**Comment by kisak-valve** [comment] 2018-08-24 20:26
Closing as a duplicate of #168.

**Closed as completed by kisak-valve** 2018-08-24 20:26 UTC
