### ISSUE TITLE
Games never starting

### ISSUE THREAD

**Issue by Minecraftveteran3** [ValveSoftware/Proton#5368] opened 2021-12-01 14:41 UTC
Proton version: any from Experimental to 5.0-10
Games tested: Rocket League and Bloons TD6
GPU: Rx 570 (The issue already existed on my old NVIDIA card)
GPU Driver: amdgpu
Linux kernel: 5.15.5-arch1-1 on ArchLinux

Here is what happens: When clicking play the game shows as "Running" for 2-4 seconds and then shows as being closed again. A window never opens (using i3wm)

The following is the Terminal output of running `steam` shortly before and after launching Rocket League:

```Opted-in Controller Mask for AppId 252950: 0
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
Proton: Upgrading prefix from 5.0-1 to 6.3-3 (/home/mcvet/.local/share/Steam/steamapps/compatdata/252950/)
Proton: Removing ShellExecute DDE registry entries.
Proton: Removing stale builtin /home/mcvet/.local/share/Steam/steamapps/compatdata/252950/pfx//drive_c/windows/system32/amd_ags_x64.dll
Proton: Removing stale builtin /home/mcvet/.local/share/Steam/steamapps/compatdata/252950/pfx//drive_c/windows/syswow64/amd_ags_x64.dll
*** stack smashing detected ***: terminated
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
Set Account Config Sets 0 0 0
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
Fossilize INFO: Setting autogroup scheduling.
Fossilize INFO: Setting autogroup scheduling.
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 252950, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 252950, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/mcvet/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=252950 -- '/home/mcvet/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/mcvet/.local/share/Steam/steamapps/common/rocketleague/Binaries/Win64/RocketLeague.exe'\0
Game process added : AppID 252950 "/home/mcvet/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=252950 -- '/home/mcvet/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/mcvet/.local/share/Steam/steamapps/common/rocketleague/Binaries/Win64/RocketLeague.exe'", ProcID 218294, IP 0.0.0.0:0
chdir /home/mcvet/.local/share/Steam/steamapps/common/rocketleague/Binaries/Win64
ERROR: ld.so: object '/home/mcvet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mcvet/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/mcvet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mcvet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mcvet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 218298 != 218295, skipping destruction (fork without exec?)
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 252950, ActionID 1] : LaunchApp changed task to Completed with ""
Installing breakpad exception handler for appid(steam)/version(1637624439)
*** stack smashing detected ***: terminated
Game process removed: AppID 252950 "/home/mcvet/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=252950 -- '/home/mcvet/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/mcvet/.local/share/Steam/steamapps/common/rocketleague/Binaries/Win64/RocketLeague.exe'", ProcID 218294
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1637624439)
Installing breakpad exception handler for appid(steam)/version(1637624439)
```

In the middle of the ouput above there is a /bin/sh command listed, I tried running this and fixing missing env variables but it also returned without any error after showing the "preparing to start Rocket League" Steam window (bash is the shell if this is relevant):
```
[mcvet@arch ubuntu12_32]$ STEAM_COMPAT_CLIENT_INSTALL_PATH=~/.local/share/Steam STEAM_COMPAT_DATA_PATH=~/.local/share/Steam/steamapps/compatdata/252950 ./reaper SteamLaunch AppId=252950 -- '/home/mcvet/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3'/proton waitforexitandrun  '/home/mcvet/.local/share/Steam/steamapps/common/rocketleague/Binaries/Win64/RocketLeague.exe'
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Xlib:  extension "NV-GLX" missing on display ":99.0".

(wine:283524): GStreamer-WARNING **: 15:35:52.790: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstogg.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstogg.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstpbtypes.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstpbtypes.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstapp.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstapp.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libprotonmediaconverter.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libprotonmediaconverter.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgsttypefindfunctions.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgsttypefindfunctions.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstcoreelements.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstcoreelements.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstcoretracers.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstcoretracers.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgsttheora.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgsttheora.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstid3demux.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstid3demux.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstspeex.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstspeex.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstnavigationtest.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstnavigationtest.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstaudioresample.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstaudioresample.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstavi.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstavi.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstplayback.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstplayback.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstflac.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstflac.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstaudioparsers.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstaudioparsers.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstopus.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstopus.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstdebug.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstdebug.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvorbis.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvorbis.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstwavparse.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstwavparse.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideofilter.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideofilter.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstaudioconvert.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstaudioconvert.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstjpeg.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstjpeg.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstflxdec.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstflxdec.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstflv.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstflv.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstadder.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstadder.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstdeinterlace.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstdeinterlace.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideoconvert.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideoconvert.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideobox.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideobox.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstmpg123.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstmpg123.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideoscale.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstvideoscale.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstmatroska.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstmatroska.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstisomp4.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstisomp4.so: wrong ELF class: ELFCLASS64

(wine:283524): GStreamer-WARNING **: 15:35:52.791: Failed to load plugin '/home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstautodetect.so': /home/mcvet/.local/share/Steam/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0/libgstautodetect.so: wrong ELF class: ELFCLASS64
wine: configuration in L"/home/mcvet/.local/share/Steam/steamapps/compatdata/252950/pfx" has been updated.
[mcvet@arch ubuntu12_32]$ pwd
/home/mcvet/.local/share/Steam/ubuntu12_32
[mcvet@arch ubuntu12_32]$
```

Here is what I already tried:
- Checking for dependencies I don't have: https://wiki.archlinux.org/title/Steam/Troubleshooting#Debugging_shared_libraries
- Running the game with `PROTON_LOG=1 %command%`: The created file contains nothing but the usual headers
- Deleting `~/.steam` and  `~/.local/share/Steam`
- A bunch of other Launch options/ additional dependencies I found while searching for a solution, none of them made any difference

A bit more to note:
- My games are on an ext4 filesystem (same as the root one)
- I have all the dependencies listed here: https://github.com/lutris/docs/blob/master/WineDependencies.md#archantergosmanjaroother-arch-derivatives (I know this is for lutris but I didn't see any other dependencies listed by Valve)
- The game(s) worked previously on this installation but that was a few months ago, there have been a lot of changes to my system since then.
- I have python(3/2), default "python" is Python 3
- The ingame overlay is disabled (But from what I have read the Errors relating to it are just a red hearing)

This isn't a major issue for me since I dualboot with Windows 10 but it would still be nice to find a Solution.

**Comment by kisak-valve** [comment] 2021-12-01 15:03
Hello @Minecraftveteran3, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

`*** stack smashing detected ***: terminated` in your terminal spew looks similar to https://github.com/ValveSoftware/steam-runtime/issues/420.

**Comment by Minecraftveteran3** [comment] 2021-12-01 15:24
Hey, thanks for pointing me to that issue, I didn't find it before. 
Removing the files mentioned there and some nvidia packages I wasn't using anymore fixed it for me. Im guessing the System info isn't needed in that case.
Thank you very much!

**Comment by kisak-valve** [comment] 2021-12-01 15:26
Closing as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/420.

**Closed as completed by kisak-valve** 2021-12-01 15:26 UTC
