### ISSUE TITLE
DOOM (2016) hangs on a DOOM Console window (379720)

### ISSUE THREAD

**Issue by btegs** [ValveSoftware/Proton#77] opened 2018-08-22 11:30 UTC
After the game [gave me issues](https://github.com/ValveSoftware/Proton/issues/69) using the standard default options, I saw a thread [here](https://www.reddit.com/r/wine_gaming/comments/96d0bs/) where adding **+r_renderAPI 1** to the Steam launch options would force the game to run in Vulkan instead of OpenGL.

When doing this, it would launch the game without the wglCreateContextAttribsARB issue but then be stuck on a black screen with a DOOM Console window open and nothing there. Then there would be a spinning icon that spins continuously. I have waited over 5 minutes for it to launch and nothing.

Running Solus with the latest updates and running on an AMD RX 580.

**Comment by voidplayer** [comment] 2018-08-22 11:43
I tried your +r_renderAPI 1 too

Same problem

**Comment by SpookySkeletons** [comment] 2018-08-22 11:43
Same issue here.
Arch linux 4.18
Tried swapping the compat prefix out for my own fully functional DOOM prefix with no luck, same issue.

**Comment by btegs** [comment] 2018-08-22 12:00
Here's my report too that I submitted via the [Vulkan Caps Viewer](https://vulkan.gpuinfo.org/download.php):

https://vulkan.gpuinfo.org/displayreport.php?id=3875

**Comment by gnusuari0** [comment] 2018-08-22 18:43
Edit: I got the game to work. Writing "+r_renderAPI 1" in the Steam launch options did the trick. OpenGL is non-functional even with the latest Mesa from Git. With Vulkan the game runs perfectly. No graphics corruption. No black screens. So... on Ubuntu 18.04 install Padoka PPA and use "+r_renderAPI 1" launch option.

If you read Proton prerrequisites here: https://github.com/ValveSoftware/Proton/blob/proton_3.7/PREREQS.md it says you need Mesa 18.2.0. Ubuntu 18.04 comes with Mesa 18.1 and Linux 4.15.
After adding the Padoka PPA and installing an updated mesa, DOOM starts. But screen shows graphics corruption all over the place, random pixels. ALT+F4 needed to exit the game (or open the task manager or a terminal and kill "DOOMx64.exe" process).

**Comment by voidplayer** [comment] 2018-08-22 20:27
Okay, i got it working too. Using vulkan ("+r_renderAPI 1") and the driver from the nvidia site "NVIDIA-Linux-x86_64-396.54.run"

Version from debian experimental is 396.51. Its not enough it seems

**Comment by parkerlreed** [comment] 2018-08-22 20:57
If you have the black screen with Vulkan including the blank console window, use Steam runtime instead of Steam native libraries

https://github.com/ValveSoftware/Proton/issues/16

**Comment by btegs** [comment] 2018-08-23 02:04
@parkerlreed - Thanks for the tip! I disabled the native libs in LSI and DOOM started no problem and ran wonderfully.

**Comment by aeikum** [comment] 2018-08-24 19:47
Dupe of #16.

**Closed as completed by aeikum** 2018-08-24 19:47 UTC
Labels: Game compatibility
