### ISSUE TITLE
**THIS IS AN IMPORTANT REPORT. THIS BUG MAKES UE5 GAMES UNPLAYABLE ON SOME DEVICES**

### ISSUE THREAD

**Issue by BinaryHarbinger** [ValveSoftware/Proton#8042] opened 2024-09-01 16:08 UTC
### **THIS IS AN IMPORTANT REPORT. THIS BUG MAKES UE5 GAMES UNPLAYABLE ON SOME DEVICES**

Installing _vulkan-intel_ drivers on devices who has Mobile GPU's makes UE5 games work on CPU which makes game run in worse FPS's

Feral Gamemode, prime-run commands and installing bbswitch then changing power mode or current GPU are not effecting this problem

### TESTED GAMES:

_+The Finals_

_+Palworld_

**Comment by kisak-valve** [comment] 2024-09-01 16:13
Hello @BinaryHarbinger, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #7892.

**Closed as not planned by kisak-valve** 2024-09-01 16:13 UTC

**Comment by BinaryHarbinger** [comment] 2024-09-01 16:16
> Hello @BinaryHarbinger, please do not intentionally open duplicate issue reports.
> 
> Closing as a duplicate of #7892.

BRO STOP SPAMMING ME I'M WDY BY NOT PLANNED THIS IS AN IMPORTANT THING FOR LOT OF PEOPLE YOU ALSO CLOSED MY OTHER ISSUES WHAT IS YOUR PROBLEM.
