### ISSUE TITLE
Quake Live online gameplay not working

### ISSUE THREAD

**Issue by kasymovga** [ValveSoftware/Proton#113] opened 2018-08-22 14:55 UTC
Local playing with bots work fine. But game crashing after click on server in server list.

**Comment by sigzegv** [comment] 2018-08-22 15:05
I have the exact same issue with Witch It, the starts correctly, and when going multiplayer it just crash.

**Comment by dawid2193487** [comment] 2018-08-22 15:05
Duplicate of #112

**Closed as completed** 2018-08-22 15:19 UTC
