### ISSUE TITLE
Grand Theft Auto V 

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1117] opened 2018-09-01 09:15 UTC
Game cannot be played since the first social club screen that must be filled is corrupt.

**Comment by vanyasem** [comment] 2018-09-01 09:37
Duplicate of #37

**Comment by kisak-valve** [comment] 2018-09-01 15:28
Hello @infosisio, feel free to add your experience to #37. Closing as a duplicate.

**Closed as completed by kisak-valve** 2018-09-01 15:28 UTC
