### ISSUE TITLE
Mac OS version using moltenVK. 

### ISSUE THREAD

**Issue by ebellumat** [ValveSoftware/Proton#4921] opened 2021-06-25 19:01 UTC
# Feature Request
Mac OS version of proton using moltenVK to create a Vulkan compatibility layer. 

## I confirm:
- [ X] that I haven't found another request for this feature.
- [ X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Mac OS support. 
## Justification [optional] 
Add Metal support can be hard. MoltenVK can be a shortcut to achieve MacOS version. 

## Risks [optional]
Maybe we have to add support for LLVM build instead GCC. 

## References [optional] 
[MoltenVK project](https://github.com/KhronosGroup/MoltenVK)

**Comment by kisak-valve** [comment] 2021-06-25 19:04
Hello @ebellumat, this is functionally a duplicate of #1344. Closing in favor of the older issue report.

**Closed as completed by kisak-valve** 2021-06-25 19:04 UTC
