### ISSUE TITLE
Proton 6.3-5 RC testing

### ISSUE THREAD

**Issue by aeikum** [ValveSoftware/Proton#4906] opened 2021-06-18 16:43 UTC
Hello. We've put together a new 6.3 build for you to test.

In the Steam client, the Proton 6.3 app should have a "next" beta branch which you can choose to start testing the 6.3-5 Release Candidates (**note that the name of the build in the Steam Settings dialog will not be updated**). I will post changes here when we push new builds. The source for the latest RC build is available on the proton_6.3-next branch in these repositories. This branch may receive forced updates.

In this issue, we are interested only in problems that are new to the 6.3-5 RC builds. If you find new problems in the "next" branch, please confirm that the problem does not occur in on the "default" branch before reporting it here.

Here is the tentative changelog. As always, this changelog has not yet been verified by our QA staff, and can change before the final release as we add or remove features during RC testing.

- Many improvements to video rendering. Games known to be improved include:
  - Bloodstained
  - Deep Rock Galactic
  - The Medium
  - Metal Gear Solid V: The Phantom Pain
  - Resident Evil 2 (2019)
  - Resident Evil 3 (2020)
  - Team Sonic Racing

- Update DXVK to [v1.9](https://github.com/doitsujin/dxvk/releases/tag/v1.9).

- Improve GPU device selection (now using DXVK's DXGI by default).

- Update vkd3d-proton to include the latest development work.

- The following games are now playable:
  - Sid Meier's Civilization VI
  - Crypt Stalker
  - Dark Devotion
  - Dorfromantic
  - Far Cry
  - Hard Reset
  - Hogs of War
  - Might & Magic: Clash of Heroes
  - Pro Cycling Manager 2020
  - Sang Froid - Tales of Werewolves
  - Secret of Mana
  - Trainz Railroad Simulator 2019
  - World of Final Fantasy

- Improve controller support in Hades and many Unity titles.

- Fix CyberPunk 2077, Darksburg, and other launchers hanging when external links are clicked.

- Fix Conan Exiles and other Funcom launchers crashing.

- Fix missing audio in Project Cars 3.

- Better support for container-based builds outside of the build VM.

**Comment by iWeaker** [comment] 2021-06-18 21:12
World of Final Fantasy (Except NVIDIA) * 
![66259046-ed1cf580-e7ac-11e9-86ed-935a77708aba](https://user-images.githubusercontent.com/49424816/122616391-2360de00-d03f-11eb-8327-76ec2a1e7add.jpg)

**Comment by blastermaster77** [comment] 2021-06-18 22:10
"Many improvements to video rendering. Games known to be improved include:

    Bloodstained
    Deep Rock Galactic
    The Medium
    Metal Gear Solid V: The Phantom Pain
    Resident Evil 2 (2019)
    Resident Evil 3 (2020)
    Team Sonic Racing"
I tried Bloodstained and i just see color bars on video. with this rc.

**Comment by kisak-valve** [comment] 2021-06-18 22:15
Hello @blastermaster77, can you check if shader pre-caching is enabled in Steam's settings?

**Comment by blastermaster77** [comment] 2021-06-18 22:19
Yes it is enabled 

![Screenshot from 2021-06-18 18-17-51](https://user-images.githubusercontent.com/9307070/122620691-9a0ed300-d061-11eb-8a65-070a46c802b4.png)
![Screenshot from 2021-06-18 18-19-31-1](https://user-images.githubusercontent.com/9307070/122620762-c591bd80-d061-11eb-8318-27109735dc93.png)

**Comment by blastermaster77** [comment] 2021-06-18 22:20
its Bloodstained ritual of the night right?

**Comment by luisalvarado** [comment] 2021-06-18 22:57
> Replying to https://github.com/ValveSoftware/Proton/issues/4906#issuecomment-864300371

Are you able to clear the cache and test again?

**Comment by blastermaster77** [comment] 2021-06-19 01:58
I will got home now.

**Comment by blastermaster77** [comment] 2021-06-19 02:08
> > Replying to [#4906 (comment)](https://github.com/ValveSoftware/Proton/issues/4906#issuecomment-864300371)
> 
> Are you able to clear the cache and test again?

I did clear it and it still the same, just to be sure, by cleaning the cache you mean the shader cache right?

**Comment by luisalvarado** [comment] 2021-06-19 02:44
> > > Replying to [#4906 (comment)](https://github.com/ValveSoftware/Proton/issues/4906#issuecomment-864300371)
> > 
> > 
> > Are you able to clear the cache and test again?
> 
> I did clear it and it still the same, just to be sure, by cleaning the cache you mean the shader cache right?

Yes correct. Well then it is still in RC. Hopefully for the final version it should be fixed.

**Comment by notpentadactyl** [comment] 2021-06-19 10:04
I tried `Guilty Gear -Strive-` (not on the list, but the changes seem to target media foundation).

Some move list videos did work: https://streamable.com/4yfise

Then I removed the shader cache and now no videos work at all.

Assuming this is the correct way to use `Proton 6.3-5 RC`:

![ggst1](https://user-images.githubusercontent.com/21175961/122638731-1ce16d80-d0f6-11eb-9faa-efa1ebe626e8.png)

**Comment by ghost** [comment] 2021-06-19 14:43
Fuser was not working, however with this update the game seems to work fine. The only problem is when pulling the disc that is hooked. I think it would be possible to test this game and add this update.

![Fuser teste](https://user-images.githubusercontent.com/52839852/122645993-8744de80-d0f3-11eb-9822-c689642951a9.png)
![Fuser teste (2)](https://user-images.githubusercontent.com/52839852/122645996-89a73880-d0f3-11eb-8827-cf7005b0d192.png)

**Comment by annulen** [comment] 2021-06-19 19:42
> I tried Bloodstained and i just see color bars on video. with this rc.

Hi @blastermaster77, does "color bars" issue reproduce with current Proton 6.3-4? Because I'm seeing very similar thing in two other games (Battletoads ~~and Aim Lab~~, to be specific) with Proton 6.3-4.

cc @kisak-valve

Update: videos in Aim Lab seems to work fine with current 6.3-4 actually, however I'm pretty sure it wasn't working a couple of months ago, however fix might be caused by changes in Aim Lab itself. Battletoads are still affected: video cutscenes look like picture shown in https://github.com/ValveSoftware/Proton/issues/4906#issuecomment-864300371 while audio playback seemingly works (but cutscene finishes in very beginning, not nearly reaching audio track end). `WINEDLLOVERRIDES="mfplay=d" %command%` doesn't change anything.

**Comment by ghost** [comment] 2021-06-20 09:33
I can confirm that RESIDENT EVIL 2 (2019) have working MFPlat videos.

**Comment by Quentin-ctrL** [comment] 2021-06-20 22:12
I confirm Might & Magic: Clash of Heroes starts now.
Excellent job ;)

**Comment by jp-bennett** [comment] 2021-06-21 01:43
Obduction is one of the games that really needs this, and we're still getting color bars for videos. The in-game videos have a couple seconds of correct sound, before dying.

**Comment by alexzk1** [comment] 2021-06-22 10:40
Elite Dangerous Odessey, FPS is close to doubled ( a bit less then 2x) on stations on foot running around. Just by switching to this proton's version, no other changes in game settings.

**Comment by aeikum** [comment] 2021-06-24 13:46
Hello. We pushed an update to the 'next' branch this morning which fixes running some games with PROTON_USE_WINED3D.

**Comment by blastermaster77** [comment] 2021-06-24 14:47
Bloodstained ritual of the night videos work now! Good job!  with the new RC!

https://user-images.githubusercontent.com/9307070/123283629-93f17a00-d4d9-11eb-9b7b-d7c6cac6bf08.mov

**Comment by aeikum** [comment] 2021-06-24 17:46
We've pushed a new build live which fixed some issues with older games running in non-native resolutions.

**Comment by ghost** [comment] 2021-06-24 18:56
@aeikum Even not mentioned the game in the list after this update the game is now extremely playable. Before, you couldn't pull the disc and the game wouldn't start. Now the game starts normally without any problem and you can pull the disc. The only problem is only on video that getting color bars for videos.

**New update**
![Fuser](https://user-images.githubusercontent.com/52839852/123317580-8ef5f000-d504-11eb-9bf5-cc72a7d8ab79.png)

Old update
![Fuser teste](https://user-images.githubusercontent.com/52839852/123317705-b0ef7280-d504-11eb-89a5-50e49b37a302.png)

**Closed as completed** 2021-07-09 14:51 UTC
