### ISSUE TITLE
Several games freeze in fullscreen mode with Proton 8.0-4

### ISSUE THREAD

**Issue by flytrapdev** [ValveSoftware/Proton#7206] opened 2023-10-27 17:35 UTC
# Compatibility Report
- Name of the game with compatibility issues: Pizza Tower, Resident Evil. Possibly other games.
- Steam AppID of the game: Pizza Tower: 2231450, Resident Evil: 304240

## System Information
- GPU: Nvidia GeForce GTX 1070Ti 
- Video driver version: Proprietary Nvidia driver 525.125.06
- Kernel version: 6.2.0-35-generic
- Link to full system information report as [Gist](https://gist.github.com/): [https://gist.github.com/flytrapdev/9aa839a5e84b3e24f52d2e54f9e7dbb3](https://gist.github.com/flytrapdev/9aa839a5e84b3e24f52d2e54f9e7dbb3)
- Proton version: Proton 8.0-4

Some extra information which could be useful:
- OS: Kubuntu 22.04
- Desktop Environment: KDE Plasma 5.24.7
- Windowing system: X11

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

NOTE : There is an open issue for Resident Evil 1 Remastered, but it seems to be an unrelated problem. The game runs fine in windowed mode, or in fullscreen with Proton 7. 

## Steam log file
[steam-2231450.log](https://github.com/ValveSoftware/Proton/files/13191581/steam-2231450.log)

## Symptoms 
Several games freeze when in fullscreen mode.
So far I've noticed this with Resident Evil 1 Remastered and Pizza Tower.
Both games work in windowed mode, but freeze in fullscreen.

As soon as the game enters fullscreen mode, the first frame remains (frozen) on the screen.
I have to alt-tab out of the game and quit it to try again.

Downgrading to Proton 7.0-6 fixes the issue.

Not every game is affected: Quake Remastered for instance runs fine in fullscreen mode.

## Reproduction
1. In the steam compatibility settings, choose Proton 8.0-4
2. Start the game
3. The game enters fullscreen mode
4. The first frame remains on-screen, the game freezes and becomes unresponsive.

**Comment by maharmstone** [comment] 2023-11-03 05:57
Disabling "Force Composition Pipeline" in nvidia-settings fixed this for me.

**Comment by flytrapdev** [comment] 2023-11-04 14:05
> Disabling "Force Composition Pipeline" in nvidia-settings fixed this for me.

That seems to have fixed it, thank you !

On the other hand, disabling the composition pipeline causes tearing when moving windows around.
It would be great if Proton 8 could work with the pipeline enabled.

Is this something that could be fixed in Proton ?

If not, I'll close this issue, since disabling the pipeline is a good enough workaround.

**Comment by maharmstone** [comment] 2023-11-04 14:08
I'd say keep it open, it's clearly a regression between Proton 7 and 8.

The same issue (presumably) causes Portal with RTX to crash outright.

**Comment by kisak-valve** [comment] 2023-11-04 14:09
Hello @flytrapdev, that makes this issue a duplicate of #6869. Feel free to add your experience to the older issue report.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2023-11-04 14:09 UTC

**Comment by darkranger-red** [comment] 2023-12-29 13:08
I just realized there is something odd between fullscreen and windowed mode. Switched to the latter is actually playable on Proton 8 and Experimental. So I found #7206 and disabled "Force Composition Pipeline" in nvidia-settings. Now the game is fully playable and does not need to fall back to Proton 7. It seems to be the duplicate bug of that issue.
