### ISSUE TITLE
Elden Ring [1245620]

### ISSUE THREAD

**Issue by olav-valle** [ValveSoftware/Proton#5615] opened 2022-02-24 23:52 UTC
# Compatibility Report
- Name of the game with compatibility issues: Elden Ring
- Steam AppID of the game: 1245620

## System Information
- GPU: Nvidia Geforce RTX 3080
- Driver/LLVM version: Nvidia 470.86.0 
- Kernel version: Linux 5.15.23-76051523-generic
- Link to full system information report as [Gist](https://gist.github.com/olav-valle/3fcc30a1f94dfa758d49a4a67181b721):
- Proton version: 1645736267 experimental-bleeding-edge-7.0-10273-20220224-pdf2505-wb25665-db42c07-vc29d00

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[steam-1245620.log](https://github.com/ValveSoftware/Proton/files/8137319/steam-1245620.log)

## Symptoms 
Game launcher loads, then displays error message: "Failed to load the anti-cheat module."

## Reproduction
Click play, wait for launcher/splash screen.

**Comment by netthier** [comment] 2022-02-24 23:53
Duplicate of https://github.com/ValveSoftware/Proton/issues/5613

**Comment by kisak-valve** [comment] 2022-02-25 00:20
Hello @olav-valle, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5613#issuecomment-1050389426.

**Closed as completed by kisak-valve** 2022-02-25 00:20 UTC
