### ISSUE TITLE
Integrate with GameMode?

### ISSUE THREAD

**Issue by MavropaliasG** [ValveSoftware/Proton#4639] opened 2021-02-20 03:23 UTC
Hi, would it make sense to integrate [GameMode](https://github.com/FeralInteractive/gamemode) in Proton for performance optimization?

**Comment by jqadev** [comment] 2021-02-20 12:25
Great idea, but for some reason after 2,5 year of Proton existence it is still not integrated.
There is already the similar issue https://github.com/ValveSoftware/Proton/issues/622 but unfortunately @kisak-valve didn't respond there.
@kakra who is the author of this issue prepared the big PR related to Steam https://github.com/FeralInteractive/gamemode/pull/76 but it hasn't been merged yet and seems dead.

@kisak-valve maybe you know the reason of not yet integrated GameMode despite the fact that **Valve** sponsors/sponsored @mdiluz work on this project.

**Comment by kakra** [comment] 2021-02-20 12:35
Not exactly dead, I'm rebasing it from time to time when the patch no longer applies to upstream. But work on it is currently in some sort of sleep mode due to multiple personal issues and focussing on some other performance improvements first. I've seen lately that Proton integrated support for doing dbus calls to daemons outside of wine (rtkit integration, experimental branch), so there's an opportunity to get back to it soonish. The current approach still misses a proper whitelisting feature.

Without the patch, all wine processes of Proton will be changed by gamemode which may be undesirable. It may create issues especially with the thread priorities patches that went into Proton Experimental. With the patch, we may still override what Proton with the thread prio patches thinks is best.

OTOH, the whole renice and prio thing is quite futile with a kernel that uses auto-group scheduling since Proton is running games inside a container. We'd need to detect that and adjust the autogroup priority of the process group leader instead. This needs some more investigation. I've suggested something similar for Proton's fossilize which has been upstreamed meanwhile.

**Comment by kisak-valve** [comment] 2021-02-20 13:17
Closing as a duplicate of #622.

@jqadev, friendly reminder that I'm a moderator for Valve's issue trackers on Github and not a Valve dev myself. Whether I make a comment on an issue report or not means nothing.

**Closed as completed by kisak-valve** 2021-02-20 13:17 UTC
