### ISSUE TITLE
DOOM 2016: Mouse lags or hangs making it hard to aim with 1000Hz mice (379720)

### ISSUE THREAD

**Issue by OlliC** [ValveSoftware/Proton#147] opened 2018-08-22 19:45 UTC
Hi, 

i installed DOOM 2016 again after having it played with wine before (via Lutris) and i still runs very good with 80-100 FPS on High Settings with Vulkan. 

The only small problem i have with it is mouse input. When moving the mouse around, it hangs at certain points like you hit an invisible wall. Then when moving the mouse further it eventually catches on. Feels really weird and a little bit hard to explain. Its also noticable in the main menu when moving the cursor around. 

My mouse is a Zowie FK1 on 1600 DPI with 1000Hz polling rate. Ingame sensitivity set to 2. 

Can someone confirm this mouse behaviour?

**Comment by libcg** [comment] 2018-08-22 20:17
I hit the same issue with wine-staging 3.13.1. It's a long standing wine bug.

**Comment by elovin** [comment] 2018-08-22 20:37
I had the same problem when I was playing DOOM through wine, in my case this was connected to the wayland session. 

Does the problem still exist when using the Xorg session ? (assumeing you are running a recent version of gnome3 or plasma 5 wayland session)

**Comment by libcg** [comment] 2018-08-22 21:08
@elovin yes it's present on Xorg as well.

**Comment by mo0nsniper** [comment] 2018-08-22 21:28
Same problem here on RedHat 7.5 playing Quake 3

**Comment by germangb** [comment] 2018-08-22 21:41
Happens to me as well on several games. Battlefront 2, Worms (DOSBox), Ultimate DOOM, Tomb Raider 1 (DOSBox) to name a few.

X11 session
Ubuntu 18.04.1 LTS
Proton 3.7 with default settings

**Comment by brantrusnak** [comment] 2018-08-23 03:03
Try turning your report/polling rate down to 125

I hit this issue in Doom as well with my g502, and when I moved the mouse slowly in one direction it felt like it "hit the edge of the screen" and stop moving completely. Swapped to a different mouse and the issue went away, figured it was my mouse settings, and dropped the report rate to 125 and that fixed the issue.

**Comment by unlimitedbacon** [comment] 2018-08-23 04:09
That makes sense. I'm having the same issue with DOOM under Proton, but I have noticed the same problem previously with other games in Wine. I first noticed the issue after I bought a new gaming mouse (Roccat Kone Aimo).

Unfortunately I am not able to change the mouse polling rate. I tried following [the instructions on the Arch Wiki](https://wiki.archlinux.org/index.php/Mouse_polling_rate) but they have no effect. It stays at 1000 hz.

**Comment by brantrusnak** [comment] 2018-08-23 05:20
@unlimitedbacon Have you tried using `roccat-tools` or `roccat-tools-kone` from the AUR? 

I had to change the settings on a Windows machine and save to the mouse on-board memory. You might be able to get away with running the roccat software in WINE or do a USB passthrough to a Windows VM?

**Comment by unlimitedbacon** [comment] 2018-08-23 06:07
Thanks, I was able to boot into Windows and use the Roccat tool to reduce the polling rate. The problem is still definitely happening, however it is reduced enough that the game is playable.

The mouse only gets stuck when you are moving it very slowly. If you are making quick precise moves it is not a problem, but if you are making subtle movements it makes it hard to aim accurately.

**Comment by mo0nsniper** [comment] 2018-08-23 07:50
I also have a mouse with 1000Hz pooling rate A4Tech X7 and I see this is also discussed here:
https://steamcommunity.com/app/221410/discussions/0/490121928343092592/

If this happends also on native game this means it's a linux bug I guess. Does anyone know if a bug report already exists for this?

**Comment by OlliC** [comment] 2018-08-23 09:46
I never noticed this on any native game, so i definitly think this is a wine bug. Also i am on Xorg with nvidia driver (GTX 1050 Ti), so no Wayland issue. 

But good to see others have the same problem. I played through the whole game once with this bug and never heard about someone with the same problem. 

I will change my mouse polling rate just to test if its better, but definitly will set it back to 1000Hz after that.

**Comment by OlliC** [comment] 2018-08-23 11:22
So i did some testing and the issue seems definitly been tied to mouse polling rate. 

At 125Hz and 500Hz there is no mouse lags of any kind for me. Neither when moving the mouse slowly nor very fast. Only at 1000Hz the issue is back. So i will just leave it at 500Hz for now.

**Comment by libcg** [comment] 2018-08-23 15:02
Can confirm it's a 1000Hz issue, I'm using a Logitech g502 as well.

**Comment by ghost** [comment] 2018-08-26 13:36
I'm experiencing the same issue on Ubuntu 18.04.1 LTS. Additionally I can't lower my mouse polling rate as described in the arch wiki: https://wiki.archlinux.org/index.php/Mouse_polling_rate#Polling_rate_not_changing

**Comment by arianvp** [comment] 2018-08-26 21:14
I can't move the mouse at all in DOOM. it's stuck in the top-left corner.  I can move around the menu's with the keyboard, but once I launch a game the keyboard doesn't work either

**Comment by CrazedProgrammer** [comment] 2018-08-27 20:29
I also cannot move the cursor in DOOM. When I launch a game the keyboard also doesn't work (I can't enter the level with [SPACE]). I have a Logitech g403 at 500Hz.

EDIT: also tried it with a 125hz mouse and removed all xorg.conf mouse config, still the same results

**Comment by OlliC** [comment] 2018-08-27 22:41
Then its probably another issue and not related to the 1000Hz problem.

**Comment by libcg** [comment] 2018-08-28 03:55
Is any of you having the mouse wall issue using gnome-shell?

**Comment by OlliC** [comment] 2018-08-28 12:17
Yes using Gnome on Arch Linux.

**Comment by ghost** [comment] 2018-08-28 16:43
Are you guys running dual or triple monitors? Because my theory is that that the invisible mouse cursor is not locked to the center of the screen while playing, and it's wandering around all screens until it hits the very edge of the left/rightmost monitor, which is when the camera movement gets stuck. Lowering the mouse report rate just makes it less frequent. Any toughts?

**Comment by unlimitedbacon** [comment] 2018-08-28 17:17
I typically run with dual monitors but I have also tested with the second monitor disabled. The problem still happens. It's definitely not hitting a screen edge since you can move the mouse faster and it will start moving again.

**Comment by brantrusnak** [comment] 2018-08-28 17:17
Also running Gnome, and no I'm running one monitor and the issue is present.

**Comment by libcg** [comment] 2018-08-28 17:29
If you switch to another virtual desktop and then back, the cursor might stay visible, and it appears that the mouse hits the wall just as the cursor hits the edge of the screen. It might be that Wine fails to lock the cursor in place, but still gets relative move events.

**Comment by steveyh25** [comment] 2018-09-02 13:35
I've seen this issue in skyrim (standard) and borderlands - it's not game specific and it looks to be a wine (and hence proton) bug. Can confirm that the mouse pointer is not being locked to the center of the screen properly - thus when you move the mouse enough in one direction to put it on the edge of the screen then what you observe is that slow mouse movements are practically ignored indefinitely if you keep moving in that direction. If you move the mouse in the opposite direction, then slow mouse movements are fine until the cursor reaches "the end" of the screen on that side - in which case you end up with the same situation as above

edit: here's the same issue mentioned on reddit (https://www.reddit.com/r/linux_gaming/comments/9893js/wine_games_not_capturing_mouse_properly/)

I've tested the 3.7.5-beta and the enabling of "Automatically capture mouse in fullscreen windows is enabled by default." does not fix the issue. The cursor is just not being reset to the center of the screen

**Comment by libcg** [comment] 2018-09-02 22:43
On GTA V, "DirectInput" and "Raw" input modes exhibit this problem, but the "Windows" method works fine.

**Comment by aufkrawall** [comment] 2018-09-03 14:55
Could you guys give wine-staging 3.15 a try? It fixed The Forest for me, seems to work now without issues with 1000Hz polling rate at the same time.

That wine-staging Winex11 fix should really get merged into Proton.

**Comment by libcg** [comment] 2018-09-03 15:47
I can confirm that the mouse works perfectly in GTA V with all input modes using wine-staging 3.15. Please merge the fix!

**Comment by Baguettedood** [comment] 2018-09-03 15:47
I have tried staging-3.15 + 1000hz mouse on games where I previously experienced the mouse issue, and it does seem to be fixed.

**Comment by aufkrawall** [comment] 2018-09-03 16:56
I tested Hitman (2016 DXVK) and Doom as well, the issue is also gone for me in these games.

**Comment by michael-n0813** [comment] 2018-09-10 04:39
Another Logitech G502 user with same issue, cursor won't move in game when slowly moving the mouse but fast rapid mouse movement works fine.

Game issue - The witness
Tested with Proton 3.7-6 Beta

Steam controller with mouse emulation works perfect and Logitech M310t works fine.

Would love to see this issue fixed!

**Comment by michaelnew** [comment] 2018-09-10 22:07
I don't think it's been posted on this issue so far, so for reference, [this](https://bugs.winehq.org/show_bug.cgi?id=42631) is the corresponding wine bug thread and [this](https://github.com/wine-staging/wine-staging/tree/master/patches/winex11-mouse-movements) is the patch that addresses the issue.

**Comment by P4NCH1** [comment] 2018-09-11 02:03
I have the same "mouse wall" or cursor lag issue with various games (GTA3 (12100), GTA-VC (12110), Q3A (2200), etc) with a Logitech M280 on SteamOS brewmaster (gnome3 desktop)

**Comment by libcg** [comment] 2018-09-23 20:21
@Plagman @aeikum any progress on this?

**Comment by aeikum** [comment] 2018-09-24 12:33
@libcg Yes, it's on our radar.

**Comment by OlliC** [comment] 2018-09-28 18:29
Can confirm its resolved for me with Proton 3.7-7 Beta. Back at 1000Hz now. Thanks!

**Comment by libcg** [comment] 2018-09-28 19:40
Issue fixed for me as well.

**Comment by aeikum** [comment] 2018-09-28 20:01
Thanks all for reporting and retesting.

**Closed as completed by aeikum** 2018-09-28 20:01 UTC
Labels: Game compatibility

**Comment by aufkrawall** [comment] 2018-09-29 20:19
Issue is not fully fixed in Proton 3.7-7 and The Forest, moving the mouse on the x axis makes it move down the y axis at the same time, or in other words: You always start looking down at the bottom when moving the mouse.

This is not the case with wine-staging 3.15, where mouse control in The Forst works perfectly fine.

**Comment by michael-n0813** [comment] 2018-09-30 04:33
This issue is fixed but in some game mouse 'drift' is still a problem. This fixed the 1000hz problem in the witness and subnautica but subnautica has mouse 'drift' to down-right of the screen when moving the mouse, clicking mouse buttons or scrolling with the mouse wheel.

Same issue with My Summer car [#880](https://github.com/ValveSoftware/Proton/issues/880)

Might wanna start another issue?

**Comment by Compizfox** [comment] 2020-07-01 09:07
Not fixed for me with the default SteamPlay Proton version (3.16-9). As soon as I move my mouse with the polling rate set to 1000 Hz, I get heavy microstuttering.

I reduced the polling rate of my mouse to 250 Hz and the issue is gone.

**Comment by ruffson** [comment] 2020-11-10 16:45
It is not fixed for me either, I tried all available proton version on steam.
For me (on a Quadro RTX 3000, i7-10875H) if I move the mouse everything gets unuseably stuttery (even in the menu). A litle while after the last mouse input I can move around with the keys and navigate the menu fine. But the mouse input is unusable, same for PS4 controller.

And since I have the `xhci-hcd` module, accoring to the [Arch wiki](https://wiki.archlinux.org/index.php/Mouse_polling_rate#Polling_rate_not_changing) I cannot even change my polling rate.

Please reopen @aeikum.

**Comment by Compizfox** [comment] 2020-11-10 16:51
> And since I have the xhci-hcd module, accoring to the Arch wiki I cannot even change my polling rate.

I had the same issue, and I managed to work around it by changing the polling rate in the mouse itself. For my mouse (Steelseries Rival 300), this tool called [rivalcfg](https://github.com/flozz/rivalcfg) could do that. You might be able to do the same thing for your mouse.

**Comment by ruffson** [comment] 2020-11-10 16:58
> > And since I have the xhci-hcd module, accoring to the Arch wiki I cannot even change my polling rate.
> 
> I had the same issue, and I managed to work around it by changing the polling rate in the mouse itself. For my mouse (Steelseries Rival 300), this tool called [rivalcfg](https://github.com/flozz/rivalcfg) could do that. You might be able to do the same thing for your mouse.

Interesting, thanks for that. I have a Logitech g302 and don't know of any software on linux for it. I tried [piper](https://github.com/libratbag/piper) but it only allows to switch between 500 and 1000Hz and doesn't work anyway :)
