### ISSUE TITLE
Easy Anti Cheat (EAC) does not work for certain games.

### ISSUE THREAD

**Issue by hlafaille** [ValveSoftware/Proton#616] opened 2018-08-26 01:46 UTC
Easy Anti Cheat returns an "unable to instantiate" error for the unofficial game Dead by Daylight, yet it works fine in Friday the 13th: The Game.

**Comment by kisak-valve** [comment] 2018-08-26 01:56
Closing as a duplicate of #519.

**Closed as completed by kisak-valve** 2018-08-26 01:56 UTC

**Comment by Rabcor** [comment] 2018-10-26 18:28
@kisak-valve it's not really a duplicate though. the title says 'certain games' it's just a poorly written OP. There are at least 5 issues which refer to EAC for different games.

**Comment by jomarocas** [comment] 2019-08-01 19:11
refer the game o games, you only refer for two games, you dont need iniziate other thread only for this, follow all thread and make a related issue
