### ISSUE TITLE
Proton seem broke, every game crash at startup failing to load graphics

### ISSUE THREAD

**Issue by SlugSleepy** [ValveSoftware/Proton#6095] opened 2022-08-15 12:23 UTC
Hello, here is my problem, all the games that should run under proton with the latest versions are non-functional, everything crashes on startup no matter what I do, proton-experimental automatically crashes all the games, the proton 7-0-3 manages to miraculously launch some games, here rain world but the graphics do not load, the screen remains in the dark, sometimes we see a small light but that's it, we can't do anything about it. I also tested the latest version of proton-ge, it does not work either.

On the other hand, your older proton in version 6 and 5 proposed by steam them works
On an alternative launcher (lutris for instance), no problem with the last wine-ge7-25

my system
i5 10400f
rx6600 8go
16gb ram
ubuntu mate 22.04.1 latest updated (COmpositor marco:picom-glx)
kernel 5.19 tkg-pds
Gist for my full spec info : https://gist.github.com/SlugSleepy/0453e441b7d8fd8f811d2fa98614ea86
Gist for terminal input : https://gist.github.com/SlugSleepy/a9402332167ca6b596938261108f2f13

Edit : i use steam on flatpak, tried on system and snap, both not working.

thank you.

**Comment by SlugSleepy** [comment] 2022-08-15 12:29
file c

**Comment by SlugSleepy** [comment] 2022-08-15 12:30
[2022-08-15_141928.zip](https://github.com/ValveSoftware/Proton/files/9337143/2022-08-15_141928.zip)
i uploded the dmp files that the game created on his own folder and sorry for closing and reopening, missclicked.

**Comment by kisak-valve** [comment] 2022-08-15 13:31
Hello @SlugSleepy, the builds of DXVK and VKD3D-Proton inside of Proton Experimental now requires mesa 22.0 or newer and the version of mesa provided inside the Flatpak environment is currently too old to be used with it. This minimum driver version requirement is not a bug.

In general, we're using one issue report per unofficially supported game title, and it might be interesting to ponder the specific issue with Rain World and Proton 7.0-3 a bit more. Feel free to add your experience with Rain World and Proton 7.0-3 to #1230 along with adding [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attaching the generated $HOME/steam-$APPID.log to that issue report as a file. (Proton logs compress well if needed.)

Closing because the primary focus of this issue report is Proton Experimental and the video drivers provided by Flatpak.

**Closed as completed by kisak-valve** 2022-08-15 13:31 UTC
