### ISSUE TITLE
Impossible to delete proton on windows due to illegal naming

### ISSUE THREAD

**Issue by Vectrobe** [ValveSoftware/Proton#2189] opened 2019-01-04 04:02 UTC
If a steam library is created on a windows disk, with proton enabled, illegal/reserved name files are created under dosdevices, of which are impossible to handle inside windows. COM files can be brute-force deleted via powershell, however disk devices cannot.

![screenshot_1](https://user-images.githubusercontent.com/3912867/50673447-e13faf80-1031-11e9-93ba-7dcc2866a87b.jpg)

**Comment by sat3ll** [comment] 2019-01-04 20:09
https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file

Not a proton bug. This is how wine represents its structure and its valid under Linux/Unix (naming conventions).

Now I am not sure but you could try using WSL (Windows Subsystem for Linux) or under a Linux VM to delete this.

**Comment by ghost** [comment] 2019-01-04 22:00
lol

**Comment by ghost** [comment] 2019-01-05 00:33
Maybe they should disallow Proton on Windows because obviously someone did it lol

**Comment by Vectrobe** [comment] 2019-01-05 00:34
Doesn't matter, it's still a fault that needs addressing. A solution would be to prevent proton being cloned to external library directories, as it currently does and where this issue primarily originates. This is not a direct fault of wine, as it doesn't expect its files to be cloned about in the first place.

**Comment by sat3ll** [comment] 2019-01-05 00:35
> Maybe they should disallow Proton on Windows because obviously someone did it lol

Could have been a dual boot situation using the same SteamLibrary.

**Comment by Vectrobe** [comment] 2019-01-05 00:36
> Could have been a dual boot situation using the same SteamLibrary.

Exactly that configuration, to shared NTFS drives.

**Comment by kisak-valve** [comment] 2019-01-05 00:37
It should be noted that sharing the same Steam library across multiple platforms has never been supported and can have undefined results.

**Comment by Vectrobe** [comment] 2019-01-05 00:40
> It should be noted that sharing the same Steam library across multiple platforms has never been supported and can have undefined results.

irrelevant, and it's windows <> windows anyway, there shouldn't be any differences unless the game was built with different win API revisions for some reason

**Comment by ArekPiekarz** [comment] 2019-01-05 01:19
What do you mean it's windows <> windows? Didn't you use Linux to install Proton on NTFS drive? You didn't provide any steps to reproduce the issue.

**Comment by ghost** [comment] 2019-01-05 02:17
> > It should be noted that sharing the same Steam library across multiple platforms has never been supported and can have undefined results.
> 
> irrelevant, and it's windows <> windows anyway, there shouldn't be any differences unless the game was built with different win API revisions for some reason

Congrats telling Valve they're are wrong lol

Blocking is right technically correct since what you did doesn't work (Proton is meant for Linux). And, sharing like Kisak says isn't supported but still I haven't seen this problem that way - it has its problems though and still shouldn't be done because all people will do is to post bugs and complain thinking it is supported.

Since they don't support it and it isn't what they created it for then it should be blocked until they decide to do something about it.

But, I'm not going to reply to any further replies about this topic. My view point is ^ right there.

**Comment by Salamek** [comment] 2019-01-05 16:34
@kisak-valve just close this stupidity + wontfix/notabug

**Closed as completed** 2019-01-05 19:20 UTC

**Comment by biji** [comment] 2023-02-12 04:18
This issue should be kept for reference

I use ntfs external disk for dual boot gaming. One time , steam download 'Proton Next' to ntfs. Everytime i boot windows, said disk need to be repaired, then I repair using windows, but windows give up with `unspecified error`. All read write operation is normal

In windows explorer, `c:` is a file with 100GB size which is impossible to delete using linux and windows . Is there any way to delete it?

**Comment by Marat-Tanalin** [comment] 2023-05-28 14:39
It would probably be useful to have a FAQ advice how to delete such files even if it’s not a bug of Proton. In my case, undeletable files were named `com1`, `com2`, etc., and occupied about 1000 bytes in total in two folders. Did not have files like `c:` as the OP described.

One of the folders was:

> steamapps/common/Proton 3.16/dist/share/default_pfx/dosdevices/

NTFS Access by nGlide author did **not** help. Was able to delete `com*` files with **Unlocker 1.9.2**.
