### ISSUE TITLE
DOOM 2016 Crash when online multiplayer match begins. (379720)

### ISSUE THREAD

**Issue by Reded100** [ValveSoftware/Proton#222] opened 2018-08-23 05:32 UTC
Every time online match begins the game crash showing a "DOOM Unhandled Exception" message.
Using Vulkan API, Linux MInt 19 64bits, kernel 4.15, driver version 396.51.

My Crash html file: https://pastebin.com/raw/bycgHM8k

Single-player Campaign works fine.

**Comment by OlliC** [comment] 2018-08-23 09:59
Multiplayer never worked for me either. Although some people at wine appdb say it works for them.

**Comment by Reded100** [comment] 2018-08-23 14:10
@OlliC Online works fine with my Lutris + Wine-Staging

**Comment by cjbr0wn** [comment] 2018-08-24 04:33
Yeah Doom MP works thru lutris but crashes when using Steam Play

**Comment by mimattr** [comment] 2018-08-24 21:30
+1 Also share the same experience as @Reded100 using **Ubuntu 16.04 LTS** (x64) and **NVIDIA 396.54** driver (_Proton 3.7.1535035861_):

[Steam System Information](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)

Online multiplayer appears to function as expected with [Wine Staging 3.14](https://github.com/wine-staging/wine-staging/tree/v3.14) and [DXVK 0.70](https://github.com/doitsujin/dxvk/tree/v0.70).

Hope that helps.

**Comment by mimattr** [comment] 2018-08-24 21:32
+1 Also share the same experience as @Reded100 using **Ubuntu 16.04 LTS** (x64) and **NVIDIA 396.54** driver (_Proton 3.7.1535035861_):

[Steam System Information](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)

Can confirm this issue appears to be resolved with [Wine Staging 3.14](https://github.com/wine-staging/wine-staging/tree/v3.14) and [DXVK 0.70](https://github.com/doitsujin/dxvk/tree/v0.70).

Hope that helps.

**Comment by mimattr** [comment] 2018-08-27 13:11
Ubuntu 16.04, NVIDIA GTX 970, Proton 3.7-4 Beta:

[Steam System Information](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)

Test | Result
-- | --
Singleplayer | Working as expected
Local Co-op | _N/A_
Online Multiplayer | Partially working^

Configuration | ...
-- | --
Input | Steam Controller
Display | 1920x1080
Fullscreen | Yes
Preset | Medium
VSync | Off
API | Vulkan^^

^ Application crash when searching for other players ([log](https://gist.github.com/mimattr/57a9246cadbb9c9e1bc2bf171ad362b6))
^^ Default graphics API is **OpenGL**

**Comment by ghost** [comment] 2018-08-30 15:18
Same issue. Arch Linux. Using amdgpu driver. Crashes as a multiplayer game is about to begin. Single Player working as expected using Vulkan API. Not posting a log since it is the same the one posted by @mimattr

**Comment by HeroCC** [comment] 2018-09-11 00:20
Same here, I saw something about Wine 2.0 having DOOM multiplayer support, but I'm not sure what proton is: https://news.softpedia.com/news/wine-staging-2-0-adds-basic-aes-gcm-support-and-fixes-doom-2016-multiplayer-mode-511363.shtml

**Comment by OliverMead** [comment] 2018-10-21 17:18
Does anyone know why it can be whitelisted when multiplayer doesn't work?

**Comment by ashkitten** [comment] 2018-10-22 00:21
has the proton 3.16 beta fixed anything with this? i couldn't get a multiplayer match to check, because apparently nobody plays lol

**Comment by Reded100** [comment] 2018-10-22 04:21
> has the proton 3.16 beta fixed anything with this? i couldn't get a multiplayer match to check, because apparently nobody plays lol

Still crash on 3.16 beta

**Comment by OliverMead** [comment] 2018-10-22 08:36
@ashkitten @reded100 3.16 beta is where I tested it, if you go to team deathmatch you should be able to find a match

**Comment by ghost** [comment] 2018-11-19 23:04
Same Problem here with 3.16

**Comment by Alexmitter** [comment] 2018-11-23 21:51
Same problem here.
Xubuntu 18.04
NVIDIA GTX 1060 @ 396.54

**Comment by ViktorWalter** [comment] 2018-12-23 13:39
And same with
Ubuntu 16.04
Quadro K5000M @ 410.73

**Comment by alasky17** [comment] 2018-12-26 15:46
@Alexander88207 @Alexmitter @ViktorWalter  What is the exact behavior you are seeing when entering a multiplayer match with 3.16-6?  There have been some changes for 3.16-6 compared to earlier versions of 3.16, so please retest.  If you are getting a failure, it would be helpful to take a +wininet,+winhttp,+winsock,+bcrypt,+secur32 log.

**Comment by ghost** [comment] 2018-12-26 17:09
Confirming that I no longer have this problem on Arch with 3.16-6. Great job with the fix guys, I hope it works for everyone else.

**Comment by ViktorWalter** [comment] 2018-12-26 23:27
> And same with
> Ubuntu 16.04
> Quadro K5000M @ 410.73

Sorry, I was on the wrong version. With 3.16-6 it works fine.

**Comment by mimattr** [comment] 2018-12-28 14:39
@kisak-valve unfortunately the multiplayer issue still exists with **Proton 3.16-6 Beta**, a consistent application crash occurs before any match starts (tested on Ubuntu 16.04 LTS):

[steam-379720.log](https://we.tl/t-ghEmH7qitc) (170MB, expires **Jan 4**)

[Steam System Information](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)

**Comment by alasky17** [comment] 2019-01-02 15:26
@mimattr From the log, it looks like you are still running into the libgnutls 26 problem.  Since steam-runtime still uses libgnutls 26, you need to have libgnutls 30 installed locally.  The log also looked like it picked up a libgnutls30 install, but perhaps it is broken?

**Comment by mimattr** [comment] 2019-01-12 04:13
> Since steam-runtime still uses libgnutls 26, you need to have libgnutls 30 installed locally. The log also looked like it picked up a libgnutls30 install, but perhaps it is broken?

@alasky17 Is there a preferred method to test this? Installing [gnutls-bin](https://packages.ubuntu.com/xenial/gnutls-bin) and executing the following command suggests **GNU TLS 3.4.10** is installed and working:

```
$ gnutls-cli --version
gnutls-cli 3.4.10
Copyright (C) 2000-2016 Free Software Foundation, and others, all rights reserved.
This is free software. It is licensed for use, modification and
redistribution under the terms of the GNU General Public License,
version 3 or later <http://gnu.org/licenses/gpl.html>

Please send bug reports to:  <bugs@gnutls.org>
```

**Comment by alasky17** [comment] 2019-01-14 14:30
@mimattr To double-check that libgnutls30 is installed, you can run "dpkg -l | grep libgnutls30" and make sure the lines have "ii" indicating they are installed (both the i386 and amd64 versions -- you may need both 32 and 64 bit).  

The dev who worked on the libgnutls update looked at your log and said that it looks like you are not on a recent enough version of Proton.  Just to make sure, you could delete the Proton 3.16 Beta folder from .steam/steam/steamapps/common and then verify the integrity of any game files with the beta selected in the Steam settings.  This will redownload the current version.

**Comment by mimattr** [comment] 2019-01-16 19:18
> you can run "dpkg -l | grep libgnutls30" and make sure the lines have "ii" indicating they are installed (both the i386 and amd64 versions -- you may need both 32 and 64 bit).

@alasky17 Executing the following command suggests **GNU TLS 3.4.10** is installed and working:
```
$ dpkg -l | grep libgnutls
ii  libgnutls-openssl27:amd64  3.4.10-4ubuntu1.4  amd64  GNU TLS library - OpenSSL wrapper
ii  libgnutls30:amd64          3.4.10-4ubuntu1.4  amd64  GNU TLS library - main runtime library
ii  libgnutls30:i386           3.4.10-4ubuntu1.4  i386   GNU TLS library - main runtime library
```

> you could delete the Proton 3.16 Beta folder from .steam/steam/steamapps/common and then verify the integrity of any game files with the beta selected in the Steam settings.

@alasky17 Unfortunately the issue still exists after deleting the following directories and validating the installation within Steam:

* `~/.steam/steam/steamapps/compatdata/379720`
* `~/.steam/steam/steamapps/compatdata/shadercache/379720`
* `~/.steam/steam/steamapps/common/Proton 3.16 Beta`

Updating to the [latest Steam Client Beta](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108822305086) has not resolved the issue either (**steam-runtime-beta-release_2019-01-10**)

Has anyone reported successful multiplayer functionality with a standard **Ubuntu 16.04 LTS** install?

**Comment by Zlopez** [comment] 2019-02-17 17:27
I tried it today with Proton 3.16-7 and the multiplayer is working. Didn't worked with whitelisted version.

Here are my [specs](https://gist.github.com/Zlopez/1433022f5f75aebc3155a622997b2997)

**Comment by BloodyIron** [comment] 2019-03-10 00:20
Crashing with 3.16-8 Beta as of today out of the box.

**Comment by BloodyIron** [comment] 2019-03-10 00:24
Installed GNUTLS 3.6.4 and still crashing. This time I'm crashing as I join in match making, before even loading... :/

Not a working user experience.

**Comment by Zlopez** [comment] 2019-03-10 09:48
Tried with 3.16-8 and the multiplayer is running fine. Finished one team deathmatch game without any issue.
[My specs](https://gist.github.com/Zlopez/1433022f5f75aebc3155a622997b2997)

**Comment by BloodyIron** [comment] 2019-03-10 16:48
@Zlopez maybe it's because you're AMD? I'm nvidia GTX 960, 418.43

**Comment by Zlopez** [comment] 2019-03-10 16:52
@BloodyIron Yes, this could be the case.

**Comment by Alexmitter** [comment] 2019-03-10 16:57
@BloodyIron @Zlopez  I can not say if that changed for the last proton version, but i was able to play MP with my 1060 and as well now with my Radeon VII

**Comment by BloodyIron** [comment] 2019-03-10 19:07
@Alexmitter what version of Steam Play you using? Any steps you had to take?

**Comment by alasky17** [comment] 2019-03-11 13:48
@BloodyIron To start, could you get a log with these channels: +bcrypt,+secur32,+wininet,+winhttp,+winsock   You can do this by editing user_settings.py in $HOME/.steam/steam/steamapps/common/Proton 3.16 Beta.  

Also, make sure that you switched to the 3.16 Beta in the properties for DOOM itself - a recent change to Steam means that you now have to specify Proton version in the game specific settings for any whitelisted title.  (Sorry if you know this already, just wanted to cover the bases).

**Comment by BloodyIron** [comment] 2019-03-11 16:41
@alasky17 I'll get that for you in a bit :)

**Comment by BloodyIron** [comment] 2019-03-13 01:47
@alasky17 need some clarification please.

1. I don't have a user_settings.py file, do you want me to just copy from the default example file?
2. Do you want me to _add_ those parameters and commas to the "WINEDEBUG" compoonent, or replace the default ones?
3. Once I've tried multiplayer with those things set, then what? You want logs, or? And from where?

**Comment by alasky17** [comment] 2019-03-13 12:47
@BloodyIron thank you for the questions :)
1) Yes, you can just cp the user_settings.sample.py file to user_settings.py in the same folder.
2) Yes, you can edit user_settings.py and add the extra channels on the winedebug line with the same formatting as the rest of the line. 
3) After setting up user_settings.py, a log with those parameters will be created automatically when you launch a Proton game and stored in your home directory $HOME or ~.  The log will have the game steam ID in the title, and if you launch a game again without renaming the log, it will be overwritten with the new launch.  

After setting up the logging, please launch DOOM and navigate until you hit the crash and the game exits so that the log will include the crash.  I believe that you can upload the file by dragging it onto your github comment while you are editing it. 

I hope this made the process more clear!

**Comment by BloodyIron** [comment] 2019-03-16 19:01
[steam-379720-Crash-Proton-Multiplayer-BloodyIron-Mar16-2019.zip](https://github.com/ValveSoftware/Proton/files/2974301/steam-379720-Crash-Proton-Multiplayer-BloodyIron-Mar16-2019.zip)

Tada! \o/

Also, your clarification most certainly did help! Thanks! :D 

Man that 7.6MB file took forever to upload, WTF MS?

**Comment by alasky17** [comment] 2019-03-18 17:38
@BloodyIron thank you!  I will take a look at those logs.

@mimattr We made some more changes to the code that touches the gnutls work.  If you are still seeing the same problem with 3.16-8 Beta, could you also provide a +bcrypt,+secur32,+wininet,+winhttp,+winsock log?  I have outlined how to do to that in some comments above if you are unsure.  Thank you for being patient!

**Comment by alasky17** [comment] 2019-03-18 21:37
@BloodyIron could you also attach your system specs?  The info is all listed in the Steam menu under Help -> System Information  and you can copy that into an attachment.  Thank you!

**Comment by BloodyIron** [comment] 2019-03-19 00:40
<details><summary>System Information</summary>
<p>

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 2600 Six-Core Processor            
    CPU Family:  0x17
    CPU Model:  0x8
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3400 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2019-01-10

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 960/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 418.43
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 119 Hz
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 5760 x 1080
    Primary Display Size: 20.51" x 11.54" (23.50" diag)
                                            52.1cm x 29.3cm (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 72 HDMI/DP

Memory:
    RAM:  16033 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Total Hard Disk Space Available:  468426 Mb
    Largest Free Hard Disk Block:  253620 Mb
    VR Headset: None detected

Recent Failure Reports:

</p>
</details>

**Comment by BloodyIron** [comment] 2019-03-19 00:41
doesn't seem to accurately represent my soundcard though lol:

28:00.3 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) HD Audio Controller

**Comment by mimattr** [comment] 2019-03-23 16:00
> We made some more changes to the code that touches the gnutls work.

@alasky17 Confirmed, the multiplayer mode now functions as expected with **Proton 3.16-8 Beta**.

@kisak-valve Once **Proton 3.16-8 Beta** becomes stable the [SteamPlay whitelist](https://steamdb.info/app/891390/) should be updated, currently **Proton 3.7-8** does not provide the full product experience.

As always kudos to all involved for their continued time and support on this issue!

**Comment by BloodyIron** [comment] 2019-03-23 16:31
Why is that version working for you and not me I wonder?

**Comment by mimattr** [comment] 2019-03-24 14:25
> Why is that version working for you and not me I wonder?

@BloodyIron Are you able to play the singleplayer campaign without issues? If so open a terminal window and execute the following command:

`dpkg -l | grep gnutls && locate libgnutls`

Copy the output and either save it as a text file or ideally [create a gist](https://gist.github.com/), which can then be added to this discussion for further analysis.

Hopefully that will help highlight any potential problems.

**Comment by BloodyIron** [comment] 2019-03-24 17:37
I was able to play several single player levels without installing gnutls, without observed issue, but as part of recent multiplayer troubleshooting I figured I'd try installing it, and it did not solve the crashing.

Installed version of gnutls : gnutls-bin/cosmic-updates,now 3.6.4-2ubuntu1.1 amd64 [installed]

**Comment by alasky17** [comment] 2019-03-25 13:27
@BloodyIron one more question (for now) - when exactly are you seeing the crash?  Is it crashing when you try to enter a multiplayer instance after the server has indicated that there are enough players to start a session? or some other time (or inconsistent)?

**Comment by BloodyIron** [comment] 2019-03-25 14:22
This, consistently, happens right after all players have been matched for a game, then it looks like each player is told to connect to the server, and that's when I crash. At least, that's what I'm seeing from the UX perspective.

**Comment by alasky17** [comment] 2019-03-26 18:58
@BloodyIron From the initial log, it looks like this is a different problem from the gnutls issue.  Could you follow the same method and create a new log with ~~+d3d~~ +vulkan added to the logging channels as well?  This will likely slow the game down quite a bit, so make sure to delete it afterwards :)

**Comment by kisak-valve** [comment] 2021-09-01 16:06
Hello, please retest this game with Proton 6.3-6 and see if any regressions have crept in since this issue was last evaluated.

**Closed as completed** 2021-10-01 16:47 UTC
Labels: Whitelist Update Request
