### ISSUE TITLE
Add a virtual desktop setting

### ISSUE THREAD

**Issue by DanielRios549** [ValveSoftware/Proton#3114] opened 2019-10-01 22:38 UTC
I have played a lot of games, and most of them have problems with a black screen when I switch to another program and go back to the game, the only way is to kill the game using xkill or system monitor.

I always use Q4Wine to enable the virtual desktop and this fix not only the black screen, but some problem with resolution, some games do not fit the entire screen without the virtual desktop, like Bully for example.

## I confirm:
- [x ] that I haven't found another request for this feature.
- [x ] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description

An option to enable the virtual desktop and a select input to change the resolution.

**Comment by kisak-valve** [comment] 2019-10-01 22:44
Hello @DanielRios549, this functionally a duplicate of #24. Closing in favor of the existing feature request.

**Closed as completed by kisak-valve** 2019-10-01 22:44 UTC

**Comment by DanielRios549** [comment] 2019-10-01 23:11
@kisak-valve Thanks man, this is what I wanted, a button to open winecfg is even better than a simple option to set the virtual destkop.
