### ISSUE TITLE
(Fixed) video stop working (and because of that have to restart the pc) (update: systemd-oomd can kill your video)

### ISSUE THREAD

**Issue by 00pandora00** [ValveSoftware/Proton#7101] opened 2023-09-15 00:12 UTC
hi, i have seen this problem with multiple games to this point, i think no one has commented it.

The problem is simple:

1.i run a game
2. the game run "fine"
3. heavy load in gpu occurs for an x period of time in a random scene of the game (note: the game does not freeze, i only hear the fans of the GPU running faster).
4. video of the pc  dies.
5.  i have to restart the pc. 

Additional Notes:

OS: Fedora Linux 38
Gpu: Amd R7 250 (yea i know, old gpu.)
Plaform where i run the games: Heroic Launcher 
Games with the problem: Pillars of Eternity - Definitive Edition, Rocket league, Tyranny - Gold Edition

(If more info is needed i will provide it, to the extent appropriate)

**Comment by simifor** [comment] 2023-09-15 14:56
This sounds like a driver issue. Are you using amdgpu or radeon kernel drivers? If you install inxi and use `inxi -G` it'll give you that information.
You should also use journalctl to find more information regarding what was happening at the time, for example:
`journalctl -rb -1`will bring the log from your last session (your previous boot) and show the last messages at the top as your problem is likely reflected at the top.
You can also use `journalctl -rb -1 > journal.txt` to put it into a file and upload here.

**Comment by 00pandora00** [comment] 2023-09-16 16:00
> This sounds like a driver issue. Are you using amdgpu or radeon kernel drivers? If you install inxi and use `inxi -G` it'll give you that information. You should also use journalctl to find more information regarding what was happening at the time, for example: `journalctl -rb -1`will bring the log from your last session (your previous boot) and show the last messages at the top as your problem is likely reflected at the top. You can also use `journalctl -rb -1 > journal.txt` to put it into a file and upload here.

Gpu: AMD Oland XT [Radeon HD 8670 / R5 340X OEM R7 250/350/350X OEM]
driver: radeon 

the posible error (i dont sure, i Am new using journalctl)

(Line 1):Process 1972 (gnome-shell) crashed in g_type_check_instance_is_fundamentally_a()
(Line 2): gkr-pam: unable to locate daemon control file

**Comment by simifor** [comment] 2023-09-16 16:30
second line is unrelated, and first line seems more like a symptom rather than the actual problem. I recommend you just the `journalctl -rb -1 > journal.txt` and upload the journal.txt file here.

Additionally, the radeon drivers are very old and don't support vulkan, there is a way to use the new amdgpu instead, but they are considered "experimental" for your generation of cards and the process might be a bit complicated, as you have to add a kernel launch parameter, and blacklist radeon.

**Comment by 00pandora00** [comment] 2023-09-16 19:44
> second line is unrelated, and first line seems more like a symptom rather than the actual problem. I recommend you just the `journalctl -rb -1 > journal.txt` and upload the journal.txt file here.
> 
> Additionally, the radeon drivers are very old and don't support vulkan, there is a way to use the new amdgpu instead, but they are considered "experimental" for your generation of cards and the process might be a bit complicated, as you have to add a kernel launch parameter, and blacklist radeon.

first, I will decline your proposition of the file ( i have Security concerns about that). But i can provide more lines of the journalctl (reviewing them myself).

second, if the think you says about the drivers is true, i will wait until my distro provides the drivers (i dont want to end breaking my O.S).

**Comment by simifor** [comment] 2023-09-16 21:11
An update isn't going to provide the drivers because the problem isn't your distro, the problem is your card. The `amdgpu` driver first released in 2015, so it must be available in your distro's kernel, but it's only enabled by default on third generation GCN cards and newer, while your card is a first generation GCN card so your card defaults to `radeon`. `amdgpu` supports first and second generation GCN cards* but it's marked as "experimental" so you have to enable the kernel module manually for it to be used.

*I was using such cards until recently and `amdgpu` worked fine, but at this point I don't think it'll ever be enabled because the new display code doesn't support analog output (this can be worked around in the same place you enable amdgpu) but the fact of the matter is that at this point, I doubt upstream will ever enable `amdgpu` by default on your card.

**Comment by 00pandora00** [comment] 2023-09-16 23:25
> An update isn't going to provide the drivers because the problem isn't your distro, the problem is your card. The `amdgpu` driver first released in 2015, so it must be available in your distro's kernel, but it's only enabled by default on third generation GCN cards and newer, while your card is a first generation GCN card so your card defaults to `radeon`. `amdgpu` supports first and second generation GCN cards* but it's marked as "experimental" so you have to enable the kernel module manually for it to be used.
> 
> *I was using such cards until recently and `amdgpu` worked fine, but at this point I don't think it'll ever be enabled because the new display code doesn't support analog output (this can be worked around in the same place you enable amdgpu) but the fact of the matter is that at this point, I doubt upstream will ever enable `amdgpu` by default on your card.

i see. them i have two option:
1. update my GPU.
2. manually enable that option. 
i think i will go with the second option. but thanks for the info (maybe i will try the first option if i get a second pc).

**Comment by simifor** [comment] 2023-09-17 19:55
You could still try to check your logs in case it's something that can be somehow resolved... I recommend you look into magic key combos (some distros have it enabled by default, in others you need to enable them), some general info about them https://en.wikipedia.org/wiki/Magic_SysRq_key . But something that'd work for you is using the keys `REISUB`, that way you should be able to reboot without forcing a shutdown with your computer's ON button. The faster you get to turn off your machine, the fewer lines you'd have to check, as the actual error should appear closer to the top.

**Comment by 00pandora00** [comment] 2023-09-18 19:07
> You could still try to check your logs in case it's something that can be somehow resolved... I recommend you look into magic key combos (some distros have it enabled by default, in others you need to enable them), some general info about them https://en.wikipedia.org/wiki/Magic_SysRq_key . But something that'd work for you is using the keys `REISUB`, that way you should be able to reboot without forcing a shutdown with your computer's ON button. The faster you get to turn off your machine, the fewer lines you'd have to check, as the actual error should appear closer to the top.

i will try to check again when i have time. and them report here

**Comment by 00pandora00** [comment] 2023-09-20 17:55
> An update isn't going to provide the drivers because the problem isn't your distro, the problem is your card. The `amdgpu` driver first released in 2015, so it must be available in your distro's kernel, but it's only enabled by default on third generation GCN cards and newer, while your card is a first generation GCN card so your card defaults to `radeon`. `amdgpu` supports first and second generation GCN cards* but it's marked as "experimental" so you have to enable the kernel module manually for it to be used.
> 
> *I was using such cards until recently and `amdgpu` worked fine, but at this point I don't think it'll ever be enabled because the new display code doesn't support analog output (this can be worked around in the same place you enable amdgpu) but the fact of the matter is that at this point, I doubt upstream will ever enable `amdgpu` by default on your card.

update on this: in the end. i update the drivers (update to amdgpu drivers) but the problem remains ( i only try the sims 4 with the new drivers).

that said, i am starting to thing is a gpu memory problem. because it only happens when i play a game with more requeriments than usuals, and my gpu only 1gb of memory.

but is weird, Shouldn't the game just freeze? o meaby is systemd-oomd of fedora closing services when go off memory

**Comment by simifor** [comment] 2023-09-21 02:28
ideally, the game should just be killed by the oom killer if you're running out of ram, but reality isn't always so kind. Are you sure you're using amdgpu? `inxi -G` will tell you.

If you want to check your memory as you play the game, you can use mangohud to see it in real time https://github.com/flightlessmango/MangoHud to enable it on steam, you go to the game's properties and the following to Launch Options: `mangohud %command%`. you can also make extra logs by adding `PROTON_LOG=1` to the launch parameters (in this case, `PROTON_LOG=1 mangohud %command%` this will create a file in your user's home folder with the following format `steam-appid.log` (the appid for sims 4 is 1222670) and it will contain information about the attempted run of the game.

**Comment by 00pandora00** [comment] 2023-09-21 15:41
> ideally, the game should just be killed by the oom killer if you're running out of ram, but reality isn't always so kind. Are you sure you're using amdgpu? `inxi -G` will tell you.
> 
> If you want to check your memory as you play the game, you can use mangohud to see it in real time https://github.com/flightlessmango/MangoHud to enable it on steam, you go to the game's properties and the following to Launch Options: `mangohud %command%`. you can also make extra logs by adding `PROTON_LOG=1` to the launch parameters (in this case, `PROTON_LOG=1 mangohud %command%` this will create a file in your user's home folder with the following format `steam-appid.log` (the appid for sims 4 is 1222670) and it will contain information about the attempted run of the game.

first, yea i checked the inxi -G info and show amdgpu as the driver. 

second, the problem was the  systemd-oomd of fedora. i disabled it,  run the game in practically the same way (doing  practically the same things in game) and the game dont crashed.

(I even have Firefox running 10+ tabs in the background and nothing)

systemd-oomd of fedora is a nightmare

"solution" = disable  systemd-oomd

Note: if the problem show up again i will comment that here.

**Comment by kisak-valve** [comment] 2023-09-21 15:44
Hello @00pandora00, it may be worthwhile to follow up with your video driver vendor / distro package maintainer.

Closing as not a Proton issue.

**Closed as completed by kisak-valve** 2023-09-21 15:44 UTC

**Comment by simifor** [comment] 2023-09-21 16:20
You can try creating an account on fedora's issue tracker and writing the problems you're having here https://bugzilla.redhat.com/show_bug.cgi?id=1941170
