### ISSUE TITLE
Add winecfg option

### ISSUE THREAD

**Issue by mrdeathjr28** [ValveSoftware/Proton#269] opened 2018-08-23 12:34 UTC
Actually winecfg per game could be access if wine stay installed previously on system

WINEPREFIX=/home/username/.steam/steamapps/compatdata/steamappid/pfx/ /opt/wine-staging/bin/winecfg

But could be complicated for new users and configure can give access to virtual desktop (this solve issues in various games) or csmt on - off (dont all titles needed and various games work incorrectly if stay active)

**Comment by vanyasem** [comment] 2018-08-23 12:49
Duplicate of #24

**Comment by kisak-valve** [comment] 2018-08-23 15:27
Closing as a duplicate of #24.

**Closed as completed by kisak-valve** 2018-08-23 15:27 UTC
