### ISSUE TITLE
Unable to start VR games with Proton 3.16-1

### ISSUE THREAD

**Issue by MagZu** [ValveSoftware/Proton#1731] opened 2018-10-13 20:15 UTC
# Compatibility Report
- Name of the game with compatibility issues: Beat Saber
- Steam AppID of the game: 620980

## System Information
- GPU: Nvidia Geforce 1070
- Driver/LLVM version: 410.57
- Kernel version: 4.18.12-1
- https://gist.github.com/magzu/e11263f54f0be95eeb65570d301b4261
- Proton version: 3.16-1 Beta

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Beat Saber: https://gist.github.com/magzu/1aec36540961038b724defa71c4b14b8
Gal Gun VR: https://gist.github.com/magzu/0fdc5972b16ab6b8b4ae76ee124da9a0
SkyrimVR: https://gist.github.com/magzu/180431c08a9cfcef877d8f8f84678693
The Forest VR: https://gist.github.com/magzu/1cb10d847c83131ffb178e967ed2c97f

## Symptoms 
With the new Proton 3.16-1 Beta i have been unable to launch any VR games with SteamVR
Games tested:
Beat saber Crashes on start.
SkyrimVR Starts a black window with 1 drum sound then freezes.
The Forest VR Crashes on start.
Gal Gun VR: Unity crash message then nothing.

Have also tried a fresh prefix folder but still same issue

## Reproduction

Just start a VR game with Proton 3.16-1 beta

**Comment by Tuuvimer** [comment] 2018-10-13 22:09
Possibly related?

Installing drivers from https://developer.nvidia.com/vulkan-driver (396.54.09) with the latest vulkan extensions (~~as of this time .09 is not available from the PPA~~ also happens with the PPA version) leads to Beat Saber and Orbus VR to crash on startup with an access violation.
Skyrim VR just gets stuck on a black screen.
A non-VR game like Witcher 3 loaded and played as normal (with NVIDIA Hair etc. working).

Uninstalling 396.54.09 and going back to nvidia-driver-396, while still running Proton 3.16-1, and they all run fine again. (but without device support for the new extensions)

**Comment by kisak-valve** [comment] 2018-10-13 22:14
Looks like Google Earth VR is not affected by this.

**Comment by MagZu** [comment] 2018-10-13 22:44
Went and tested Google Earth VR and works fine on my system as well.

**Comment by FictionX** [comment] 2018-10-14 14:55
Same (only they crash with both 396.54.09 and 396.54.05 for me). Only Google Earth VR works, and has way better performance with .09 than before. Other games crash - including whitelisted games like Superhot.

**Comment by elypter** [comment] 2018-10-15 18:23
>Uninstalling 396.54.09 and going back to nvidia-driver-396, while still running Proton 3.16-1, and they all run fine again.

its probably nothing nvidia related because it also happens with my rx580

**Comment by aeikum** [comment] 2018-10-17 12:16
Can you please retest this with Proton 3.16-2, released last night? You can use the "Verify Local Files" option on the Proton 3.16 tool to ensure it is up to date.

**Comment by Tuuvimer** [comment] 2018-10-17 13:43
Everything seems to work on my end.
Beat Saber, Orbus VR and Skyrim VR all launch and run. (hands in Orbus appear (transform/new vulkan extensions), so that's working too)

**Comment by MagZu** [comment] 2018-10-17 15:30
I can confirm that this issue is resolved in Proton 3.16-2 tested the mentioned games and they now work as before. good work!

**Comment by elypter** [comment] 2018-10-17 15:36
vrchat works as well

**Comment by FictionX** [comment] 2018-10-17 20:11
Some games such as Racket: NX, Pavlov, Operation Warcade VR and Crisis VRigade that had the issue with missing objects in earlier versions (proton 3.7-8 and earlier) seems to have been fixed with 3.16-2.

However, several games that would start with 3.7-8 but were missing objects now won't start at all, but instead crash with an access violation. Examples are Job Simulator and Bounce.

SuperHot VR and and Soundstage which worked perfectly before (no missing objects and great performance) also crash at startup.

**Comment by Plagman** [comment] 2018-10-18 02:50
Can others confirm SUPERHOT VR not working at all on 3.16?

**Comment by MagZu** [comment] 2018-10-18 05:47
Tested SUPERHOT VR with 3.16-2 and 3.16-3
Crashed on both versions.
Here are the gists:
3.16-2: https://gist.github.com/magzu/ac6ba90c417d253fae3679c6889797be

3.16-3: https://gist.github.com/magzu/ca9b3d52f2f4c0df1732491fda04fe5a

It crashes with a unity styled crash message popping up that are saying the logfiles were stored somewhere. I can provide those logs as well if they are of interest.

**Comment by jozefkucia** [comment] 2018-12-01 10:15
SUPERHOT VR doesn't crash with `PROTON_USE_WINED3D=1` for me. Please retest with `PROTON_USE_WINED3D=1 %command%`.

**Comment by frostworx** [comment] 2018-12-01 21:13
I can confirm that Superhot VR works using PROTON_USE_WINED3D=1, jozefkucia! thanks!

**Comment by jozefkucia** [comment] 2018-12-01 21:37
@frostworx Thanks for testing. In this case, it is most likely a DXVK regression.

**Comment by FictionX** [comment] 2018-12-03 21:00
Superhot VR works for me with PROTON_USE_WINED3D=1 %command% as well - but with worse performance than in 3.7-8. Same goes for Job Simulator (where objects were missing in 3.7-8).

**Comment by doitsujin** [comment] 2018-12-04 17:56
Reverting doitsujin/dxvk@a3bf90f5a3fe050ffae353f80bc5608c7c9a1244 in DXVK should fix the issue.

**Comment by valentindavid** [comment] 2018-12-08 12:37
Thank you @doitsujin , that fixes it. I have built Proton with this reverted and now Job Simulator works perfectly.

**Comment by aeikum** [comment] 2018-12-12 14:16
This commit was included in Proton 3.16-5. Please retest to confirm it's fixed.

**Comment by FictionX** [comment] 2018-12-18 11:08
Both Superhot VR and Job Simulator starts works flawlessly (as far as I can tell from brief tests) without any workarounds with 3.16-5.
Thanks!

**Comment by kisak-valve** [comment] 2019-01-18 22:50
Thanks for retesting, closing as fixed in Proton 3.16-5.

**Closed as completed by kisak-valve** 2019-01-18 22:50 UTC
Labels: Game compatibility, cw

**Comment by yesmar12** [comment] 2019-09-13 03:26
I am having a similar issue to this. When I open up beatsaber on the desktop it crashes. But if I open it from the headset it works fine. 

Also it seems that steam is unable to tell that beatsaber crashed, cause I am still listed as playing beatsaber and have the option to exit. Trying to exit the game through the steam ui, is ineffective and fails quietly. If I kill the process called steam child monitor ( or something like that) I can then start the game from the headset.

**Comment by kisak-valve** [comment] 2019-09-13 12:55
Hello @yesmar12, please open a new issue report.
