### ISSUE TITLE
[Whitelist] Elder Scroll Online [306130] (PROTON_NO_ESYNC=1)  but need optimization

### ISSUE THREAD

**Issue by julianovs** [ValveSoftware/Proton#863] opened 2018-08-28 21:21 UTC
with the parameter PROTON_NO_ESYNC=1 work good !!

without the parameter PROTON_NO_ESYNC=1  stuck in bethesda logo !!

one thing I noticed was the following:

running the game natively on windows 10, when you're in a city with a lot of players fps drops from 80 to a 42 (a bit of lag for a few seconds, nothing much)

running the game in linux using proton, when you're in a city with a lot of players fps drops from 80 to a 33-37 (here bottlenecks happen and this is something annoying)

I think the proton project needs to be optimized as much as possible because it will have a bigger performance problem with multiplayer games with large numbers of players, for example MMO RPGS

FOR SINGLE PLAYER GAMES I DO NOT SEE PROBLEM, I BELIEVE THAT THE BIGGEST CHALLENGE WILL BE ON LONG SCALE MULTIPLAYER

**Comment by Dazarlin** [comment] 2018-08-28 22:07
I can confirm the findings of @julianovs although my numbers for frames are quite a bit lower due to my weaker system, though it's still very playable. Main issue I have with ESO is the long loading times. These also existed on Windows however. Likely due to the fact that I'm loading everything off of a HDD. I fully agree that in the long run the biggest problem seems like it'll be multiplayer games in general and more specifically MMOs. We'll see however.

I fully agree that the way that ESO performs should indicate that if the addition of the PROTON_NO_ESYNC=1 setting being applied at installation were possible, this game could be added to the whitelist and a fairly popular MMORPG would be easily available on Linux.

Here's my system info if needed: https://gist.github.com/Dazarlin/1fe5b3d929f71f1f3f598c5b99d0c262

**Comment by julianovs** [comment] 2018-08-28 22:17
more players = more animations, more effects, higher load of cpu and gpu

if running natively in the windows you already have sharp drops of fps in regions populated by players so imagine this in proton

**Comment by julianovs** [comment] 2018-08-28 22:20
my system: dual boot win10/linux mint 19
cpu intel core i7 7700 3.60ghz
16 gb memory 
geforce gtx 1080 ti
2 ssd  240gb

**Comment by kisak-valve** [comment] 2018-08-29 13:11
Hello @julianovs, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/556#issuecomment-416946928.

**Closed as completed by kisak-valve** 2018-08-29 13:11 UTC
