### ISSUE TITLE
ESO launcher shows borders since 5.0

### ISSUE THREAD

**Issue by maboleth** [ValveSoftware/Proton#3508] opened 2020-02-09 19:47 UTC
Latest proton 5.0.1 here.

ESO compatibility seems flawless, however since upgrading proton to 5.0, launcher has fake window borders, that shouldn't be there. On Proton 4.11.12 everything is fine.

Take a look at the screenshot with latest proton:
![eso-launcher](https://user-images.githubusercontent.com/2467520/74108701-44790b00-4b7d-11ea-8200-fd0e7d131d85.jpg)

**Comment by kisak-valve** [comment] 2020-02-09 20:10
Hello @maboleth, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #556, however, this has also been reported as a general issue with launchers at #3495.

Closing as a duplicate of #3495.

**Closed as completed by kisak-valve** 2020-02-09 20:10 UTC
