### ISSUE TITLE
The Ultimate Doom (2280) rerelease

### ISSUE THREAD

**Issue by xDShot** [ValveSoftware/Proton#4172] opened 2020-09-05 08:32 UTC
# Compatibility Report
- Name of the game with compatibility issues: The Ultimate Doom
- Steam AppID of the game: 2280

## System Information
- GPU: AMD Radeon RX5700
- Driver/LLVM version: Mesa 20.1.7 llvm 10.0.1
- Kernel version: 5.8.5
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/xDShot/8e9ae635b715265059e09bb21f592afa
- Proton version: 5.0-9

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

Black screen when launched from Steam. Works if launched directly outside of Steam with system Wine.

**Comment by kisak-valve** [comment] 2020-09-05 12:55
Hello @xDShot, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by xDShot** [comment] 2020-09-06 00:02
@kisak-valve 

[steam-2280.log](https://github.com/ValveSoftware/Proton/files/5178902/steam-2280.log)

**Comment by kisak-valve** [comment] 2020-09-06 00:16
Thanks, `err:strmbase:STRMBASE_DllGetClassObject {271c3902-6095-4c45-a22f-20091816ee9e}: no class found in C:\windows\system32\winegstreamer.dll.` looks like a line of interest from the log.

This hints that you're using a wine-staging build for your system wine and https://github.com/wine-staging/wine-staging/blob/master/patches/mfplat-streaming-support/0007-Implement-stub-bytestream-handler-and-source.patch is what's making the difference.

**Comment by xDShot** [comment] 2020-09-06 08:17
Recompiled proton by @Tk-Glitch with no luck

**Comment by xDShot** [comment] 2020-09-06 10:11
Current workaround is to remove or rename all video files and repeatedly press space until you get on menu.
Hangs when quitting the game. Need to kill process or stop it from Steam library.

**Comment by RondoRevolution** [comment] 2020-09-07 19:25
My game also froze with a black screen when using default Proton. But it looks like GloriousEggroll's version works without problems, displaying the logos properly and going to the menu. (I used Proton-5.9-GE-5-ST for testing).

**Comment by dpanter** [comment] 2020-09-08 18:34
Adding feedback from my own testing. [Steam system information Github gist](https://gist.github.com/dpanter/7ac9050fef342ccffd7f7df7257bc30a)
8700k, 1080ti 450.66, Siduction (Debian sid based) 5.7.16, KDE Plasma 5.17.5

- **3.7-8** (whitelist): game starts to a black screen. Press space 4 times to bypass, can then play game normally. Hangs on exit. Can kill it with Steam client stop button.
- **5.0-10-rc4**: same behavior as 3.7-8.
- **Proton-5.9-GE-5-ST**: everything works. Intro videos play, game plays normally, exiting game works as expected.

Logfiles from these tests are ~30MB each, so I uploaded them to [gofile.io](https://gofile.io/d/fROhF7)

**Comment by rliden** [comment] 2020-09-08 21:10
My feedback after some testing. 
[Steam System Info](https://gist.github.com/rliden/1d1f113b7251073e53bae85b475e944a): Fedora 32 Workstation, Kernel 5.8.6, Ryzen 7 3700X, 32GB, GTX 1660Ti (450.66)

- **3.7-8 (official/approved)**: Program launches to a black screen, no logos, no sound. Press spacebar (4 times) to bypass and enter the game. Bethesda net login pops up and requests user/password and does not automatically link to the Steam account. Program does not exit cleanly and must be killed with the Steam "Stop" button or the system.
- **Proton-5.9-GE-5-ST (glorious eggroll custom)**: Program launches as expected and automatically links my previously authenticated Steam account to Bethesda. The application exits normally.

Logfiles are large as mentioned above. I also put them on [gofile](https://gofile.io/d/5WSIEr).

**Comment by D-357** [comment] 2020-09-17 10:47
I tried exiting while using Proton 5.0.10-rc4 and it still hangs. The differences I see is that Glorious Eggroll loads 'kernelbase.dll' as load_native_dll, instead of mine with load_dll

<details><summary>Log snippet</summary><p>

```
52410.206:00a4:00a5:trace:module:find_forwarded_export delay loading L"kernelbase.dll" for 'kernelbase.AppPolicyGetProcessTerminationMethod'
52410.206:00a4:00a5:trace:module:load_dll looking for L"kernelbase.dll" in L"Z:\\home\\user\\.local\\share\\Steam\\steamapps\\common\\Ultimate Doom\\rerelease;C:\\Program Files (x86)\\Steam;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem"
52410.206:00a4:00a5:trace:module:get_load_order looking for L"C:\\windows\\system32\\kernelbase.dll"
52410.206:00a4:00a5:trace:module:get_load_order got hardcoded default for L"kernelbase.dll"
52410.206:00a4:00a5:trace:module:load_dll L"C:\\windows\\system32\\kernelbase.dll" is a fake Wine dll
52410.206:00a4:00a5:trace:module:load_builtin_dll Trying built-in L"kernelbase.dll"
52410.206:00a4:00a5:trace:module:load_dll looking for L"kernel32.dll" in L"Z:\\home\\user\\.local\\share\\Steam\\steamapps\\common\\Ultimate Doom\\rerelease;C:\\Program Files (x86)\\Steam;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem"
52410.206:00a4:00a5:trace:module:load_dll Found L"C:\\windows\\system32\\KERNEL32.dll" for L"kernel32.dll" at 0x7b420000, count=-1
52410.206:00a4:00a5:trace:module:load_builtin_callback loaded kernelbase.dll 0x61440 0x7f41bbe80000
52410.206:00a4:00a5:trace:module:load_dll Loaded module L"C:\\windows\\system32\\kernelbase.dll" (builtin) at 0x7f41bbe80000
52410.206:00a4:00a5:trace:module:process_attach (L"kernelbase.dll",(nil)) - START
52410.206:00a4:00a5:trace:module:MODULE_InitDLL (0x7f41bbe80000 L"kernelbase.dll",PROCESS_ATTACH,(nil)) - CALL
52410.206:00a4:00a5:trace:module:MODULE_InitDLL (0x7f41bbe80000,PROCESS_ATTACH,(nil)) - RETURN 1
52410.206:00a4:00a5:trace:module:process_attach (L"kernelbase.dll",(nil)) - END
52410.206:00a4:00a5:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffffffffffa, 0x23fd20
52410.206:00a4:00a5:trace:module:LdrGetDllHandle L"mscoree.dll" -> (nil) (load path L"Z:\\home\\user\\.local\\share\\Steam\\steamapps\\common\\Ultimate Doom\\rerelease;C:\\Program Files (x86)\\Steam;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem")
52410.206:00a4:00a5:trace:module:LdrShutdownProcess ()
52410.206:00a4:00a5:trace:module:MODULE_InitDLL (0x7f41bbe80000 L"kernelbase.dll",PROCESS_DETACH,0x1) - CALL
52410.206:00a4:00a5:trace:module:MODULE_InitDLL (0x7f41bbe80000,PROCESS_DETACH,0x1) - RETURN 1
```

</p></details>

**Comment by ivyl** [comment] 2020-10-29 16:28
Same thing as https://github.com/ValveSoftware/Proton/issues/4253 - works with the mfplat patches applied, hangs on a blank screen without them.

**Comment by dpanter** [comment] 2020-10-29 19:08
Tested again with 5.13-1, same behavior as with 3.7-8 above.
8700k, 1080ti 455.23.04, Siduction (Debian sid based) 5.8.16, KDE Plasma 5.17.5 [System specs pastebin](https://pastebin.com/WZEGtvLG)
[Proton log gofile.io](https://gofile.io/d/wIk1YX)
[xsession-errors_2280.log attachment](https://github.com/ValveSoftware/Proton/files/5460709/xsession-errors_2280.log)

**Comment by ar664** [comment] 2022-10-05 18:58
I tested Doom (AppID: 2280) with Proton 7.0-4 on the Steam Deck (OS Version 3.3.1). I can confirm it works now without any problems or further configuration changes. @kisak-valve

**Comment by kisak-valve** [comment] 2022-11-11 19:46
Closing per the last comment.

**Closed as completed by kisak-valve** 2022-11-11 19:46 UTC
Labels: Game compatibility
