### ISSUE TITLE
whene library is on NTFS

### ISSUE THREAD

**Issue by Millie290** [ValveSoftware/Proton#1874] opened 2018-11-01 13:05 UTC
if your games are on ntfs part steamplay dosent work

**Comment by kisak-valve** [comment] 2018-11-01 14:18
Hello @Millie290, this issue is already being tracked on various issue reports including #11, #104, and your own issue report #1824. Closing as a duplicate of the existing issue reports.

**Closed as completed by kisak-valve** 2018-11-01 14:18 UTC
