### ISSUE TITLE
The Witcher Enhanced Edition (20900) with plenty of artifacts

### ISSUE THREAD

**Issue by elkanguro** [ValveSoftware/Proton#5276] opened 2021-11-01 18:41 UTC
Hello, in The Witcher Enhanced Edition (20900) I have plenty of artifacts in the game. I use Proton 3.7-8 because it was not possible to launch the game on the 6.3-7 version. Any advise what can solve the issue? I run the game on Lenovo G580 with Intel HD3000 GPU. Here is the screenshot from the Steam [https://steamcommunity.com/sharedfiles/filedetails/?id=2643316446](url)

**Comment by kisak-valve** [comment] 2021-11-01 19:09
Hello @elkanguro, Proton uses DXVK to translate DirectX 9 to Vulkan and the Intel HD 3000 graphics is part of the SandyBridge generation, which does not support Vulkan. A spec-compliant Vulkan GPU driver is required for Proton support, which makes your hardware unsupported by Proton. When Proton 3.7 was released, DXVK had not yet grown to support DirectX 9, so it was using wine's DirectX to OpenGL render path.

You could try newer Proton versions with `PROTON_USE_WINED3D=1 %command%`, but this is an unsupported launch option and if you're seeing the same issue with newer versions of Proton, then you'll need to reproduce the issue with vanilla wine and report your findings to the upstream wine issue tracker and/or the Intel mesa devs to ponder.

Closing due to the unsupported hardware.

**Closed as completed by kisak-valve** 2021-11-01 19:09 UTC
