### ISSUE TITLE
Final Fantasy XV (637650) Not Launching

### ISSUE THREAD

**Issue by srsgores** [ValveSoftware/Proton#6395] opened 2022-12-17 11:30 UTC
# Compatibility Report
- Final Fantasy XV
- SteamGameId: `637650`

## System Information
- GPU: AMD Radeon RX 6800/6800 XT
- Driver/LLVM version: `amdgpu v: kernel arch: RDNA-2 code: Navi-2x process: TSMC n7 (7nm)`
- Kernel version: `6.0.11-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 12.2.0`
- Proton version: `1670512927 experimental-7.0-20221208`

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game. (https://github.com/ValveSoftware/Proton/issues/74)
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
Game will not launch with any of Proton `7.0.2` **or** Proton `Experimental` via Steam

## Reproduction
1. Configure game to run with compatibility: `Proton Experimental`
2. Attempt to run on Steam 

## Log
```
======================
Proton: 1670512927 experimental-7.0-20221208
SteamGameId: 637650
Command: ['/run/media/seang/Installed Games and Applications/Program Files (x86)/Steam/steamapps/common/FINAL FANTASY XV/ffxv_s.exe']
Options: {'forcelgadd'}
depot: 0.20221018.74
pressure-vessel: 0.20221014.0
scripts: v0.20220823.0-0-gcc4e44f
soldier: 0.20221017.1 soldier 0.20221017.1
Kernel: Linux 6.0.11-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Dec 2 21:23:52 UTC 2022 x86_64
======================
```

**Comment by kisak-valve** [comment] 2022-12-17 14:50
Hello @srsgores, in general, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #74. However, `[...]/Installed Games and Applications/Program Files (x86)/Steam/steamapps/[...]` is a fairly strong hint that you're sharing a Steam library folder with a Windows install, and it's a likely assumption that it's on an NTFS formatted partition.

Sharing Steam libraries between OSes is not supported and can cause undefined behavior. (https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation)

Having said that, the header only Proton log hints that there's an issue with Proton's python script before the actual game has a chance to run. You could completely close Steam, then run `steam-runtime` from a terminal and see if there's a better hint there, but I expect that it'll match up to one of the [existing NTFS issue reports](https://github.com/ValveSoftware/Proton/search?q=NTFS+-label%3A%22Game+Compatibility+-+Unofficial%22&type=issues).

You could give some of the suggestions in https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows a try, but the better recommendation is to use a linux native filesystem with Proton.

Closing as a duplicate of the various NTFS issue reports.

**Closed as not planned by kisak-valve** 2022-12-17 14:50 UTC
