### ISSUE TITLE
Jamestown+ (377950)

### ISSUE THREAD

**Issue by undu** [ValveSoftware/Proton#3320] opened 2019-12-14 11:59 UTC
# Compatibility Report
- Name of the game with compatibility issues: Jamestown+
- Steam AppID of the game: 377950

## System Information
- GPU: AMD R9 Nano
- Driver/LLVM version: 4.5 Mesa 20.0.0-devel (git-8a8381dd60) (from valveaur)
- Kernel version: 5.4.2-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/undu/a0067967688bdb254603a9b77af5a007
- Proton version: 3.7-8, 3.16-9, 4.2-9, 4.11-10

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[steam-377950.log](https://github.com/ValveSoftware/Proton/files/3963801/steam-377950.log)

## Symptoms 

Crash on startup

## Reproduction

Just try to launch the game.

Seems like the game works with nvidia drivers, but not with mesa and amd from the reports in [protondb](https://www.protondb.com/app/377950) and [steamcommunity](https://steamcommunity.com/app/377950/discussions/0/1643170269568283280/)

**Comment by sp0gg** [comment] 2022-06-11 20:41
+1 to this; worked fine when I had an nvidia card, now does not work after switching to AMD.

**Comment by Saroumane** [comment] 2022-06-12 08:56
Has anyone managed to run this game with "pure" wine + AMD ?

**Comment by pmaddaloni** [comment] 2022-07-22 21:08
Still broken as of latest proton experimental, and proton 7.0.3 :/

**Comment by waspennator** [comment] 2022-12-15 20:44
Apparently someone on the discussion hub has said one of the devs are looking into it. Though apparently they still aren't sure why it crashes, even with someone reverse engineering the game.

**Comment by sofakng** [comment] 2023-02-15 20:47
Really hoping this gets fixed... it's a great game.

**Comment by waspennator** [comment] 2023-05-25 19:00
Honestly starting to feel like this is a similar issue to Danmaku Unlimited 3 (working on nvidia Linux, broken on amd linux, but recently fixed), might need the devs to fix it on their end, but I dunno if they are still looking into it or if they are just working on their other titles instead.

Wonder if something is going on in the shader code that needs to be changed

**Comment by sofakng** [comment] 2023-05-25 19:47
I've reached out to the developers by every means possible as well as the publisher and haven't received a response.  As far as I can tell the game is completely abandoned which is unfortunate because it's probably not a huge effort to fix it.

**Comment by Saroumane** [comment] 2023-05-25 20:32
I think that Valve could find a workaround by making the game Nvidia/AMD agnostic, thanks to the Proton middleware.

**Comment by tarceri** [comment] 2023-05-26 04:39
A temporary workaround is to set the following in steams launch options:

force_compat_profile=true %command%

I've submitted the mesa workaround here:

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23246

**Comment by waspennator** [comment] 2023-05-26 13:48
> A temporary workaround is to set the following in steams launch options:
> 
> force_compat_profile=true %command%
> 
> I've submitted the mesa workaround here:
> 
> https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23246

I can confirm that using that workaround on deck no longer crashes the game before the first logo. Only tested a little bit, but it's enough to get me into gameplay too. There is small yellow box on the top left saying something about an error or something, but it went away after I started pressing buttons or towards the title screen.

**Comment by sofakng** [comment] 2023-05-26 18:06
> A temporary workaround is to set the following in steams launch options:
> 
> force_compat_profile=true %command%
> 
> I've submitted the mesa workaround here:
> 
> https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/23246

Thank you so much!!  I've been trying to play this for a long time!

I wonder if I can use this somehow on macOS (with WINE) to also have it work properly?

**Comment by waspennator** [comment] 2023-05-30 01:28
Looks like the workaround just got merged into mesa, so I'm guessing soon you won't even need to manually enter the launch command to play on deck, or on amd gpus in general.

**Comment by waspennator** [comment] 2023-06-08 21:30
The Workaround is finally present in Mesa 23.1.2.

**Closed as completed** 2023-06-09 18:16 UTC
Labels: Game compatibility - Unofficial, XAudio2, Mesa drivers

**Comment by waspennator** [comment] 2023-11-17 03:33
Update, just retested after latest stable os update and the game seems to work out of the box now without the launch command. Audio was a bit crackly on first test, but I relaunched it a few times and it only happened on first launch. I also don't see the yellow error box on the top left anymore.

Believe this game is ready to be bumped out of unsupported, played through 1 level without issue.
