### ISSUE TITLE
Use Python3.7

### ISSUE THREAD

**Issue by adds68** [ValveSoftware/Proton#59] opened 2018-08-22 07:47 UTC
Hi,

This is awesome stuff from Valve :)

However what is the reason for Proton to depend on Python2.7?

There is less than [2 years](https://pythonclock.org/) left for updates and it is recommended to switch to python3 ASAP

**Comment by daniel-j** [comment] 2018-08-22 07:48
https://github.com/ValveSoftware/Proton/pull/9

**Comment by kisak-valve** [comment] 2018-08-22 12:34
Closing as a duplicate of #9.

**Closed as completed by kisak-valve** 2018-08-22 12:34 UTC
