### ISSUE TITLE
The problem with the cursor in games launch via proton on SteamOS

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/Proton#3122] opened 2019-10-04 08:00 UTC
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 

The problem with the cursor in games launch via proton. This problem is seen only in SteamOS. On other operating systems the cursor works fine. After pressing any key the cursor becomes inactive or disappears.

**Comment by kisak-valve** [comment] 2019-10-04 12:53
Same as https://github.com/ValveSoftware/SteamOS/issues/695#issuecomment-538379450.

Closing as a duplicate of #2849, https://github.com/ValveSoftware/SteamOS/issues/475.

**Closed as completed by kisak-valve** 2019-10-04 12:53 UTC
