### ISSUE TITLE
[Whitelist] Ducktales: Remastered (237630)

### ISSUE THREAD

**Issue by jstuder-gh** [ValveSoftware/Proton#803] opened 2018-08-28 03:52 UTC
I'd like to recommend [Ducktales: Remastered](https://store.steampowered.com/app/237630/DuckTales_Remastered/) as a possible candidate for whitelisting. It worked flawlessly for me.

Played the game through to completion with a wired XBox 360 controller. Rumble, Achievements, Steam Cloud sync all worked for me. I did not notice any graphical glitches or slowdown.

The only issue I encountered was https://github.com/ValveSoftware/Proton/issues/287 but that was only a mild annoyance.

[Hardware Info](https://gist.github.com/jstuder-gh/f9b766c94e5e93c70528d2d27982a86f)

**Comment by ghost** [comment] 2018-08-28 04:46
Duplicate of #597

**Comment by kisak-valve** [comment] 2018-08-28 12:53
Transferred to https://github.com/ValveSoftware/Proton/issues/597#issuecomment-416572733 due to the game controller notes. Closing as a duplicate.

**Closed as completed by kisak-valve** 2018-08-28 12:53 UTC
