### ISSUE TITLE
proton 5.13-2 OpenGL Version: 2.1

### ISSUE THREAD

**Issue by tails2021** [ValveSoftware/Proton#4425] opened 2020-11-29 02:27 UTC
proton 5.13-2 OpenGL Version: 2.1
deus ex  human revolution director cut 
and deus ex the fall

**Comment by kisak-valve** [comment] 2020-11-29 02:39
Hello @tails2021, please do not intentionally open duplicate issue reports. Closing as a duplicate of #4424.

**Closed as completed by kisak-valve** 2020-11-29 02:39 UTC
