### ISSUE TITLE
DOOM 2016 - Mouse getting stuck. (379720)

### ISSUE THREAD

**Issue by raenii** [ValveSoftware/Proton#1364] opened 2018-09-09 17:54 UTC
# Compatibility Report
- Name of the game with compatibility issues: DOOM 2016
- Steam AppID of the game: 379720

## System Information
- GPU: GTX 1060 3gb
- Driver/LLVM version: nvidia 396.24
- Kernel version: 4.15
- Link to full system information report as [Gist](https://gist.github.com/waveneko/975d9a8f4accf919c5ba47b7f32cb18a):
- Proton version: The default/whatever it uses for DOOM 2016.

## I confirm:
- [ Y ] that I haven't found an existing compatibility report for this game.
- [ Y ] that I have checked whether there are updates for my system available.

## Symptoms 
On the menu, moving my mouse near the bottom or the right side will cause it to stop moving beyond that point until I push the cursor faster. In-game, the mouse will occasionally get stuck, making it difficult to aim. This issue has persisted throughout Ubuntu 18.04 and switching to Pop!_OS 18.04.
If it makes any difference, I've used Gnome Tweak Tool to turn off mouse acceleration. I also have any mouse smoothing in-game turned off.

## Reproduction
Boot up the game and try to move your mouse towards to bottom or the right side fairly slowly.

**Comment by kisak-valve** [comment] 2018-09-09 18:03
Hello @waveneko, can you check #147 and see if it is relevant to your system?

**Comment by raenii** [comment] 2018-09-09 18:09
Ah, yes, @kisak-valve. I must've missed that. I managed to fix the mouse on the main menu by enabling mouse acceleration again but the issue persists in-game. I'm also unable to change the polling rate of my mouse as I don't have a Windows system. Not that I would want to do that because I notice the difference between lower polling rates and it really screws up my aim in CS:GO and TF2.

**Comment by libcg** [comment] 2018-09-23 20:20
@kisak-valve this is indeed a duplicate of #147

**Comment by kisak-valve** [comment] 2018-09-23 20:23
Closing in favor of #147.

**Closed as completed by kisak-valve** 2018-09-23 20:23 UTC
Labels: Game compatibility
