### ISSUE TITLE
Garry's Mod no longer starts

### ISSUE THREAD

**Issue by xznhj8129** [ValveSoftware/Proton#2435] opened 2019-03-20 03:42 UTC
# Compatibility Report
- Name of the game with compatibility issues: GMod
- Steam AppID of the game: 4000?

## System Information
- GPU: Nvidia GTS 450
- Driver/LLVM version: NVIDIA-SMI 390.116 
- Kernel version: 4.15.0-46-generic
- Proton version: 3.16-8 Beta

## I confirm:
- [?] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.
Yes, It's since i updated that it stopped working
"Please add `PROTON_LOG=1 %command%` to the game's launch options and drag
and drop the generated `$HOME/steam-$APPID.log` into this issue report"
DID NOT WORK! No log generated!

## Symptoms 
Error.log: https://pastebin.com/mrmMeqXR
Gmod no longer starts. Was working fine with Proton 3.16-8 Beta (forcing Proton because native linux version literally unplayable, can't click in-game menus) and played for long hours without problems, now i do an apt update/upgrade, reboot, try starting gmod, and it immediately crashes. I added the PROTON_LOG to the options and it does absolutely nothing, no log is generated. Trying every other proton version yields the same failure.

**Comment by xznhj8129** [comment] 2019-03-20 07:31
FIXED: Tried playing another game on Proton to see if it worked, downloaded Factorio and set it to use Proton 3.16-8B. It downloaded the 300-400mb of Proton and launched. Some hard-prockilling later because of some a hang-on-launch, i tried Gmod again and it worked.
I have no idea why it did that.

**Comment by kisak-valve** [comment] 2019-03-20 12:49
Hello @snow-frog, you encountered https://github.com/ValveSoftware/steam-for-linux/issues/5963, which should have better behavior in Steam's beta client.

Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/6045.

**Closed as completed by kisak-valve** 2019-03-20 12:49 UTC
