### ISSUE TITLE
Latest Proton Experimental Fails To Open

### ISSUE THREAD

**Issue by cagelight** [ValveSoftware/Proton#4881] opened 2021-06-02 21:08 UTC
Proton Experimental (Build ID 6802103)

I cannot launch any games with the latest Proton Experimental as I get the following error:
```
Traceback (most recent call last):
  File "/home/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 1111, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 940, in init_session
    g_compatdata.setup_prefix()
  File "/home/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 697, in setup_prefix
    nvidia_wine_dll_dir = find_nvidia_wine_dll_dir()
  File "/home/.local/share/Steam/steamapps/common/Proton - Experimental/proton", line 152, in find_nvidia_wine_dll_dir
    libglx_nvidia = CDLL("libGLX_nvidia.so.0")
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGLX_nvidia.so.0: cannot open shared object file: No such file or directory
```
I have an AMD card and it should not be looking for "nvidia" anything.

**Comment by Vladimir-A** [comment] 2021-06-02 21:10
I have the same situation.

**Comment by ehea617** [comment] 2021-06-02 21:13
Also seeing the same issue here on an RX 570 with Mesa 20.3.4. Setting PROTON_ENABLE_NVAPI=0 %command% as a launch option does not help either.

**Comment by DadSchoorse** [comment] 2021-06-02 21:14
It's a known issue, and should hopefully be resolved soon.
https://github.com/ValveSoftware/Proton/pull/4878#issuecomment-853373269

**Comment by aeikum** [comment] 2021-06-02 22:40
Thanks for reporting. This should be fixed in an Experimental update that just went live (version `experimental-6.3-20210602b`).

**Comment by cagelight** [comment] 2021-06-02 22:47
Latest update fixed it for me!

**Comment by davidgrenier** [comment] 2021-06-02 23:13
Likewise.

**Comment by ehea617** [comment] 2021-06-03 03:58
The issue is resolved for me after updating. Thanks!

**Comment by kisak-valve** [comment] 2021-06-03 10:37
Closing as fixed by https://github.com/ValveSoftware/Proton/commit/cc7ad4bd13bb88ce194270908cc5243b8dc0613a.

**Closed as completed by kisak-valve** 2021-06-03 10:37 UTC
