### ISSUE TITLE
Steam language is not set in Proton regedit

### ISSUE THREAD

**Issue by legluondunet** [ValveSoftware/Proton#1476] opened 2018-09-16 01:18 UTC
Hello,

some games, like "Zeno Clash" (22200), use regedit string to set their interface language.
Like you can see, it is not set by default in Proton Regedit:
```

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Valve\Steam]
"Language"=""
```

So "Zeno Clash" game start only in english, even if Steam uses a different language.
I can not reproduce this bug on a Windows computer, so I think it is a Proton bug.
If I set the regedit string above to French, Zeno Clash will start with a french menu.
I don't know if there are some others games that are affected by this.
For most of the Steam games, language can be set in the properties, language tab.
But Zeno Clash has not a "language" tab.

https://gist.github.com/legluondunet/0f0a56fb4e9cb743f111385e554fce69

**Comment by tingvarsson** [comment] 2018-09-16 11:47
There was some other game and dont remember which one of course.. That didnt get correct text in menus but instead got placeholder names, sounds like something caused by no language configured.

**Comment by lieff** [comment] 2018-09-16 14:31
https://github.com/ValveSoftware/Proton/issues/1007 may be related to this.

**Comment by aeikum** [comment] 2018-09-17 12:32
Good find! Thanks for reporting.

**Comment by legluondunet** [comment] 2018-09-28 18:13
Bug is stil present in Proton 3.7-7 beta.

**Comment by CSahajdacny** [comment] 2019-02-06 17:44
This PROTON BUG affects Castle Of Illusion too...
On windows, the game automatically sets the language according the system language info. In my case, Spanish... 

But here, because of this serious PROTON issue where the regional settings of my machine are not detected, PROTON thinks I live in United States and not in Argentina... And because of this, Castle of illusion automatically set its language to English and there is no way to change it...

**Comment by nsivov** [comment] 2019-03-27 05:29
Please retest with 4.2-1, language should be inherited from client language now, ValveSoftware/Proton@70822d804.

**Comment by legluondunet** [comment] 2019-03-27 07:02
Can confirm it works with Zeno Clash, nice work!

**Comment by kisak-valve** [comment] 2019-05-03 13:12
Closing as fixed.

**Closed as completed by kisak-valve** 2019-05-03 13:12 UTC
