### ISSUE TITLE
All Windows games require 0 byte update every time the Steam client is launched

### ISSUE THREAD

**Issue by meowmeowfuzzyface** [ValveSoftware/Proton#316] opened 2018-08-23 19:48 UTC
The "update" completes almost instantly for every game.  Every time the Steam client is restarted, the Windows games must download this "update" again.  The Steam library folder is on a secondary ext4 hard drive on which I have full read/write permissions.  I'm on Ubuntu 18.04.

All native games and most Windows games I've tried so far run successfully, but the Windows games require this instant, 0 byte "update" to be installed before launching.  Also, the Windows games run their first time setup every time they are launched, but I'm not sure if it's related.  Native games don't have this problem.

**Comment by arzardk** [comment] 2018-08-23 19:55
This problem started to appear after today Proton update i guess.

**Comment by pprotonrep** [comment] 2018-08-23 19:59
See https://github.com/ValveSoftware/Proton/issues/130 and https://github.com/ValveSoftware/steam-for-linux/issues/5644

**Comment by meowmeowfuzzyface** [comment] 2018-08-23 20:02
Thanks, I will reply there.

**Comment by kisak-valve** [comment] 2018-08-23 20:03
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5644.

**Closed as completed by kisak-valve** 2018-08-23 20:03 UTC
