### ISSUE TITLE
Steam Locks Up Computer

### ISSUE THREAD

**Issue by CJ1169** [ValveSoftware/Proton#5343] opened 2021-11-24 02:34 UTC
Seems like several users are having an issue with steam spooling up wineservers and ultimately locking up PCs
link: https://www.reddit.com/r/linux_gaming/comments/qnfli7/psa_steam_is_creating_a_wineserver_process_that/
I can confirm I'm having this issue as well. Doing some more testing. Are there any suggestions on tests to perform to make this more efficient?
Preliminary testing shows steam spooling up a wineserver, running d3ddriverquery64.exe, and then doing it again with another compatibilitytools.d proton version.

System information:
Linux ceejay-desktop 5.14.18-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:24:59 UTC 2021 x86_64 GNU/Linux
Had previously tested with Steam Beta. I've switched to Steam standard to see if that does the trick.

**Comment by kisak-valve** [comment] 2021-11-24 02:50
Hello @CJ1169, this is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/8255. Please see the discussion on https://github.com/ValveSoftware/steam-for-linux/issues/8114. Closing as this is an issue with third party Proton builds and does not appear to affect the mainline releases.

**Closed as completed by kisak-valve** 2021-11-24 02:50 UTC

**Comment by CJ1169** [comment] 2021-11-24 03:07
I think you're correct in your commentary on the issue you linked. The symptoms do seem to line up with a quirk with old builds. I have plenty of GE copies in my folders and it only seems to be affecting older copies.

**Comment by mkrupczak3** [comment] 2021-12-08 04:43
bump
