### ISSUE TITLE
Black Screen in OpenGL Games with Proton 3.7-5 beta

### ISSUE THREAD

**Issue by sputniktr02** [ValveSoftware/Proton#1067] opened 2018-08-31 12:09 UTC
Recent Proton update (3.7-5 beta) have black screen issue in OpenGL games. Games effected in my testing are:

- RAGE
[steam-9200.tar.gz](https://github.com/ValveSoftware/Proton/files/2340259/steam-9200.tar.gz)

- Wolfenstein: The New Order
[steam-201810.tar.gz](https://github.com/ValveSoftware/Proton/files/2340260/steam-201810.tar.gz)

- Wolfenstein: The Old Blood
[steam-350080.tar.gz](https://github.com/ValveSoftware/Proton/files/2340263/steam-350080.tar.gz)

My Specs: https://gist.github.com/sputniktr02/3f410eb3d6206ab7bd35b70c6a1bb12c

**Comment by kisak-valve** [comment] 2018-08-31 12:50
Hello @sputniktr02, do the games work for you with Proton 3.7-3?

**Comment by MrCraigen** [comment] 2018-08-31 13:25
@kisak-valve I can confirm that RAGE works with 3.7-3, but not with 3.7-5

**Comment by sputniktr02** [comment] 2018-08-31 13:37
@kisak-valve Yes, games were working with 3.7-3 and 3.7-4 beta out of the box, however when i try to change the resolution in game settings i was getting black screen. I mentioned it in the whitelist request back then.

**Comment by sputniktr02** [comment] 2018-08-31 13:52
@kisak-valve Hi, i have added the log files to the original post.

**Comment by Kira-PH** [comment] 2018-08-31 21:59
DOOM and RAGE "died" on me with black screen issues. Deleting the compatdata folder for each game appears to have solved it, except now RAGE complains bitterly about not having enough memory and - just before I came back here - lost all its textures.

**Comment by Kira-PH** [comment] 2018-08-31 22:01
@kisak-valve I think you can probably merge #1089 here

**Comment by kisak-valve** [comment] 2018-08-31 22:04
DOOM (2016) Everything's gone dark... (379720)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/1089.
@HughPH posted on 2018-08-31T19:10:05:

So DOOM was running very nicely. I had a quick look to see if anything [interesting] had changed in the newest Steam Client Beta update (which I'd already been running) and found that there is now listed Proton 3.7-5 Beta. Hurrah!

So I tried to run RAGE. Just got a black screen - and sound. And sounds when I press keys. Had to close it, that caused the machine to become unresponsive - except the mouse, and there was disk activity. Shut it down gracelessly. Rebooted. Ran RAGE again. Black screen. Same again. Ctrl+Alt+F2, killall Rage.exe. That worked. Loaded DOOM again, and everything looked good until I got to the actual game...

https://imgur.com/a/ir2fzDM

Now I'll try a reboot - but it could be a big problem (for reproducing issues at the very least) if the previous game can affect the stability of the current game...
***
@HughPH commented on 2018-08-31T19:22:02

Comes back to life after a reboot.
***
@HughPH commented on 2018-08-31T19:59:41

Dead again after trying some other games (Fallout: New Vegas, Fallout 3, Schein, Mafia 3) and checking if the Black Mesa team had fixed the bug that keeps crashing my game out (they haven't) - weird since Black Mesa worked.

Next I'll try rebooting, running DOOM, exiting DOOM and running DOOM again. It would be strange if it was directly affected by another game, especially after running Black Mesa which works fine.
***
@HughPH commented on 2018-08-31T20:19:03

After rebooting DOOM is still dark (as per image) - so now unsure of how/why this is occurring. I cannot reproduce DOOM being OK after a reboot. (DOOM seems forever not OK now!)
***
@HughPH commented on 2018-08-31T20:28:59

Works OK after deleting compatdata folder. In hindsight I should have backed up my save files... Steam hasn't redownloaded them (yet, if it will at all)
***
@TwoD commented on 2018-08-31T21:51:17

Set `+r_renderapi 1` as the launch option and keep restarting it until it works.
Sometimes when it's launching to a black screen there's an error reporting dialog popping up which I have to kill to make the game quit. (How you do that depends on your window manager but usually you can do something like right/middle clicking the X to close it, or do it from a context menu while holding down Alt, or just kill the process via a terminal.)
If it keeps failing, restart Steam and try either with native libraries or the steam runtime. Eventually it'll start properly. Done it several times and finished the campaign just 10 minutes ago.
***
@HughPH commented on 2018-08-31T22:00:22

Thanks @TwoD

**Comment by sputniktr02** [comment] 2018-09-08 10:39
@kisak-valve Hi, just here to report that latest Proton beta (3.7-6) fixed black screen issues for me. Thanks.

**Comment by kisak-valve** [comment] 2018-09-08 14:03
@MrCraigen, @HughPH, does Proton 3.7-6 fix this for you two as well?

**Comment by Kira-PH** [comment] 2018-09-08 17:41
@kisak-valve Yes, seems to, but DOOM started up in 640x480! It was easy enough to change, though.

**Comment by MrCraigen** [comment] 2018-09-12 21:21
@kisak-valve RAGE work now as it should be on 3.7-6 Beta build

**Comment by kisak-valve** [comment] 2018-09-12 23:22
Thanks for retesting, closing.

**Closed as completed by kisak-valve** 2018-09-12 23:22 UTC
Labels: Regression

**Comment by pantas123** [comment] 2018-09-16 15:01
Hm, same problem with Anno 1404 (blank screen but sound and cursor), worked great in 3.7.3 , no chance with proton 3.7.6 and the beta...
Dont know where to start . Is there a way to go back to 3.7.3 (cause steam autoupdated mine). 
Also i deleted the compatcache folder without luck.

EDIT: managed it by editing engine.ini in the prefix folder and change directx to 9

**Comment by kisak-valve** [comment] 2018-09-16 16:35
Hello @pantas123, the investigation of the specific issue that was tracked here has been concluded and your issue is mentioned at #641.
