### ISSUE TITLE
Two Worlds II HD (7520)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1179] opened 2018-09-02 14:44 UTC
An error occurred while launching Two Worlds II "(missing executable) : /steam/steamapps/common/Two Worlds II/TwoWorlds2_DX10.exe."
The game runs as if a native game (completely stable) if I create a clean wineprefix and install Steam and run the the DirectX 9 version. I compared the clean install directory against my Steamplay directory and discovered that the relevant game exe's aren't copied into the main "Two Worlds II" folder in the steamplay version.

**Comment by ghost** [comment] 2018-09-19 18:50
Retested the above. Performed a clean download and install. The '/mnt/data/games/steam/steamapps/common/Two Worlds II' folder appears to be correctly populated with the relevant exe.

However the prefix directory is not being created at all refer '/mnt/data/games/steam/steamapps/compatdata' directory.

On my steam page it does not show the the game can be played via 'Steamplay' notification.

Could there be some issue due to the fact that this game has a native MAC version?

**Comment by ghost** [comment] 2018-10-26 22:26
Steam identifies this game as having a native build and therefore does not allow the game to be played via Proton. I do not have the "Runs on this computer via Steam Play" notification next to the game

To resolve this I suggest that the game is set to not have a native linux build.

**Comment by kisak-valve** [comment] 2018-10-26 22:40
Hello @JSJoubert, for the time being I'm going to close this issue report as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5638. If the situation is changed for this game, give me a ping and we can re-evaluate.

**Closed as completed by kisak-valve** 2018-10-26 22:40 UTC
Labels: Game compatibility - Unofficial
