### ISSUE TITLE
Zwei: The Arges Adventure (427680)

### ISSUE THREAD

**Issue by ipr** [ValveSoftware/Proton#5653] opened 2022-03-06 14:59 UTC
# Compatibility Report
- Name of the game with compatibility issues:Zwei: The Arges Adventure 
- Steam AppID of the game:427680

## System Information
- GPU: AMD Vega 56/64
- Driver/LLVM version: Mesa 21.3.5
- Kernel version: 5.16.12
- Proton version:7.0

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

## Symptoms 
When starting game opens a pop-up saying Indeo codec could not be found.

Actual game seems to work fine.

## Reproduction
1. start game
2. notice the pop-up before main menu

[steam-427680.log](https://github.com/ValveSoftware/Proton/files/8192816/steam-427680.log)

**Comment by kisak-valve** [comment] 2022-03-06 15:06
Closing as a duplicate of #5652.

**Closed as completed by kisak-valve** 2022-03-06 15:06 UTC

**Comment by ipr** [comment] 2022-03-06 15:16
> Closing as a duplicate of #5652.

Thanks. I thought github didn't save the issue at first but looks like it just took long for some reason..
