### ISSUE TITLE
need to unset WINEARCH

### ISSUE THREAD

**Issue by sandsmark** [ValveSoftware/Proton#70] opened 2018-08-22 10:17 UTC
if the user has set e. g. WINEARCH=win32, proton_run will fail to start («wine: WINEARCH set to win32 but '[...]/.local/share/Steam/steamapps/compatdata/221380/pfx' is a 64-bit installation.»

just running «unset WINEARCH» before launching steam seems to work, but proton should probably either support win32 or unset WINEARCH before attempting to launch.

**Comment by E100Beta** [comment] 2018-08-22 10:51
I would hope they'll support creating win32 prefix, some games may need that. I was never able to get Sonic Adventure 2 running in win64 prefix, and this seems to continue with Proton.

**Comment by cjwijtmans** [comment] 2018-08-22 11:10
or wine should just fix that.

**Comment by jwhite66** [comment] 2018-08-22 11:56
Duplicate of https://github.com/ValveSoftware/Proton/issues/8

**Closed as completed by jwhite66** 2018-08-22 11:56 UTC
