### ISSUE TITLE
Life is Strange: Before the Storm - Crash

### ISSUE THREAD

**Issue by Xeers** [ValveSoftware/Proton#830] opened 2018-08-28 14:39 UTC
Arch Linux
Nvidia Geforce 950 GTX
AMD FX

Pastebin:
https://paste.drhack.net/?f57a54d0ac442495#ZXIeakX5YnpS4gaT1EZhFANZDPjU0lKaAZ0OsyBkmZI=

========== OUTPUTING STACK TRACE ==================

RtlLookupFunctionEntry returned NULL function. Aborting stack walk.
<Missing stacktrace information>

========== END OF STACKTRACE ===========

**** Crash! ****
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
Game removed: AppID 554620 "", ProcID 7809 
No cached sticky mapping in ActivateActionSet.JS method call WebChat.GetOverlayChatBrowserInfo with 1 arguments
pid 7815 != 7812, skipping destruction (fork without exec?)

**Comment by Zero86Sk** [comment] 2018-08-28 14:48
did you try running the game with `PROTON_USE_WINED3D11=1 %command%` ?

**Comment by Xeers** [comment] 2018-08-28 14:56
Thank you very much. This seems to work

**Comment by kisak-valve** [comment] 2018-08-28 14:57
Closing as a duplicate of #75.

**Closed as completed by kisak-valve** 2018-08-28 14:57 UTC

**Comment by thermalthrottle** [comment] 2018-08-30 17:57
It doesn't work for me, running Mint 19
