### ISSUE TITLE
Proton Experimental currently requires rdtscp CPU support

### ISSUE THREAD

**Issue by bear-bulloff** [ValveSoftware/Proton#5199] opened 2021-10-05 07:56 UTC
# Compatibility Report
- Name of the game with compatibility issues: Mudrunner, syberia 2, Robin Hood Sherwood Builders demo
- Steam AppID of the game: 675010, 46510, 1774170.

## System Information
- GPU: RX 560
- Kernel version: 5.14
- Proton version: Proton experimental-6.3-20211004

Games with Proton experimental-6.3-20211004 won't run, tested with Mudrunner, syberia 2, Robin Hood Sherwood Builders demo. With version 6.3-7 everything works.

[steam-46510.log](https://github.com/ValveSoftware/Proton/files/7283850/steam-46510.log)
[steam-675010.log](https://github.com/ValveSoftware/Proton/files/7283853/steam-675010.log)
[steam-1774170.log](https://github.com/ValveSoftware/Proton/files/7283857/steam-1774170.log)
![Screenshot_~ : bash_1](https://user-images.githubusercontent.com/59369672/135982809-3e545f64-9a0a-4b5f-bb53-4f11b3b74b32.png)

**Comment by kisak-valve** [comment] 2021-10-05 13:10
Hello @bear-bulloff, between the logs, `err:ole:start_rpcss Failed to open service manager` looks like line of interest.

**Comment by bear-bulloff** [comment] 2021-10-05 16:56
> Hello @bear-bulloff, between the logs, `err:ole:start_rpcss Failed to open service manager` looks like line of interest.

With proton 6.3-7 Robin Hood Sherwood Builders Demo no such problems. here is the log
[steam-1774170.log](https://github.com/ValveSoftware/Proton/files/7287704/steam-1774170.log)
.

**Comment by ivyl** [comment] 2021-10-05 18:03
Looks like your CPU doesn't support `rdtscp` instruction and wineboot.exe crashes:

```
Unhandled exception: illegal instruction in 64-bit code (0x0000000140002b89).
```

This is only available in experimental and needs to be fixed. Thanks for the report!

**Comment by alasky17** [comment] 2021-10-07 17:49
@bear-bulloff I've uploaded a build here that should fix this failure: https://www.codeweavers.com/xfer/alasky/proton-test/
with the lock code "cpu".  Could you give it a try and see if the games now run on your machine with the CPU in question?

Edited with easier instructions: 
You can test this build by:
1) Creating a compatibilitytools folder here if it doesn't already exist:  ~/.steam/steam/compatibilitytool.d
2) Drop the tarball into compatiblitytool.d
3) Untar
4) Reboot steam
5) Now this version will show up as a Proton version to choose from in the dropdown menu
6) To remove later, just delete the folder in compatibilitytools.d and reboot Steam again

**Comment by bear-bulloff** [comment] 2021-10-08 17:14
> Replying to https://github.com/ValveSoftware/Proton/issues/5199#issuecomment-938019962

With this version of Proton all the tested games run. Thank you.
[steam-1774170.log](https://github.com/ValveSoftware/Proton/files/7313154/steam-1774170.log)
[steam-675010.log](https://github.com/ValveSoftware/Proton/files/7313155/steam-675010.log)
[steam-46510.log](https://github.com/ValveSoftware/Proton/files/7313157/steam-46510.log)

**Comment by alasky17** [comment] 2021-10-08 20:44
@bear-bulloff Thank you so much for testing :)  The fix should be in the next experimental release.

**Comment by bear-bulloff** [comment] 2021-10-09 15:46
Thank you. We'll be waiting.
Tried to run Battlefield 2042 beta with this version of Proton, a message appears about using an older version of windows 10.
![Screenshot_Please update Windows_1](https://user-images.githubusercontent.com/59369672/136665242-ee369edc-73da-474c-9816-ba6661edbc9d.png)
[steam-1638720.log](https://github.com/ValveSoftware/Proton/files/7315937/steam-1638720.log)

**Comment by kisak-valve** [comment] 2021-10-09 15:59
Hello @bear-bulloff, that issue is unrelated to the issue reported here. Please use #5200 for feedback on using Battefield 2042 Open Beta with Proton.

**Comment by bear-bulloff** [comment] 2021-10-09 21:17
Hello. Okay. I just wanted to add for this particular version of Proton before it was released.

**Comment by alasky17** [comment] 2021-10-11 21:51
@bear-bulloff The fix for older CPUs was included in the recent proton release - experimental-6.3-20211011b.  I'm going to go ahead and close this issue since you already tested the fix; please comment if the problem isn't solved and I can reopen this.

**Closed as completed by alasky17** 2021-10-11 21:51 UTC
