### ISSUE TITLE
3.16 Beta breaks where 3.7-8 works

### ISSUE THREAD

**Issue by jwatte** [ValveSoftware/Proton#2374] opened 2019-03-02 18:40 UTC
# Compatibility Report
Forged Battalion
Supreme Commander 2

## System Information
- GPU: NVIDIA GTX 1080 Ti
- Driver/LLVM version: NVIDIA-Linux-x86_64-415.27.run
- Kernel version: 4.15.0-45-generic
- Proton version: 3.16-4, 3.16-7 Beta

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Games that start with 3.7.x do not start with 3.16.x
The problem is likely related to `run-detectors: unable to find an interpreter for /opt/steam/steamapps/common/ForgedBattalion/ClientLauncherG.exe`

## Reproduction

[2019-03-02 10:31:45] Checking for update on startup
[2019-03-02 10:31:45] Checking for available updates...
[2019-03-02 10:31:45] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-03-02 10:31:45] Download skipped: /client/steam_client_ubuntu12 version 1550534751, installed version 1550534751
[2019-03-02 10:31:45] Nothing to do
[2019-03-02 10:31:45] Verifying installation...
[2019-03-02 10:31:45] Performing checksum verification of executable files
[2019-03-02 10:31:46] Verification complete
installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""

Thread 6 "CIPCServer::Thr" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0xeccffb40 (LWP 17838)]
0xf2ace552 in AssertMsgImplementation () from /home/jwatte/.local/share/Steam/ubuntu12_32/libtier0_s.so
(gdb) c
Continuing.
installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""

Thread 6 "CIPCServer::Thr" received signal SIGTRAP, Trace/breakpoint trap.
0xf2ace552 in AssertMsgImplementation () from /home/jwatte/.local/share/Steam/ubuntu12_32/libtier0_s.so
(gdb) c
Continuing.
run-detectors: unable to find an interpreter for /home/jwatte/.local/share/Steam/legacycompat/iscriptevaluator.exe
installscript_posix.cpp (418) : Assertion Failed: Standalone evaluator returned error code for app 686260
installscript_posix.cpp (418) : Assertion Failed: Standalone evaluator returned error code for app 686260

Thread 6 "CIPCServer::Thr" received signal SIGTRAP, Trace/breakpoint trap.
0xf2ace552 in AssertMsgImplementation () from /home/jwatte/.local/share/Steam/ubuntu12_32/libtier0_s.so
(gdb) c
Continuing.
GameAction [AppID 686260, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
run-detectors: unable to find an interpreter for /home/jwatte/.local/share/Steam/legacycompat/iscriptevaluator.exe
GameAction [AppID 686260, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 686260, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 686260, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 686260, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask for AppId 686260: 0
Game update: AppID 686260 "", ProcID 18156, IP 0.0.0.0:0
ERROR: ld.so: object '/home/jwatte/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jwatte/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jwatte/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
run-detectors: unable to find an interpreter for /opt/steam/steamapps/common/ForgedBattalion/ClientLauncherG.exe

**Comment by kisak-valve** [comment] 2019-03-02 18:46
Hello @jwatte, how are you selecting the version of Proton to use? Please go to Steam -> Library dropdown -> Tools and install Proton 3.16 (beta) if it is not already. (https://github.com/ValveSoftware/steam-for-linux/issues/6045)

**Comment by ghost** [comment] 2019-03-02 20:13
In addition, Supreme Commander 2 is shown to work with 3.16.x just fine https://www.protondb.com/app/40100

**Comment by jwatte** [comment] 2019-03-04 19:10
Update: It seemed 3.17 was available to select on my machine, but wasn't actually (correctly?) installed.
When I installed a new Windows game from the library, that somehow forced the Steam client to correctly install Proton 3.17, and now all the games I mentioned, work.

So, the bug is "somehow, after an update, Steam client showed (and defaulted to) version 3.17, ,even though it wasn't actually properly installed. Installing some other Windows game causes this version to be properly installed."

**Comment by kisak-valve** [comment] 2019-03-04 19:22
Thanks for retesting @jwatte, closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/6045.

**Closed as completed by kisak-valve** 2019-03-04 19:22 UTC
