### ISSUE TITLE
[Whitelist] Flatout 2 (2990)

### ISSUE THREAD

**Issue by jammm** [ValveSoftware/Proton#109] opened 2018-08-22 14:42 UTC
Ubuntu 18.04 with Nvidia driver 396.51 (GTX 1080)

**Comment by thunder1410** [comment] 2018-08-22 17:53
Can also confirm with AMD RX 580, mesa 18.3.0 driver on ubuntu 18.04.1. Works perfectly

**Comment by Houtworm** [comment] 2018-08-25 11:02
It also works great here, Arch Linux, Nvidia 396.54

**Comment by AsciiWolf** [comment] 2018-08-25 12:08
Fedora 28, Mesa 18.0.5, AMD RX 580.

Both FlatOut and FlatOut 2 work out-of-box without any issues.

By the way, the official Linux port of FlatOut 2 from GOG is also using Wine.

**Comment by alvarlagerlof** [comment] 2018-09-02 21:20
Does not work for me.  #1192

**Comment by kisak-valve** [comment] 2018-09-02 21:35
FlatOut 2 only UI works.

Issue transferred from https://github.com/ValveSoftware/Proton/issues/1192.
@alvarlagerlof posted on 2018-09-02T21:18:00:

The UI, sound and everything like that works, but when i load a map i see only sun flares. No game. It is running, because I can drive the car and hear it crashing into stuff. But I see nothing. I have tried on both 3.7-5-beta and 3.7-3. Neither works. Is this Proton or the game? Can i fix it somehow?

[Here it seems to work](https://proton.city/game.html?id=2990)
[Steam system infromation](https://gist.github.com/alvarlagerlof/c711341605a4e13b2b888ca1799d5525)

![Looks like this](https://user-images.githubusercontent.com/14835120/44960817-5bd2b400-af06-11e8-8c02-9cc3650afa59.png)

**Comment by thunder1410** [comment] 2018-09-02 21:57
@alvarlagerlof do you have any issues with other games under proton? The game is dx9 so it couldn't be a DXVK problem.

**Comment by alvarlagerlof** [comment] 2018-09-02 22:50
@thunder1410 No. Have played Stick Fight, Scribblenauts, Quake Champions and a free drifting game. All work very well.

**Comment by thunder1410** [comment] 2018-09-03 19:48
@alvarlagerlof verify game cache? It works for me and most people. Tried running using wine (steam)? Can you provide any logs?

**Comment by alvarlagerlof** [comment] 2018-09-03 20:56
@thunder1410 Did that, in steam right? Under properties. Did not help? Any launch parameters that could work?

**Comment by thunder1410** [comment] 2018-09-04 11:06
@alvarlagerlof Can you try running it with wine, for example through lutris?
First install lutris. Then just click install steam version here https://lutris.net/games/flatout-2/

**Comment by alvarlagerlof** [comment] 2018-09-04 12:37
@thunder1410 Will try, but lutris is not as nice at all. I want everything
in Steam optimally.

Den tis 4 sep. 2018 13:06thunder1410 <notifications@github.com> skrev:

**Comment by DoubyCz** [comment] 2018-09-27 20:08
I can confirm it works out of the box without any issue.

// Ubuntu 18.04LTS, GeForce GTX 680 - 4.6.0 NVIDIA 390.48, kernel 4.15.0-33-generic, proton 3.7-6, [full system specs](https://gist.github.com/DoubyCz/ddfa8a99e121fc3213206aa2db8a1ff3) //

**Comment by AsciiWolf** [comment] 2018-10-06 13:32
Also works out-of-box on my ThinkPad T480 with Intel GPU on Fedora 28, Mesa 18.0.5.

**Comment by kisak-valve** [comment] 2018-11-13 23:32
Found in the 2018-11-13 white list update.

**Closed as completed by kisak-valve** 2018-11-13 23:32 UTC
Labels: Whitelist Request

**Comment by ghost** [comment] 2019-01-13 17:34
On Solus Budgie with Nvidia GTX 860M everything works out of box, except for LAN multiplayer. Does anybody else experience problems with this? Tried Steam and GOG versions with Windows computers, both creating and joining games, can't see existing games and other can't see my games. Didn't try with other Linux computers.

**Comment by kisak-valve** [comment] 2019-01-13 18:20
Hello @vladimir-malky, please open a new issue report.
