### ISSUE TITLE
None of my games will start on fresh Ubuntu install with recommended drivers, official or not.

### ISSUE THREAD

**Issue by tyisafk** [ValveSoftware/Proton#302] opened 2018-08-23 17:05 UTC
This is on a fresh Ubuntu 18.04.1 LTS install, only changes were kernel and MESA drivers, both provided by this github.  Error log from trying to run an officially supported game provided, but crashes happen on every game, regardless of D3D11 (Neir) or OGL/Vulkan (DOOM).  This worked on Manjaro Linux with no problems under the same configuration.

What I did was install the OS, install the GPU drivers from the repository provided, download a few games.

- DOOM 2016 (Officially supported)
- Neir Automata (Officially supported)
- Monster Hunter: World (Unofficially supported)
- Beat Saber (Officially supported)
- Final Fantasy XIV Stormblood (Unofficially supported)

When I try to run any Windows title, the game immediately closes right away as soon as the preparing window goes away, games with Steam Cloud support sync as soon as I try to load the game so I know the process itself gets killed.

---

Specs and drivers

---

- Kernel: 4.18.0 SteamVR, 4.18.4 Mainline didn't work either.
- Custom kernel parameters via GRUB: radeon.modeset=0 amdgpu.modeset=1 amdgpu.dc=1 amdgpu.cik_support=1 amdgpu.dpm=1
- CPU: Ryzen 1700 8c16t
- GPU: AMD R9 390X 8GB
- RAM: 16GB DDR4 at 3200Mhz
- Storage: SSD mounted at / and HDD mounted at /home
- MESA Drivers: 18.3, provided from the PPA on this github.

Log below.  If there's any other log I need to upload, let me know.  Thanks!

[error.log](https://github.com/ValveSoftware/Proton/files/2315454/error.log)

**Comment by Oschowa** [comment] 2018-08-23 17:13
You need to install python2.7

**Comment by tyisafk** [comment] 2018-08-23 17:19
That did it. Thanks!

**Comment by kisak-valve** [comment] 2018-08-23 18:09
Closing as a duplicate of #15.

**Closed as completed by kisak-valve** 2018-08-23 18:09 UTC
