### ISSUE TITLE
No internet access on applications using Proton Experimental

### ISSUE THREAD

**Issue by Toren-T** [ValveSoftware/Proton#4999] opened 2021-07-23 17:26 UTC
# Compatibility Report
- Name of the game with compatibility issues: Warframe
- Steam AppID of the game: 230410

## System Information
- GPU: AMD AMD Radeon (TM) RX 480 Graphics 
- Driver/LLVM version: 4.6 (Compatibility Profile) Mesa 21.3.0-devel (git-211d1dfd34)
- Kernel version: 5.13.4-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/):https://gist.github.com/Toren-T/e2a281aff17fb5c545ee7bf5ac1abd42
- Proton version: 1626706042 experimental-6.3-20210719

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

[steam-230410.log](https://github.com/ValveSoftware/Proton/files/6870209/steam-230410.log)
Note: This is one of the smaller logs I got due to the app crashing immediately without an internet connection.

## Symptoms 
Any program I run using the Proton Experimental build lacks a internet connection. All other versions of Proton I have used have had internet access. 

This issue persists regardless of network drivers. I have tested using systemd-networkd with systemd-resolved and NetworkManager with systemd-resolved, openresolv and dnsmasq.

**Comment by kisak-valve** [comment] 2021-07-23 17:32
Hello @Toren-T, besides Warframe, what other games have you seen this behavior with?

**Comment by Toren-T** [comment] 2021-07-23 17:37
So far I have tested Warframe(from the log) and Forza Horizon 4.

**Comment by Toren-T** [comment] 2021-07-23 18:02
With a bit more testing Risk of Rain 2 I can see multiplayer servers, The Binding of Isaac: Rebirth Daily leader boards work, and TrackMania2 Stadium I can see multiplayer servers.

**Comment by kisak-valve** [comment] 2021-07-23 18:10
Thanks @Toren-T, since the issue isn't an unconditional failure, I think it would be better to evaluate this feedback on a per-game basis, and we're using one issue per unofficially supported game title. I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/167#issuecomment-885811626. Feel free to also add a note to #4667 for Forza Horizon 4.

**Closed as completed by kisak-valve** 2021-07-23 18:10 UTC
