### ISSUE TITLE
Monster Hunter: World (Missing Codecs?)

### ISSUE THREAD

**Issue by WalterLuigi** [ValveSoftware/Proton#1680] opened 2018-10-03 01:13 UTC
# Compatibility Report
- Monster Hunter: World
- Steam AppID of the game:

## System Information
- GPU: GTX 1070
- Driver/LLVM version: nvidia 396.54
- Kernel version: 4.14.71-1 LTS
- Proton version: 3.7-7 Beta

## I confirm:
- [ x ] that I haven't found an existing compatibility report for this game.
- [ x ] that I have checked whether there are updates for my system available.

[steam-582010.log](https://github.com/ValveSoftware/Proton/files/2440220/steam-582010.log)

## Symptoms 

Game crashes after final boss. Thread on issue can be found here.
https://www.reddit.com/r/MonsterHunter/comments/99cqi4/xeno_save_corruption_bug_does_not_exist_proof/

## Reproduction

Just beat the final boss. It will happen.
I assume proton is missing the codecs listed here, as installing these is the fix on Windows.

https://www.microsoft.com/en-us/software-download/mediafeaturepack
https://www.microsoft.com/en-us/p/web-media-extensions/9n5tdp8vcmhs?activetab=pivot%3Aoverviewtab

**Comment by shadywack** [comment] 2018-10-03 03:14
This is a known issue, and as soon as Kisak sees it, it'll get merged into the existing issue https://github.com/ValveSoftware/Proton/issues/175

**Comment by kisak-valve** [comment] 2018-10-03 13:17
Hello @NullOtoko, we're using one issue report per unofficially supported game title and this has been mentioned several times in #175. I'm going to point to https://github.com/ValveSoftware/Proton/issues/175#issuecomment-424128257 as the direct match.

Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/175#issuecomment-424128257.

**Closed as completed by kisak-valve** 2018-10-03 13:17 UTC
