### ISSUE TITLE
Proton doesn't run games on NTFS partitions?

### ISSUE THREAD

**Issue by andrebadaia** [ValveSoftware/Proton#311] opened 2018-08-23 18:50 UTC
I tried to run Tropico 4 installed on a NTFS partition (my Steam folder on Windows) via Steam but the game didn't start. Other games in the same partition also didn't work. When I put the Tropico 4 on my EXT4 partition, the game worked perfectly. The type of partition is a issue? I'm asking this because I usually run Windows Games via Wine, and most of them run perfectly. 

Thanks!

**Comment by tfaller** [comment] 2018-08-23 18:53
This is already known. Please take a look at issue #104

**Comment by andrebadaia** [comment] 2018-08-23 18:55
Thanks for the information!

**Comment by kisak-valve** [comment] 2018-08-23 18:55
Closing as a duplicate of #104.

**Closed as completed by kisak-valve** 2018-08-23 18:55 UTC
