### ISSUE TITLE
Disable desktop compositor when launching proton games

### ISSUE THREAD

**Issue by jolty1** [ValveSoftware/Proton#1765] opened 2018-10-17 11:32 UTC
# Feature Request

## I confirm:
- [X] that I haven't found another request for this feature.
- [X] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

Have Proton games on launch disable desktop compositing / 3D desktop effects. Could improve performance in games.

Some games running native on Linux games already do this TF2, CS:GO, Dirt Rally, Euro Truck Sim 2.

## References [optional] 

Starting Big Picture Mode mode disables my compositor, launching games through it is a work around.
Could just be an issue with Vulkan and certain window managers. I use KWin.
The tested games above use OpenGL. Not Vulkan.

**Comment by doitsujin** [comment] 2018-10-17 11:38
Proton 3.16 should already do this if you launch a game in fullscreen mode (but not in windowed mode).

**Comment by jolty1** [comment] 2018-10-17 12:53
Can confirm proton is already doing what was requested. And can be closed.

Its an issue with KDEs Plasma Panel breaking when Alt tabbing out of Vulkan/proton games.

I've found behaviour is diffent between APIs.

Alt-tabbing out of fullscreen Proton games re-enables composition making the panel freeze, the until the game is closed or game is back in focus.

Alt-tabbing out of fullscreen OpenGL games will still keep composition disabled.

Info may be usefull to those on KDE.

**Comment by kisak-valve** [comment] 2018-10-17 12:54
Closing as a duplicate of https://github.com/ValveSoftware/wine/pull/23.

**Closed as completed by kisak-valve** 2018-10-17 12:54 UTC

**Comment by kakra** [comment] 2019-04-26 14:51
I believe It's a bug in KWin: In a multi-monitor setup you can see the panel freezing (and displaying some old state) as soon as the game launches. It will stay that way until the game ends no matter if you tab in/out or enter/leave fullscreen. It seem KWin draws the panel just once before the compositor starts and then leaves it that way forever until you log out.

**Comment by ghost** [comment] 2021-04-13 02:56
> I believe It's a bug in KWin: In a multi-monitor setup you can see the panel freezing (and displaying some old state) as soon as the game launches. It will stay that way until the game ends no matter if you tab in/out or enter/leave fullscreen. It seem KWin draws the panel just once before the compositor starts and then leaves it that way forever until you log out.

Same problem.

**Comment by kakra** [comment] 2021-04-13 03:24
But should be fixed since some time now in KDE, at least I didn't experience this again, at least since Plasma 5.21, maybe even 5.20.
