### ISSUE TITLE
[Feature Suggestion] Embed Protontricks within Steam for Linux so you can easily install the required game dependencies right from the game Properties.

### ISSUE THREAD

**Issue by setsunati** [ValveSoftware/Proton#2285] opened 2019-01-30 19:47 UTC
Protontricks is a wrapper for Winetricks that makes it very easy to install game dependencies into the Proton prefix and configure.

https://github.com/Matoking/protontricks

Protontricks button in game Properties will be awesome so you can just click the button which will launch the Protontricks GUI (which opens Winetricks GUI pre-configured for Steam games) and you can easily install required game dependencies.

Visual representation: https://i.imgur.com/vCPnJl5.png

Clicking the Protontricks button will automatically grab Steam game ID and launch this command:
Example:
protontricks 377160 --gui

And then you simply install game dependencies and configure what you need straight in Winetricks GUI pre-configured for Steam games.

**Comment by kisak-valve** [comment] 2019-01-30 20:17
Hello @setsunati, this is a feature request for Steam, not Proton itself, and is effectively a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5687. Also possibly a duplicate of #1714.

Closing in favor of the existing issue reports.

**Closed as completed by kisak-valve** 2019-01-30 20:17 UTC
