### ISSUE TITLE
Nier Automata disappears from screen after  the companies' logos on Cinnamon (524220)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#1135] opened 2018-09-01 17:03 UTC
Hello,
I have a weird bug, after the yohra loading screen(after paltinum games’s logo), the game dissappears, BUT i can still interact with it. I got the game through Steam Family, but I was able to play Monster hunter World and Dark Souls II: Scholar Of The First Sin from the same shared library on steam play without any issue. Here’s my spec: 
-OS: Antergos with Cinnamon as a desktop enviroment
-Driver: As a graphic driver I run vulkan-radeon(the mesa driver for vulkan as it is described) from AUR, it works since I’m able to play various games on it, like DOOM and MH: World
-CPU: i5-8400
-GPU: RX 480 8gb
-RAM: 16 GB

EDIT: After testing I found out that this is a Cinnamon only related problem, on every other desktop enviroment on Antergos the games runs fine, but with major performance drops

**Comment by N00byKing** [comment] 2018-09-23 15:30
This Issue ain't limited to Cinnamon, I have it too on Arch Linux with the Deepin Desktop Environment,
GPU is Vega 56, Driver mesa-git 18.3.0 built using llvm8

**Comment by N00byKing** [comment] 2018-09-28 17:09
Tested using 3.7-7, Issue still present

**Comment by N00byKing** [comment] 2018-09-29 13:15
Found a Solution:
Unchecking "Enable Window Effect" in deepin allows the Game to run normally.
There is probably a similar switch on Cinnamon, but I don't use it so I wouldn't know where it is

This is probably a WM issue

**Comment by N00byKing** [comment] 2018-10-13 17:28
Issue fixed with Proton 3.16-1 Beta

**Comment by libgradev** [comment] 2019-01-04 10:03
Ubuntu 18.10 (Gnome) / Proton 3.16-6

Had to run winecfg on the prefix and disable: Graphics->Allow the window manager to control the windows

Disabling the window animations/effects alone wasn't enough - it still vanished pre-menu requiring an alt-tab. Runs fine now :)

**Comment by kisak-valve** [comment] 2021-09-01 16:08
Hello, please retest this game with Proton 6.3-6 and see if any regressions have crept in since this issue was last evaluated.

**Closed as completed** 2021-10-01 16:48 UTC
Labels: Whitelist Update Request
