### ISSUE TITLE
No windows games launch

### ISSUE THREAD

**Issue by anthonyorm** [ValveSoftware/Proton#2341] opened 2019-02-16 19:04 UTC
OS - Kubuntu 18.04 LTS

I recently installed Kubuntu, previously from WIndows 7. All of my steam games are on a separate drive. Every windows game I try starts running for a few seconds then closes. Here is the log from attempting to launch fallout 4, every other windows game I tried has this similar log: https://pastebin.com/nGbApPHQ

**Comment by kisak-valve** [comment] 2019-02-16 19:08
Hello @anthonyorm, what filesystem(s) are you using with the steam library?

**Comment by anthonyorm** [comment] 2019-02-16 19:11
fuseblk(ntfs)

**Comment by kisak-valve** [comment] 2019-02-16 19:18
NTFS is known to have issues with Proton, noted at #11, #104, and [various other issue reports.](https://github.com/ValveSoftware/Proton/search?q=ntfs&type=Issues) Use a linux native filesystem, or you try some of the workarounds mentioned in the various issue reports.

There's also some things you can try at https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows.

Closing as a duplicate of #11.

**Closed as completed by kisak-valve** 2019-02-16 19:18 UTC
