### ISSUE TITLE
Grim Dawn - wine: Unimplemented function mscoree.dll.CorIsLatestSvc

### ISSUE THREAD

**Issue by scottc** [ValveSoftware/Proton#84] opened 2018-08-22 12:33 UTC
Proton 3.7
Archlinux

Grim dawn crashes on load with black window.

Std:io:

```
wine: Call from 0x7b43c45c to unimplemented function mscoree.dll.CorIsLatestSvc, aborting
wine: Unimplemented function mscoree.dll.CorIsLatestSvc called at address 0x760023:0x7b43c45c (thread 0017), starting debugger...
```

Also see: #18

Grim dawn runs with good compatibility in vanilla wine with /d3d9 mode, or in dxvk with /d3d11 mode.

**Comment by jarrard** [comment] 2018-08-22 12:37
I think mscoree.dll can be disabled under winecfg, maybe proton needs to consider doing the same.

**Comment by scottc** [comment] 2018-08-22 13:02
I tried playing around with winecfg and setting mscoree override to disabled:

`WINEARCH=win64 WINEPREFIX="/home/__myuser__/.local/share/Steam/steamapps/common/Proton 3.7/dist/share/default_pfx" winecfg`

But got same result, I hope that was the correct wine-prefix. I guess i could try provide my own mscoree.dll and set it as override. But probably not that helpful for the initial publicbeta Proton 3.7 release.

**Comment by aeikum** [comment] 2018-08-22 13:41
Dupe of #18.

**Closed as completed by aeikum** 2018-08-22 13:41 UTC
