### ISSUE TITLE
Disk Overhead Management

### ISSUE THREAD

**Issue by foodabc123** [ValveSoftware/Proton#5348] opened 2021-11-26 23:50 UTC
# Feature Request

## I confirm:
- [yes] that I haven't found another request for this feature.
- [yes] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
Instead of a new WINE directory for each game that makes use of Proton, an idea I'm in favor of is a unified directory for Proton, where one main directory is used and if libraries overlap, or well known incompatibilities have been listed, then an overflow directory would be created, where any game that doesn't fit, goes into the new overflow directory.

## Justification [optional] 
Whilst WINE makes use of one WINE directory by default, Steam automatically creates a Proton directory for each game, creating disk overhead when an unused directory isn't deleted, and could potentially save on space by grouping games in less directories, Steam Deck could possibly lose valuable storage for those unaware.
## Risks [optional]
Potentially unstable experience for any unaccounted incompatibilities.

**Comment by kisak-valve** [comment] 2021-11-27 00:23
Hello @foodabc123, this feature request is already being tracked at #2691. Closing as a duplicate of  #2691 / #4093 / #604 / #4764.

**Closed as completed by kisak-valve** 2021-11-27 00:23 UTC
