### ISSUE TITLE
Counter Strike 2 and proton

### ISSUE THREAD

**Issue by pavlokozlenko** [ValveSoftware/Proton#8291] opened 2024-12-05 23:55 UTC
# Feature Request
Why didn't Valve add VAC anti-cheat support to proton? I tested it and the game goes perfectly through proton, but why did the developers annoy the players so much? If they can't make a normal port of the game, then why not give you the opportunity to play through proton?

[Game: ](https://steamdb.info/app/730/)
System info https://pastebin.com/Qu3QJ911
## I confirm:
- [ ] that I haven't found another request for this feature.
- [ Yes] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 
VAC support to proton

**Comment by kisak-valve** [comment] 2024-12-06 00:03
Hello again @pavlokozlenko, we're using one issue report per unofficially supported game title with Proton, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-2521761177.

Closing as a duplicate of #3225.

**Closed as not planned by kisak-valve** 2024-12-06 00:03 UTC

**Comment by pavlokozlenko** [comment] 2024-12-06 00:07
> Hello again @pavlokozlenko, we're using one issue report per unofficially supported game title with Proton, so I've gone ahead and transferred this issue report to [#2704 (comment)](https://github.com/ValveSoftware/Proton/issues/2704#issuecomment-2521761177).
> 
> Closing as a duplicate of #3225.

Thanks! One quest. I wonder why developers continue to ignore this after so many years?
