### ISSUE TITLE
Install non-steam game?

### ISSUE THREAD

**Issue by smurfhunter** [ValveSoftware/Proton#122] opened 2018-08-22 16:43 UTC
Could one install a game/program inside steam using steam play?

**Comment by OvermindDL1** [comment] 2018-08-22 16:58
Should probably post that at https://github.com/ValveSoftware/steam-for-linux/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc as it is related to the Steam Client.  :-)

**Comment by gd71** [comment] 2018-08-24 11:42
No yet tested but seems ok
https://www.reddit.com/r/Steam/comments/99fjzw/steam_proton_for_non_steam_applications/

**Comment by ghost** [comment] 2018-08-29 03:46
Would really like to be able to use Proton with non-Steam games. I can add a shortcut to an EXE to my Steam but it will still launch using system native wine and not Proton.

**Comment by r4-broadcast** [comment] 2018-09-04 10:45
I tried 2 Non-Steam games:

Warcraft 3 & Frozen Throne: Run without issues, only Videos got an error. For running them I'm using:

> 
`STEAM_COMPAT_DATA_PATH=~/.proton/ ~/.steam/steam/steamapps/common/Proton\ 3.7/proton run whatever.exe`

Also, using the same Commands, I tried 5 Adobe CC 2018 Apps:

Photoshop Ran but without the correct fonts on interface.
Illustrator, Media Encoder, Premiere Pro and After Effects threw errors on libraries, specially MS.VC90

Read out:

> `https://www.reddit.com/r/linux_gaming/comments/9au2qp/how_do_i_use_proton_via_command_line/`

**Comment by WaKeMaTTa** [comment] 2018-09-06 17:56
I tried to run [Mod Organizer](https://www.nexusmods.com/skyrim/mods/1334/) and i had to install this package:

```
sudo apt-get install libfreetype6:i386
```

This is the command i used:

```
PROTON_NO_ESYNC=1 PROTON_DUMP_DEBUG_COMMANDS=1 STEAM_COMPAT_DATA_PATH=~/.steam/steam/steamapps/compatdata/203630/ "~/.steam/steam/steamapps/common/Proton 3.7/proton" run "~/.steam/steam/steamapps/common/ModOrganizer/ModOrganizer.exe"
```


:heavy_check_mark: Tested in Ubuntu 18.04 LTS (64bits)

**Comment by Bulbyzarr** [comment] 2018-09-21 15:42
I have  no file named "Proton" in "~/.steam/steam/steamapps/common/Proton 3.7/" :/

**Comment by torzod** [comment] 2018-09-29 16:00
this is required for continuing the game [OneShot](https://store.steampowered.com/app/420530/OneShot/) (`_______.exe`)

**Comment by gwemmie** [comment] 2018-10-18 00:18
Does Proton do anything under the hood that would benefit a non-Steam game that vanilla WINE doesn't do besides use DXVK? Would using wine with DXVK on DX10-12 games be effectively the same thing as twisting Proton to cover non-Steam games? (Honest question.)

I guess an easier way to answer this question is, does Valve add anything to WINE besides DXVK in making Proton, and do they contribute their improvements back to WINE itself as is GNU practice?

Just skimming the source a little, it seems to me like besides DXVK, all Proton adds to WINE is various specific versions and builds of individual libraries that are tailored to maximize compatibility with the games Proton directly supports. If that's true, that would mean using Proton on a non-Steam game is potentially *less* helpful than using just WINE with DXVK on it. But I only skimmed, so take this entire paragraph with a massive grain of salt.

EDIT: Researching further, I just learned another big thing besides DXVK that's added is esync: https://github.com/zfigura/wine/blob/esync/README.esync

**Comment by justinvdk** [comment] 2018-12-28 23:35
For me the benefit is making sure that the executable I add would run in the same environment as any other program launched from steam.

More specifically to my situation: I've installed Steam via Flatpak and have no multilib/multiarch on my system, which means I am unable to run 32 bit binaries. Flatpak solves this internally and Steam runs perfectly, even Windows games via Proton. However, manually running a non-steam game in that environment is a pain (couldn't even get it to work).

Allowing running non-steam games via proton would solve this, and probably any other situation in which Steam installed in a tricky environment (I understand that mine is not very common; but similarity other setups might benefit).

I hope that in the future Steam would allow us some advanced control over what proton does with wine prefixes and such for these kind of edge-cases. Some games split multiplayer and singleplayer in two different binaries and Steam only has a single entry for both, with the Singleplayer game having a menu option to launch the Multiplayer binary. This doesn't work for me in proton with Splinter Cell: Chaos Theory unfortunately. I was hoping to just directly add the Multiplayer exe as non-steam game to work-around this.

**Comment by kisak-valve** [comment] 2019-01-19 15:52
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5677. Also implemented in the [2019-01-18](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108833155107) Steam client beta update.

**Closed as completed by kisak-valve** 2019-01-19 15:52 UTC

**Comment by f0rmatme** [comment] 2019-01-19 23:51
thanks based mr valve, love the steam client beta update

**Comment by melroy89** [comment] 2019-02-23 02:55
Thank Valve! Love you guys.
