### ISSUE TITLE
[Feature Request] Allow other Wine builds and advanced configuration options to be used directly

### ISSUE THREAD

**Issue by XaeroVincent** [ValveSoftware/Proton#313] opened 2018-08-23 19:10 UTC
It looks like Proton uses an older Wine 3.7 build--I would like to use Wine Staging 3.14 and newer builds. It would be nice to have a mechanism like PlayOnLinux and Lutris to use custom Wine and Wine Staging builds, along with the ability to make fine tune configuration edits via Wine registry, Winecfg, and Winetricks. Basically wanting an "advanced configuration" menu that gives the flexibility that PlayOnLinux and Lutris do to make per-game tweaks.

**Comment by kisak-valve** [comment] 2018-08-23 19:19
Closing as a duplicate of #22 and #24.

**Closed as completed by kisak-valve** 2018-08-23 19:19 UTC
