### ISSUE TITLE
Just Cause 3

### ISSUE THREAD

**Issue by sTiKyt** [ValveSoftware/Proton#6497] opened 2023-01-31 19:36 UTC
# Compatibility Report
- Name of the game with compatibility issues:  Just Cause 3
- Steam AppID of the game: 225540

## System Information
- GPU: Nvidia GeForce RTX 3060
- Driver/LLVM version: Nvidia 525.85.05 (Proprietary) (But issue doesn't go away if I use nvidia-open instead)
- Kernel version: 6.1.8-arch1-1
- Link to full system information report as [Gist](https://gist.github.com/): [Full System Information](https://gist.github.com/sTiKyt/55e240b4505157e7fa0958f2acca45e0)
- Proton version: Proton Experimental (But issue exists on all of them)
- 
[steam-225540.log](https://github.com/ValveSoftware/Proton/files/10529441/steam-225540.log)

## Symptoms 
Shows splash screen when I press "Play" button, then crashes

## Reproduction
Just run the game

## I confirm:
- [x] that I haven't found an existing compatibility report for this game. 
- [x] that I have checked whether there are updates for my system available.

I did find existing issue #682, but it seems to be ignored, so I'm posting this as new issue just in case

**Comment by kisak-valve** [comment] 2023-01-31 19:42
Hello @sTiKyt, we're using one issue report per unofficially supported game title. Please do not intentionally open duplicate issue reports.

Closing as a duplicate of #682.

**Closed as not planned by kisak-valve** 2023-01-31 19:42 UTC

**Comment by sTiKyt** [comment] 2023-01-31 19:50
> Hello @sTiKyt, we're using one issue report per unofficially supported game title. Please do not intentionally open duplicate issue reports.
> 
> Closing as a duplicate of #682.

Okay, sorry, just felt like report wasn't noticed
