### ISSUE TITLE
#Compability Report

### ISSUE THREAD

**Issue by Xeneomorph** [ValveSoftware/Proton#2196] opened 2019-01-05 16:59 UTC
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by HonkingGoose** [comment] 2019-01-05 18:31
Hi @Xeneomorph, welcome to Github, and welcome to the Proton issue tracker! :smile: 

I think something went wrong when you were making your issue report, because your report contains no data about any game or issue.

Before you edit your issue, please search the Proton issue tracker, to ensure you aren't posting a new report for a unofficially supported game. (We only use 1 report for each unofficially supported game).

I recommend searching by the game's appid number. For example: if I want to find the Appid for Factorio, I go to https://steamdb.info/search/?a=app&q=factorio and enter Factorio. I can see that Factorio has the app id number **427520**. If i wanted to search for Factorio on the Proton issue tracker I would enter **427520** and look what comes up.

You can edit your issue and fill in the needed data. Log into your Github account and go to this issue report. Then click on the icon with the three dots: ... and select: "Edit".

You can also edit the title of your issue report, I recommend a format like:
Name of game (steam appid number).

Also I recommend reading trough my feature request, that contains helpful advice for newcomers to this Proton issue tracker: #1664

Especially relevant is this:
1. One issue per unofficially supported game.
1. Title of issue for a unofficially supported game should contain: <br>official name of game from steam store + (appid number) 
1. Separate issues for each bug for officially supported/whitelisted games.
1. Title of issue for a officially supported game should contain: <br>official name of game from steam store + short description of issue + (appid number)
1. Demo's have their own bug-report, and own app-id.
1. If things break after a Proton update (regression) we will need confirmation of the known good and bad unmodified Proton versions, so that we can be sure that a fluke or system issue is not causing the regression.

I hope this advice helps you on your way to contributing towards Proton by filing reports.

Good luck,

HonkingGoose

**Comment by kisak-valve** [comment] 2019-01-05 19:22
Closing as invalid.

**Closed as completed by kisak-valve** 2019-01-05 19:22 UTC
