### ISSUE TITLE
Resident Evil 2 (2019)

### ISSUE THREAD

**Issue by GoreTechGit** [ValveSoftware/Proton#6954] opened 2023-07-22 21:37 UTC
# Compatibility Report
- Name of the game with compatibility issues: Resident Evil 2 (2019)
- Steam AppID of the game: 883710

## System Information
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
- Video driver version: 4.6.0 NVIDIA 535.54.03
- RAM: 16 GB DDR4 2133 MHz
- Storage: 1 TB SSD (44.5 GBs available)
- Kernel version: 5.15.0-76-generic
- OS: Linux Mint 21.0 & 21.2
- Link to full system information report as [Gist](https://gist.github.com/GoreTechGit/e3b8c8097823cb3e36d5e98425dec3df):
- Proton version: 5.13, 6.3, 7, 8, Experimental, GE 5.21, GE 8.6 (I know GE is beyond the scope of official Proton. I just wanted to point out that I've tried them)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game regarding this issue.
- [X] that I have checked whether there are updates for my system available.
- [X] that I've reinstalled the game
- [X] that I've restarted my PC
- [X] that I've verified the game cache after launch and after PC restart
- [X] that I've tried both the main branch (DX12 with raytracing) and the dx11_non-rt beta branch
- [X] that I've turned off the Steam overlay, Theatre VR and Steam Cloud
- [X] that I've added the following launch options: `VKD3D_CONFIG=dxr11 PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 PROTON_LOG=1 %command%`
- [X] that I've added the following launch options (without the ones above): PROTON_USE_WINED3D11=1 %command%
- [x] that I've launched re2.exe with regular wine in the terminal (it exited 2 seconds later. No popup, no messages)
- [X] that I've kept it in a "launching" state for an hour to see if it was just being slow

PROTON_LOG outputs nothing

## Symptoms 
Whenever I start the game, it stays in a "launching" state indefinitely. It doesn't open anything, it's just "launching" forever. I came to the conclusion that Proton's install script was the issue:
![Install Script Hanging](https://github.com/ValveSoftware/Proton/assets/96606070/25008a47-3c7c-44b6-b6e1-919680525187)
(Don't mind the fact that there's GE in the command line. The official Proton did the same thing. All of them)
![DXSETUP hanging](https://github.com/ValveSoftware/Proton/assets/96606070/ed121bd5-a86e-4bd2-9b2b-745c9095f050)

Both DXSETUP.exe and the Python script for installing DirectX libraries are hanging forever. To bring more proof that they're the source of the problem, I also found out that whenever I verify the game cache shortly after I launched it, it hangs at the "resetting the install script" step. Plus, exiting Steam also started hanging (AKA the applet on the bottom right doesn't disappear) since he was presumably trying to close or reset the install script as well.

I tried running DXSETUP.exe with wine, except without the /silent option, and it instantly showed me the installation wizard, so the exe itself seems to be working fine. I haven't tried running the Python script though, but I've already wasted way too many hours trying to launch this one game.

## Reproduction
Just launch the game. The install script will be hanging indefinitely until I restart my computer.

**Comment by kisak-valve** [comment] 2023-07-22 21:54
Hello @GoreTechGit, we're using one issue report per unofficially supported game title, and usually I'd transfer this issue report to #6672, but this set of symptoms you've described is some kind of video driver issue being tracked at #6859.

Closing as a duplicate of #6859.

**Closed as not planned by kisak-valve** 2023-07-22 21:54 UTC
