### ISSUE TITLE
Impossible to set 144Hz screen refreshrate

### ISSUE THREAD

**Issue by furioness** [ValveSoftware/Proton#1623] opened 2018-09-27 19:34 UTC
As title says. Only 60Hz in any game and any resolution when under normal wine 3.0.3 games see system resolutions@Hz list.
Ubuntu 16.04, RX 460 with Ubuntu 'default' driver.
Same for Ubuntu 18.04

**Comment by ghost** [comment] 2018-09-28 06:43
Same issue on other distros

**Comment by viggy96** [comment] 2018-09-29 21:15
Can confirm this on multiple games. When running games with Proton, only 60Hz is available.
With mainline wine or wine-staging, multiple refresh rate options are available. I have a 75Hz ultrawide, but on games running via Proton, I can only set them to 60Hz. On games running via wine, wine-staging, or wine-esync, I can properly set the refresh rate of the game to 75Hz. 

Ubuntu 18.04.1 LTS, Mesa 18.3 git Padoka, Kernel 4.18.11. R9 Fury

**Comment by minisori** [comment] 2018-10-01 09:14
I can confirm the issue with latests nvidia driver too.

Debian stretch, kernel 4.17.17-1~bpo9+1, GTX 1080ti

**Comment by Snuggle** [comment] 2018-10-08 17:16
This is likely a known bug with GNOME's mutter compositor. There's an (apparently) working merge request but nothing has been done yet.

https://gitlab.gnome.org/GNOME/mutter/merge_requests/171

**Comment by viggy96** [comment] 2018-10-08 20:29
@Snuggle But I when I run games with esync-wine, wine-staging, or vanilla wine, on Lutris, I the games properly detect the refresh rates available, and I can set the refresh rate to 75Hz, appropriate for my monitor. I'm running the default GNOME desktop on Ubuntu 18.04.

**Comment by Snuggle** [comment] 2018-10-10 17:12
Hm. Darn, I can't find a small Windows game that would even run at 120hz to test, I'll take your word for it then. Does Steam Proton run games with a virtual Wine desktop or something? Something must be different to cause this behaviour.

**Comment by furioness** [comment] 2018-10-10 18:58
@Snuggle try any afps like Reflex Arena or Quake Live

**Comment by viggy96** [comment] 2018-10-10 21:26
@Snuggle I've been using World of Tanks via Lutris, and that's where I see that vanilla wine, and esync, and staging properly detect monitor refresh rate.

**Comment by jonnyteronni** [comment] 2018-10-23 10:55
I can confirm this in Frostpunk

**Comment by Aimela** [comment] 2018-10-24 15:44
This seems to vary per game. In Subnautica, everything is fine, but in The Witness, The Witcher 3, and DOOM(2016) are all limited to 60fps once v-sync is turned on. I haven't tried many other games.

My relevant specs: 
Arch Linux
KDE Plasma
i7-6700k
GTX 1080(driver 410.57).

**Comment by xpander69** [comment] 2018-10-30 05:56
Same issue here with many games. With proton every game seems to report just 2560x1440@60hz, while wine-staging has no issues reporting 2560x1440@144hz. This is really bad for games where there is no vsync toggle or ways to turn it off, those games just lock to 60fps instead of 144 :(
Osiris: New Dawn is one of those
MATE desktop 1.20, nvidia drivers 396.54.09

maybe there are some workarounds that can be used until this gets solved?

**Comment by ghost** [comment] 2018-11-21 15:28
For me GTA V was set to 60hz but wine forced 144hz i could see it because gta v was locked with vsync to 144 fps

**Comment by john5788** [comment] 2018-12-28 09:37
I am noticing this issue in HITMAN 2. With a 144hz monitor, Vsync in HITMAN 2 locks FPS to 60 rather than 144.

**Comment by davidbepo** [comment] 2018-12-28 11:01
this also happens in warframe no 72hz option, just 60

**Comment by furioness** [comment] 2018-12-28 15:10
Seems like it happens everywhere, any exception?
Btw, on Xubuntu with disabled compositor same, so it's not just Gnome Mutter.

**Comment by hardware** [comment] 2019-02-10 11:11
> I am noticing this issue in HITMAN 2. With a 144hz monitor, Vsync in HITMAN 2 locks FPS to 60 rather than 144.

For me, Vsync in HITMAN 2 locks framerate to 144fps but game run in 60Hz mode with my 144hz monitor. I choose 1080p144hz in nvidia-settings panel, but no effect.

Driver : 415.27
GPU : RTX2080
Proton 3.7-8
OS: Archlinux

Other than that the game runs very well.

**EDIT :** 

Solution for KDE (Plasma) :

Disable Kwin with `ALT+SHIFT+F12`

**Comment by urbenlegend** [comment] 2019-02-20 11:29
I believe this is due to Proton's fullscreen patch that allows resolution changes for fullscreen games without changing desktop resolution. It's doing some funky screen emulation and my guess is that it mistakenly passes only 60Hz down to the game.

Currently I am running [wine-tkg](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git) on Arch. It's basically a wine build script that allows you to add a bunch of custom patches, including Proton's patches to wine. During compile time, I have the option of disabling or enabling the Proton fullscreen patch. When I have it enabled, games think I only have a 60Hz monitor. When I disable the patch, games are able to properly see 144Hz and other refresh rates.

For some games this doesn't matter, but there are quite a few games that use the refresh rate value as a frame limiter when vsync or adaptive resolution is on (i. e. Dishonored 2). This should be fixed so we can unlock the full performance of our games.

**Comment by xpander69** [comment] 2019-02-20 11:33
@urbenlegend yeah confirming this is the proton fs patch thingy that does that. I forgot to report this earlier.

**Comment by ghost** [comment] 2019-03-24 08:06
I don't have high refresh rate monitor myself, but this sounds like it needs fixing and with a bit of luck, it might not be that hard. Anybody checked the code yet?

**Comment by BloodyIron** [comment] 2019-04-01 23:56
Yeah I'm seeing multiple games that won't let me go above 60hz, when my panel, and DE, are set to 120hz.

Ubuntu 18.10 + GTX 960.

**Comment by Tk-Glitch** [comment] 2019-04-04 14:58
Yeah it'll always report 60 no matter what but will use desktop refresh rate. However, yes, some games might use that value to set a fixed framelimiter. I guess I've been lucky not to encounter one yet.

**Comment by ghost** [comment] 2019-04-04 15:45
Same for me

**Comment by aubreymatic** [comment] 2019-05-10 20:17
Just confirming that when I run my local install of wine staging on Blood: Fresh Supply for example, it can detect the correct refresh rate of 144hz but proton doesn't.

**Comment by Reonu** [comment] 2019-06-23 14:37
I'm having the same issue on Manjaro. Games run at 60 Hz only despite me having a 144 Hz monitor.

**Comment by ghost** [comment] 2019-06-28 06:35
I am also on Manjaro and all games are 60 Hz. Any fixes?

**Comment by aeikum** [comment] 2019-07-31 18:27
You should be able to play games at your monitor's current framerate in Proton 4.11-1. Please retest.

**Comment by davidbepo** [comment] 2019-07-31 20:37
tried warframe and i can indeed confirm that changing framerate works

**Comment by Reonu** [comment] 2019-08-02 00:24
The correct refresh rate is now reported to Risk of Rain 2 (144 Hz appears in the graphics options) but the framerate is still capped to 60 FPS for some reason (not the case on Windows)

**Comment by aeikum** [comment] 2019-08-02 14:13
@Leon422 According to the Steam overlay FPS monitor, ROR2 seems to be working for me. Note that enabling vsync may cause the framerate to lock to some whole number fraction of the whole framerate (e.g. 72 or 96 FPS) if it can't keep up with the full 144Hz. Do you have vsync enabled in-game, or any odd GPU configurations (e.g. in nvidia-settings, or mesa environment variables, or something like that)?

**Comment by Reonu** [comment] 2019-08-02 15:10
> 
> 
> @Leon422 According to the Steam overlay FPS monitor, ROR2 seems to be working for me. Note that enabling vsync may cause the framerate to lock to some whole number fraction of the whole framerate (e.g. 72 or 96 FPS) if it can't keep up with the full 144Hz. Do you have vsync enabled in-game, or any odd GPU configurations (e.g. in nvidia-settings, or mesa environment variables, or something like that)?

I have Vsync disabled and nope, just the Nvidia propietary drivers installed, no special settings at all. GTX 1070.

**Comment by xpander69** [comment] 2019-08-02 15:12
@Leon422 might be your Desktop Environments compositor is blocking? try without compositor running if you can

**Comment by kisak-valve** [comment] 2019-09-06 13:19
Closing as fixed in Proton 4.11-1. The followup issue with Risk of Rain 2 should be discussed on its compatibility report.

**Closed as completed by kisak-valve** 2019-09-06 13:19 UTC
