### ISSUE TITLE
Proton 5.0-4: Failed to initialize OpenVR

### ISSUE THREAD

**Issue by farmboy0** [ValveSoftware/Proton#3652] opened 2020-03-19 21:26 UTC
Running VR games with Proton 5.0-4 results in the games only rendering on desktop as DXVK cant initialize OpenVR. Reverting to 5.0-3 or 4.11-13 does fix this problem.
I am running Steam and SteamVR from the beta branch.

**Comment by kisak-valve** [comment] 2020-03-19 21:30
Hello @farmboy0, please give some examples of games you tested. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

Additionally, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by farmboy0** [comment] 2020-03-19 21:51
Games Ive tried:
Apex Construct Demo
Budget Cuts
Cosmic Trip
Superhot VR

Here are the logs from Budget Cuts:
[Budget Cuts_d3d11.log](https://github.com/ValveSoftware/Proton/files/4357075/Budget.Cuts_d3d11.log)
[steam-400940.log](https://github.com/ValveSoftware/Proton/files/4357077/steam-400940.log)

**Comment by farmboy0** [comment] 2020-03-19 21:55
System Info:
https://gist.github.com/farmboy0/16f79f8c08e6062bb1cf5365963499ce#file-steam-system-information

**Comment by rstrube** [comment] 2020-03-20 04:41
I can confirm the same issue.  Since upgrading to Proton 5.0-4 I can no longer start certain VR games that worked on earlier versions of Proton (5.0-3 and below).

This includes ~~both Superhot VR and~~ No Man's Sky which worked very well with previous versions of Proton.

_Edit: after deleting my WINEPREFIX for Superhot VR it started working fine.  NMS does have issues, but i'm not sure if it's related to Open VR initialization, or it's something else entirely._

**Comment by aeikum** [comment] 2020-03-20 11:30
Thanks for reporting. Can you upload a log with `+steam,+vrclient` added to WINEDEBUG? Let me know if you'd like more instructions than that.

**Comment by farmboy0** [comment] 2020-03-20 14:39
Log of Budget Cuts with +steam,+vrclient:; [steam-400940.log](https://github.com/ValveSoftware/Proton/files/4360162/steam-400940.log)

**Comment by aeikum** [comment] 2020-03-20 14:47
@farmboy0 Thanks! According to the log, your vrclient paths file is empty:

    16512.972:0008:0009:trace:steam:convert_linux_vrpaths openvr vrpaths is empty

So something's gone wrong here. This normally lives at `$HOME/.config/openvr/openvrpaths.vrpath`. Can you check if that file exists and is indeed empty? If not, can you post its contents here?

**Comment by farmboy0** [comment] 2020-03-20 15:09
Its not empty:
```
{
	"config" : 
	[
		"/mnt/daten/Home/steamvr/config",
		"/mnt/daten/Home/.steam/steam/config",
		"/mnt/daten/Home/.local/share/Steam/config"
	],
	"external_drivers" : null,
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"/mnt/daten/Home/steamvr/logs",
		"/mnt/daten/Home/.steam/steam/logs",
		"/mnt/daten/Home/.local/share/Steam/logs"
	],
	"runtime" : 
	[
		"/mnt/daten/SteamLibrary/Linux/steamapps/common/SteamVR",
		"/mnt/daten/Home/.local/share/Steam/steamapps/common/SteamVR"
	],
	"version" : 1
}
```

**Comment by rstrube** [comment] 2020-03-20 23:58
**NMS:**
No Man's Sky only displays on my monitor and not in the HMD.  Here is the log file.
[steam-275850.log](https://github.com/ValveSoftware/Proton/files/4362131/steam-275850.log)

I don't see the same error message as you pointed out, so perhaps it's a different issue??!

**Superhot:**
Superhot *is* actually running fine for me after deleting my WINEPREFIX, I'm not able to upload the logfile because it's too large!

Here is my openvr.paths file for reference:

```
cat ~/.config/openvr/openvrpaths.vrpath
{
	"config" : 
	[
		"/home/robert/.local/share/Steam/config"
	],
	"external_drivers" : null,
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"/home/robert/.local/share/Steam/logs"
	],
	"runtime" : 
	[
		"/home/robert/.local/share/Steam/steamapps/common/SteamVR"
	],
	"version" : 1
}
```

**Comment by kisak-valve** [comment] 2020-03-21 00:02
Hello @rstrube, friendly reminder that Proton logs compress well. If Github isn't happy with the size of a log, consider throwing it in an archive.

**Comment by rstrube** [comment] 2020-03-21 01:32
Well that was quick.  Proton 5.0-5 fixed my issue with NMS and VR.  Let me know if you'd like another log file.

**Comment by farmboy0** [comment] 2020-03-21 21:08
With 5.0-5 this issue is not resolved.

**Comment by aeikum** [comment] 2020-03-23 14:34
@farmboy0 Do you have the `XDG_CONFIG_HOME` environment variable set? I think I see a bug in our handling of that case. I've uploaded a fix you can try out if you're comfortable doing that.

Grab `steam.exe.so` from here:

https://www.codeweavers.com/xfer/aeikum/misc/
Unlock key: `misc`

And drop it into your `Proton 5.0/dist/lib/wine/` directory, overwriting the file that is already there. Then see if VR is fixed for you.

**Comment by farmboy0** [comment] 2020-03-23 19:04
Yes, i have XDG_CONFIG_HOME set and yes this fixes this issue.

**Comment by radriaanse** [comment] 2020-03-25 02:03
Can confirm that this indeed fixes the issue and I also have that var set in my environment.

**Comment by aeikum** [comment] 2020-03-25 12:27
Thanks for trying it out. The fix will be included in the next release.

**Comment by aeikum** [comment] 2020-04-15 21:59
Hi all. Proton 5.0-6 was just released and contains the fix for VR when XDG_CONFIG_HOME is set. Can you retest to confirm it's working again?

**Comment by farmboy0** [comment] 2020-04-17 19:17
It still works, this can be closed.

**Comment by kisak-valve** [comment] 2020-04-17 19:18
Thanks for retesting, closing.

**Closed as completed by kisak-valve** 2020-04-17 19:18 UTC
