### ISSUE TITLE
Elite Dangerous now working in wine, Proton specific crash (359320)

### ISSUE THREAD

**Issue by fls2018** [ValveSoftware/Proton#1800] opened 2018-10-22 00:27 UTC
Hello for some reason I posted in the previous compatibility report thread for this game but it got deleted. If a moderator could move this there as this is progress, game is now working under wine as of yesterday but proton has it's own issue in addition to connection errors that have been worked around.

# Compatibility Report
- Name of the game with compatibility issues: Elite Dangerous
- Steam AppID of the game: 359320

## System Information
- GPU: GTX 1070
- Driver/LLVM version: Nvidia 396.54.09
- Kernel version: 4.18
- Proton version: 3.16-3

[steam-359320.log](https://github.com/ValveSoftware/Proton/files/2499789/steam-359320.log)

## Symptoms 

Game now works in Wine staging 3.18 with DXVK using a simple registry fix listed here: https://forums.frontier.co.uk/showthread.php/366894-How-to-install-ED-on-Linux-using-Wine-EXPERIMENTAL-NOT-OFFICIALLY-SUPPORTED?p=7082698&viewfull=1#post7082698

However game still freezes in Proton even after applying the same fixes, the login issue has been resolved but something "**Proton specific**" causes the game to freeze a minute after starting up.

Here's it running under Wine staging: https://youtu.be/JcDY4WFENug

## Reproduction
Similar to the steps in this video: https://youtu.be/jG7TUOXZhng

1/ `winetricks corefonts dotnet40 vcrun2012 quartz` into the 359320 pfx.

2/ `regedit` the 359320 pfx and do the following to match the machineGuid of both keys:

Navigate to HKLM/Software/Microsoft/Cryptography
Copy Value
Navigate to HKLM/Software/Wow6432Node/Microsoft/Cryptography
Paste Value

3/ `winecfg` and set mode to Win7

The above will make the launcher and game start in Steam/Proton and will also fix the authentication error, however game will freeze in about a minute (sometimes sooner). This doesn't happen under Wine staging therefore issue is to do with Proton.

**Comment by ghost** [comment] 2018-10-22 13:30
> 3/ winecfg and set mode to Win7

I suppose 0/ (or 1 if digits increased) would be to winecfg and set to WinXP? Win7 is default so there's no reason to do this unless it was changed previously.

**Comment by ghost** [comment] 2018-10-22 16:30
From the log
```
159005.320:0008:0034:trace:module:LdrUnloadDll (L"rsaenh.dll") - START
159005.320:0008:0034:trace:module:MODULE_DecRefCount (L"rsaenh.dll") ldr.LoadCount: 2
159005.320:0008:0034:trace:module:LdrUnloadDll END
159005.320:0008:0034:fixme:ole:Context_CC_ContextCallback (0x3aadd80/0x3aadd84)->(0x791c8272, 0x30ecc38, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
159005.320:0008:0034:fixme:ole:Context_CC_ContextCallback (0x3aadd80/0x3aadd84)->(0x791c8272, 0x30ecbc4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
159005.320:0008:0034:fixme:ole:Context_CC_ContextCallback (0x3aadd80/0x3aadd84)->(0x791c8272, 0x30ecbc4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
159005.320:0008:0034:trace:seh:raise_exception code=c0000005 flags=0 addr=0x15de5665 ip=15de5665 tid=0034
159005.320:0008:0034:trace:seh:raise_exception  info[0]=00000000
159005.320:0008:0034:trace:seh:raise_exception  info[1]=00000000
159005.320:0008:0034:trace:seh:raise_exception  eax=00000000 ebx=000000d5 ecx=030eca20 edx=1d4d94a0 esi=03eda098 edi=03ab3a1c
159005.320:0008:0034:trace:seh:raise_exception  ebp=030ecae8 esp=030eca80 cs=0023 ds=002b es=002b fs=0063 gs=006b flags=00010206
```
rsaenh.dll is Microsoft Enhanced Cryptographic Provider. Must have to do with the registry change. Not sure why it works differently with Wine VS Proton though.

Wine 3.18 does have two changes however, so not sure if that makes a difference here:
>       rsaenh: Move PKCS1 padding and unpadding functions.
>       rsaenh: Implement RSA OAEP.
https://www.winehq.org/announce/3.18

Would have to see where the exception is going to.

Wonder if the dll provided with Wine would solve it with Proton?

**Comment by kisak-valve** [comment] 2018-10-22 16:54
Hello @fls2018, Github had an [internal issue](https://blog.github.com/2018-10-21-october21-incident-report/) which delayed #150 from getting updated. Your post was not deleted.

Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/150#issuecomment-431715919.

**Closed as completed by kisak-valve** 2018-10-22 16:54 UTC
