### ISSUE TITLE
Steam SDK v1.56 causing crash at start-up with Proton (DX9 game).

### ISSUE THREAD

**Issue by bulldoginteractive** [ValveSoftware/Proton#6719] opened 2023-04-26 05:06 UTC
# Compatibility Report
- Name of the game with compatibility issues: Cue Club 2
- Steam AppID of the game: 366690

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version: Latest

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

## Symptoms 

Feedback on Steam SDK v1.56.

Linux users running our game 'Cue Club 2' under Proton were getting instant crash to desktop when launching. After we rolled back to previous v1.55 SDK it worked fine again for them. The game runs under Windows, DirectX 9.0c

Seems like some compatibility conflict with the latest SDK release? If you can forward to the dev team to explore, it'd be much appreciated. Please let me know if you need any more info.

I had the following reports from users...

"Oh dear, the game won't launch after installing this update. Linux, compatibility on or off. Hit green play button, steam launch dialogue, screen flickers black and then steam blue pause button goes back to green play button. I've turned compatibility off and on, experimental etc."

"The same for me. It was running perfectly yesterday. Tried various proton compatibility too. I click play, the screen goes black for a second, then back to my steam library page."

Seems like it was happening with different versions of Proton?

Not sure if this helps, but this is the second time it's happened. A couple of years ago I had to do a similar rollback for Linux / Proton users due to crash on start-up. Eventually it got resolved with the next SDK.

## Reproduction

Cue Club 2, AppID 366690
https://store.steampowered.com/app/366690/Cue_Club_2_Pool__Snooker/

**Comment by alasky17** [comment] 2023-05-12 13:48
@bulldoginteractive Is this still an issue?  I was unable to reproduce the problem, so maybe it has already been fixed with SDK 1.57?

**Comment by bulldoginteractive** [comment] 2023-05-15 09:24
Have been informed by Steam support that 1.57 fixes it, but we're working on releasing a new game update in a few days, so will include SDK 1.57 and see if the issue is resolved for our Linux / Proton users. Will report back soon. Thanks.

**Comment by kisak-valve** [comment] 2023-07-01 00:05
Closing pending feedback.

**Closed as completed by kisak-valve** 2023-07-01 00:05 UTC
