### ISSUE TITLE
No way run games via proton (on ext4 or ntfs), only natives games works.

### ISSUE THREAD

**Issue by suchencjusz** [ValveSoftware/Proton#5551] opened 2022-02-07 17:28 UTC
Related problem - https://github.com/ValveSoftware/steam-runtime/issues/488

Proton 6.3-8

When I started steam in cli, this shows up:

```chdir /home/suchencjusz/.steam/debian-installation/steamapps/common/SlapshotRebound```

It only appears on non-native games, csgo, prison architect and portal 2 works fine.

System info: https://gist.github.com/suchencjusz/0aebfc40cdfeb5e84cd9397d1fa5084d
Log file of ```.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier```
https://gist.github.com/suchencjusz/88459e63d7aa56059a80bbb31c850af4

VERSIONS.txt are clear

**Comment by kisak-valve** [comment] 2022-02-07 20:15
Hello @suchencjusz, please do not intentionally open duplicate issue reports. Closing as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/488.

**Closed as completed by kisak-valve** 2022-02-07 20:15 UTC
