### ISSUE TITLE
100% Orange Juice (282800): All User/Global Stats being returned as 0

### ISSUE THREAD

**Issue by hdmap** [ValveSoftware/Proton#211] opened 2018-08-23 03:06 UTC
100% Orange Juice itself runs fine, but event info and game stats are failing to load correctly. For example, levels, XP, and games played are being reported as zero. Under normal wine and windows steam client, everything works as expected. Achievements seem to be loaded correctly under both.

With log_ipc enabled, I see GetAchievement and other calls working correctly from the game, but all instances of GetGlobalStat and GetStat return "0, 0x0," and "0, 0," respectively.

I can add more detailed logs/system info if needed.

**Comment by Mushoz** [comment] 2018-08-23 07:24
Very weird. The only major difference between Wine and Proton is the inclusion of Esync patches. Have you tried disabling Esync to see if that fixes the issue?

**Comment by hdmap** [comment] 2018-08-23 13:12
Yes, that has no effect.

**Comment by kisak-valve** [comment] 2018-08-25 21:48
100% Orange Juice (282800): Game is not connecting with Steam.

Issue transferred from https://github.com/ValveSoftware/Proton/issues/490.
@MrThatKid posted on 2018-08-25T06:44:01:

OS: Ubuntu 18.04.1, 64-bit, 4.15.0-23-generic kernel
HW: i7-4770T CPU, GeForce GTX 750 Ti GPU
Driver: NVIDIA 396.54
While the game itself plays fine, it appears that the game does not connect to Steam properly under Proton.
The in-game store (denoted as "Shopping" in the main menu) explicitly says "No Steam Connection"

Further testing in WINE with the Windows Steam client shows that the game needs a Steam connection to allow access to special events, like the (as of this posting) currently ongoing summer event.
In WINE, an option for the summer event would show up in the top right corner of the main menu, however this doesn't happen in Proton.

I do not know what else in the game requires a steam connection. If a connection is needed for user stats, it may explain #211

If you need specific logs from me, let me know what is needed!
***
@arzardk commented on 2018-08-25T07:15:45

I think you should copy this issue in #211 because they keep one thread per one unofficial game.
***
@MrThatKid commented on 2018-08-25T08:15:46

Oh. I wasn't sure how connected these two issues were, and I do see at least one game with more than one thread (Cuphead)
If others think I should post this in the other issue, then I'll do so and close this issue.

**Comment by Plagman** [comment] 2018-09-08 03:23
Can you re-test with the new 3.7-6 Beta?

**Comment by MrThatKid** [comment] 2018-09-09 17:02
Just tested with 3.7-6. It looks promising so far. Events now show up (as of this writing, it's the "All Units Event"), and the in-game store no longer says "No Steam Connection", but instead now shows my level (and it shows as 11 in my case). I haven't tried online yet, and hopefully I'll get time to test that either later today or tomorrow.

**Comment by hdmap** [comment] 2018-09-10 19:48
Yep, stats and online functionality are working correctly with the new beta. I tested online matches, too, and everything seems to be working now. Thanks!

**Comment by kisak-valve** [comment] 2018-09-10 21:15
Thanks for retesting, closing.

**Closed as completed by kisak-valve** 2018-09-10 21:15 UTC
Labels: Game compatibility - Unofficial

**Comment by qunka** [comment] 2020-04-20 15:55
The new game mode, Bounty Hunt, crashes after a few seconds when I try to play it, whether I'm on native or runtime Steam. To reproduce this bug, try to play Bounty Hunt.

Kernel: 5.6.4 x86_64
GPU: GTX 1060
Driver: nvidia 440.82
Proton 5.0-6

https://gist.github.com/qunka/7614100e11da275b6d002d04735030cb

**Comment by kisak-valve** [comment] 2020-04-20 16:03
Hello @qunka, please add your experience to #182. Also, please attach logs as a file or use a [gist](https://gist.github.com).

**Comment by qunka** [comment] 2020-04-20 16:18
> Hello @qunka, please add your experience to #182. Also, please attach logs as a file or use a [gist](https://gist.github.com).

Done and done. Time to reopen, perhaps?
