### ISSUE TITLE
Borderlands 3 (397540)

### ISSUE THREAD

**Issue by ChickenMilk** [ValveSoftware/Proton#8347] opened 2024-12-26 23:58 UTC
# Compatibility Report
- Name of the game with compatibility issues: Borderlands 3
- Steam AppID of the game: 397540

## System Information
- GPU: GTX 1660
- Video driver version: NVIDIA 565.77
- Kernel version: Linux 6.12.6-zen1-1-zen
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ChickenMilk/d376f2a21b28ff5f790e49317a6696c2
- Proton version: Proton Experimental

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

 
[steam-397540.log](https://github.com/user-attachments/files/18256146/steam-397540.log)
(Unable to post dmp file thats created)
## Symptoms 
Launching Borderlands 3 under any proton version causes steam itself to close without the game running.
Attempting to run the game EXE through wine launches the splash screen but then asks to launch via steam and closes. 
Occurs with and without compiling shaders. 

## Reproduction
Fresh install of Borderlands 3, press play and wait for steam to crash

**Comment by kisak-valve** [comment] 2024-12-27 00:04
Hello @ChickenMilk, we're using one issue per game title, and usually I'd transfer this issue report to #3535, however, this is a Steam client issue and should be resolved along with https://github.com/ValveSoftware/steam-for-linux/issues/11592. Opt out of Steam's client beta until the next Steam client beta update cycle.

Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/11592.

**Closed as not planned by kisak-valve** 2024-12-27 00:04 UTC
