### ISSUE TITLE
DOOM 2016 save files keep corrupting (379720)

### ISSUE THREAD

**Issue by Warrengbrn** [ValveSoftware/Proton#881] opened 2018-08-29 03:40 UTC
This happens randomly when I quit and reopen the game then I come back to my save file stating that I'm in dev mode and that my file is corrupted. I can't continue playing my save file after this.

I'm using Proton 3.7-4 Beta.
[System Information](https://gist.github.com/Warrengbrn/6f765f04dd39fb88b7d33388c6765015)

![20180828232635_1](https://user-images.githubusercontent.com/37555856/44763891-2d766280-ab1b-11e8-8ac5-56550708fccf.jpg)

**Comment by Reded100** [comment] 2018-08-30 04:05
+1 Same here, savegame get corrupted every time i close and re-open the game.

![20180829203112_1](https://user-images.githubusercontent.com/42632652/44828874-21e87180-abd7-11e8-97f8-6c63bf1402c1.jpg)

Also tested with Lutris+Wine Staging and windows 7 and the problem is only present on Proton.

EDIT: Problem is on **Steam Clound sync, disable it** for this game to avoid corruption.

**Comment by dbenoy** [comment] 2018-09-15 05:43
This seemed to trigger for me with cloud sync, as well, but it would do it when switching between Windows and Linux. It's possible it might only trigger if you have it installed on both platforms, and perhaps if you have both OSes running at once on separate systems that would cause it to instantly corrupt the moment you exit the game?

**Comment by fredoche** [comment] 2018-09-16 20:46
same here, if I put steam in offline mode (or unplug the cable) the corruption doesnt trigger, whereas it triggers right after steam "syncs" the game.
I played the game on windows 2 years ago, and I have two saves. 
thx

**Comment by Plagman** [comment] 2018-10-05 00:35
This is fixed in the current Steam Client Beta:
https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1691556695813620029

**Closed as completed by Plagman** 2018-10-05 00:35 UTC
Labels: Game compatibility
