### ISSUE TITLE
Fresh Ubuntu install, games fail to launch

### ISSUE THREAD

**Issue by j-macdonald** [ValveSoftware/Proton#4096] opened 2020-07-27 10:29 UTC
I wiped my PC and reinstalled Ubuntu a few days ago. Unfortunately some proton-enabled games are failing to launch. 

#### Your system information

* Steam client version (build number or date): Built Jul 23 2020 at 11:01:27
* Distribution (e.g. Ubuntu): Ubuntu 20.04
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I click "Play" on some games (e.g Elite Dangerous, Homeworld Remastered, Mount & Blade: Bannerlord) and steam says "running" for a few seconds. It fails to launch and the button again reads "play" as though it was never clicked.

I've tried running from the command line, gist here: https://gist.github.com/j-macdonald/5328d96915dfb11b3c09a34afcff99e3

I enabled logging and this is what is produced: https://gist.github.com/j-macdonald/40d2f37de3723cad53a2bcc1fe3c6107

I've tried reinstalling the games themselves, reinstalling steam, switching proton versions, driver updates, no joy.

Weirdly, some proton-enabled games (such as Endless Space 2) work fine and don't have this issue.

#### Steps for reproducing this issue:

At the risk of being glib, "Open steam - click play - repeat".

**Comment by kisak-valve** [comment] 2020-07-27 12:04
Hello @j-macdonald, we're tracking issues with games run with Proton in the Proton issue tracker, so I've transferred this issue report.

In general, issues caused by running games with Proton need to be investigated on a per-game basis.

For the game you've provided a log for, `The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.` is the line of interest, it tells us the launcher was built using WPF, which will be part of wine-mono, but hasn't been integrated yet.

Feel free to search through this issue tracker to for games you're having issues with and add your experience. Elite Dangerous: #150, Homeworld Remastered: #99, Mount & Blade II: Bannerlord: #3706.

Closing in favor of the existing compatibility reports.

**Closed as completed by kisak-valve** 2020-07-27 12:04 UTC

**Comment by pierrep** [comment] 2020-07-30 04:18
Just to add to this discussion, one of the best resources apart from this Github issue tracker is to head to [ProtonDB](https://www.protondb.com/) and search for the game(s) in question. For quite a few games there are some small workarounds or tweaks needed to make the game work optimally. I'm fairly confident that a lot of these issues will be iron out in the future, given the amazing progress we've seen (thanks @kisak-valve  and team)
