### ISSUE TITLE
Typo in wine msi affects msi software installation (like winetricks dotnet40)

### ISSUE THREAD

**Issue by simons-public** [ValveSoftware/Proton#1839] opened 2018-10-28 19:32 UTC
There is a regression in wine that was [identified in the mailing list](https://www.winehq.org/pipermail/wine-cvs/2018-September/130002.html). It prevents the installation of dotnet40 in winetricks, and probably other software that uses msi to install.

The fix has already been committed to upstream wine. I've created a [pull request](https://github.com/ValveSoftware/wine/pull/30) in the [wine repo](https://github.com/ValveSoftware/wine) that should fix this.

**Comment by kisak-valve** [comment] 2018-10-28 19:41
Hello @simons-public, it's pointless to track this both in the pull request and an issue report. Closing as a duplicate of https://github.com/ValveSoftware/wine/pull/30.

**Closed as completed by kisak-valve** 2018-10-28 19:41 UTC
