### ISSUE TITLE
Scaling Issue with Proton 3.16-1

### ISSUE THREAD

**Issue by NeptNutz** [ValveSoftware/Proton#1739] opened 2018-10-14 22:51 UTC
# Compatibility Report
- Name of the game with compatibility issues: Shadow of the Tomb Raider
- Steam AppID of the game: 750920

## System Information
- GPU: GTX 660 SC
- Driver/LLVM version: Nvidia 396.54.09
- Kernel version: 4.15.0-36-generic
- Proton version: 3.16-1 Beta

## I confirm:
- [*] that I haven't found an existing compatibility report for this game.
- [*] that I have checked whether there are updates for my system available.

[steam-750920.log](https://github.com/ValveSoftware/Proton/files/2476929/steam-750920.log)

## Symptoms 
This appears not to be so bad at higher resolutions, but I'm testing at 720p on the lowest-of-the-low settings, including no AA. Whatever type of aliasing, or softening, is present in the display scaling on current Proton (3.7-8 and Beta) goes completely away in 3.16-1 Beta, causing the fonts, etc. to get extremely jagged. There is a definite, visible difference.

**Comment by kisak-valve** [comment] 2018-10-14 22:54
Also mentioned at https://github.com/ValveSoftware/Proton/issues/773#issuecomment-429589983.

**Comment by NeptNutz** [comment] 2018-10-14 23:06
Just cross-tested game on a Dell (A10/RX 560) Windows 10 stock box with similar-sized 1920x1080 monitor. Same "lowest" settings at 720p in DX11 confirm that Proton 3.7 is the correct 'look'.

**Comment by sputniktr02** [comment] 2018-10-15 08:23
I can confirm the issue. I am having the same issue with the games that use DXVK (Witcher 3, The Forest, etc). DirectX 9 games seems to be fine though.

**Comment by dubigrasu** [comment] 2018-10-15 15:38
I also confirm this happening on Dishonored demo. Looks like for 3.16-1 an **nearest** type of filtering is used, while for 3.7 a **linear** one, very visible on text.

3.7 on the left, 3.16 on the right:

![screenshot from 2018-10-15 18-05-04](https://user-images.githubusercontent.com/6303599/46961225-fc40fa00-d0a8-11e8-8fb3-a5c6ed2d7c8f.png)

**Comment by aeikum** [comment] 2018-10-15 15:45
We do request linear scaling when stretching the framebuffer up to the display, see https://github.com/ValveSoftware/wine/blob/proton_3.16/dlls/winevulkan/vulkan.c#L1911 . Nothing changed here between 3.7 and 3.16. @doitsujin, do you have any ideas why this might be happening?

**Comment by aeikum** [comment] 2018-10-15 15:50
Ah, wait, if we're building DXVK as a native linux .so, it's probably bypassing our fullscreen hack code entirely. I bet that's our problem.

**Comment by doitsujin** [comment] 2018-10-15 15:56
This is a DXVK bug. For some reason it is now responsible for doing the scaling by itself, which is okay, but it doesn't handle the case where the window size differs from the Vulkan swap chain size correctly (previously they were always the same). Should be easy to fix though.

**Comment by dubigrasu** [comment] 2018-10-15 16:06
On the same Proton 3.16-1, I replaced the native dxvk libraries with the latest (dll) files from dxvk 0.90 and the scaling issue doesn't happen.

**Comment by aeikum** [comment] 2018-10-15 16:10
@dubigrasu Thanks for testing, that fits with the explanation. We're going to have to back out the native DXVK build anyway due to issues with the Steam Runtime (see #1730) so this should be fixed alongside that.

**Comment by dubigrasu** [comment] 2018-10-15 16:13
I'm sorry for the probably off-topic question, but can't be the steam-runtime just updated to avoid similar conflicts?

**Comment by aeikum** [comment] 2018-10-15 16:19
Yes, but that's a much larger task.

**Comment by doitsujin** [comment] 2018-10-15 16:42
Anyway, doitsujin/dxvk@0d1fa17da289790a5cbe7d8af89f1565964957fc should fix this.

**Comment by kisak-valve** [comment] 2018-10-17 00:51
Hello @NeptNutz, @dubigrasu, please retest with Proton 3.16-2.

**Comment by NeptNutz** [comment] 2018-10-17 01:40
Looks good! Back to normal. [Tested on Nvidia 396.54.09 and 410.66.]

**Comment by dubigrasu** [comment] 2018-10-17 02:00
Yes, all good here.

**Comment by kisak-valve** [comment] 2018-10-17 02:15
Thanks for retesting, closing.

**Closed as completed by kisak-valve** 2018-10-17 02:15 UTC
Labels: Regression, cw
