### ISSUE TITLE
Mouse Problem on Many Unity-Based Games.

### ISSUE THREAD

**Issue by fcmonter** [ValveSoftware/Proton#1424] opened 2018-09-13 02:30 UTC
[steam-444490.log](https://github.com/ValveSoftware/Proton/files/2377484/steam-444490.log)

#Games
- Anything Unity Engine Based;
- Games i'm sure of, The Forest, Polywar

#Specs
- GPU: GTX 1060
- Driver Version 396.54
- Kernel version: 4.15.0-34-generic
- https://gist.github.com/fcmonter/bdd21ee912d7f840eb55b9e14b7ba771
- Proton version: 3.7.6 BETA
- Steam log of game is of Polywar

Whenever I play any unity-based game on any computer on any Linux distro, whenever I would move the mouse up, it would move to the right a little bit. Overall the mouse would just do weird things.

To reproduce this I guess just play a unity game.

Here is a reddit post of some people having the same issue
https://www.reddit.com/r/linux_gaming/comments/9ajw3j/mouse_problems_with_proton/

**Comment by nanonyme** [comment] 2018-09-13 07:10
Duplicate of #1418?

**Comment by fcmonter** [comment] 2018-09-13 11:24
> Duplicate of #1418?

I don't think so.. but i'm not sure.

**Comment by ghost** [comment] 2018-09-13 14:16
Will kisak-valve close it or not? That is the question lol

**Comment by dreamer** [comment] 2018-09-13 14:27
@fcmonter I tested one or two Unity titles and didn't experience this problem (but not the ones you reported). This sounds awful like  #831 (which was fixed in 3.7-6).

**Comment by fcmonter** [comment] 2018-09-13 14:30
> @fcmonter I tested one or two Unity titles and didn't experience this problem (but not the ones you reported). This sounds awful like #831 (which was fixed in 3.7-6).

Well I'm not sure what to do, and the games they tested were not unity-based.

**Comment by dreamer** [comment] 2018-09-13 14:32
Did you try to run Unity games in the native resolution of your display? That was a workaround for 831.

**Comment by Quinnux** [comment] 2018-09-13 14:42
This bug is reported as present in My Summer Car #880 (which is a Unity game) - if you click a mouse button, or move the scroll wheel, your view shifts down-right every time.

Adjusting resolution etc has no effect.

**Comment by fcmonter** [comment] 2018-09-13 20:30
> This bug is reported as present in My Summer Car #880 (which is a Unity game) - if you click a mouse button, or move the scroll wheel, your view shifts down-right every time.
> 
> Adjusting resolution etc has no effect.

You are right, I scrolled and clicked and it moved the camera, but even if i just move my mouse up it does the same thing as scrolling.

**Comment by fcmonter** [comment] 2018-09-13 20:30
> Did you try to run Unity games in the native resolution of your display? That was a workaround for 831.

Yes, I have tried native full screen and various windowed resolutions.

**Comment by gbdlin** [comment] 2018-09-18 13:10
This is definitely a duplicate of https://github.com/ValveSoftware/Proton/issues/1418

**Comment by kisak-valve** [comment] 2018-09-18 13:22
Initial evaluation was unclear if this was a duplicate. Transferred to https://github.com/ValveSoftware/Proton/issues/1418#issuecomment-422390460.

**Closed as completed by kisak-valve** 2018-09-18 13:22 UTC
