### ISSUE TITLE
Stand with Mac！

### ISSUE THREAD

**Issue by LoveJessyChen** [ValveSoftware/Proton#5706] opened 2022-03-20 14:46 UTC
# Whitelist Request
- Name of the game to be whitelisted:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Distro version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [ ] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are remaining issues:

**Comment by dlove67** [comment] 2022-03-20 14:55
First: MacOS *is not linux* it is a BSD.

Second: Apple removed 32-bit support, doesn't have Vulkan support, would rather their own store be supported over Steam, and seems to be moving to ARM. That's a lot of additional workload you're asking devs to take on.

Third: Stop spamming this request everywhere.

**Comment by LoveJessyChen** [comment] 2022-03-20 15:13
You can write a Vulkan for Mac  from Linux.

**Comment by ShalokShalom** [comment] 2022-03-20 15:42
MacOS is kernel wise Mach, not BSD or Linux. 
I recommend you to run Windows or Geruda Linux in dual boot. 
And there is [MoltenVK](https://moltengl.com/moltenvk/) but Valve has no reason to support Mac. 
They do support Linux, since Microsoft was grabbing for their market share. 
That is solved now.

**Comment by dlove67** [comment] 2022-03-20 15:50
Mach is no longer used, it was replaced with XNU (which is sort of a hybrid of mach and a traditional BSD kernel). And while it doesn't use a BSD kernel it is still "A BSD"

The most important thing, though, is that it's not Linux which this user seems to misunderstand, judging by their other posts.

**Comment by kisak-valve** [comment] 2022-03-20 15:57
@LoveJessyChen, please stop opening duplicate issue reports. Closing as a duplicate of #1344.

**Closed by kisak-valve** 2022-03-20 15:57 UTC

**Comment by marinohardin** [comment] 2023-01-26 19:36
> First: MacOS _is not linux_ it is a BSD.
> 
> Second: Apple removed 32-bit support, doesn't have Vulkan support, would rather their own store be supported over Steam, and seems to be moving to ARM. That's a lot of additional workload you're asking devs to take on.
> 
> Third: Stop spamming this request everywhere.

I totally understand being annoyed with this guy's spam, but I just want to add...I don't think most of these are an issue.

> seems to be moving to ARM

Apple's built in Rosetta 2 layer automatically translates x86 to ARM.  Existing WINE implementations wrap a Windows .exe to present as a Mac app and Rosetta 2 automatically translates the binaries.  And Apple's special ARM design has some hardware tweaks to make this more performant.

> Second: Apple removed 32-bit support

CrossOver, a commercial WINE based product, can run a good deal 32- and 64-bit x86 Windows games with near native performance.  It doesn't look like this is an issue when translating x86 to ARM even if Apple doesn't support 32-bit ARM binaries.

> would rather their own store be supported over Steam

I mean, so would Microsoft.  There's nothing on MacOS that causes issues for third party stores.  It's not iOS.

> doesn't have Vulkan support

This is the only real challenge IMHO.  [MoltenVK](https://github.com/KhronosGroup/MoltenVK) exists though which sufficies for a lot of cases.
