### ISSUE TITLE
Strider (235210) no sound / glitch

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#981] opened 2018-08-30 11:44 UTC
Distro: Manjaro XFCE 17.1.12
GPU: GTX 1060, Nvidia proprietary driver 396.54
Resolution: 1920x1080
RAM: 8GB
Proton 3.7-4 Beta

Graphic Glitch and no sound and Xbox Controller work !

**Comment by kisak-valve** [comment] 2018-08-30 12:37
Closing as a duplicate of #603.

**Closed as completed by kisak-valve** 2018-08-30 12:37 UTC
