### ISSUE TITLE
Proton 5.13-1 does not like $TMPDIR longer than 7 chars

### ISSUE THREAD

**Issue by jpalus** [ValveSoftware/Proton#4324] opened 2020-10-27 22:45 UTC
That is a funky one -- after installing Proton 5.13-1 all games stopped working. Out of many many errors in terminal there's this one that turned to be relevant:
```
pressure-vessel-launcher[2086728]: Socket directory path "/home/users/jan/tmp/SteamPVSockets.f3Oo3p/SteamLinuxRuntime.6e7c67e510858036" too long
```
My $TMPDIR, as you might have guessed, is "/home/users/jan/tmp", perhaps not something very common but still completely valid. Not for Proton though. Unsetting TMPDIR resulted in games working again. So I've started experimenting and turns out "/tmp/12" is still good enough while "/tmp/123" is a no go.

I've thought that I'll check how pressure-vessel-launcher looks like and what it does but laughs on me -- I cannot find it anywhere. I would appreciate if someone could guide me to proper location.

**Comment by kisak-valve** [comment] 2020-10-27 22:58
Hello @jpalus, by mere seconds this issue is a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/290. Since your issue report adds some additional info, I've gone ahead and transferred it to https://github.com/ValveSoftware/steam-runtime/issues/290#issuecomment-717589134.

**Closed as completed by kisak-valve** 2020-10-27 22:58 UTC
