### ISSUE TITLE
Fall Guys: Ultimate Knockout

### ISSUE THREAD

**Issue by JonathanCarpenter** [ValveSoftware/Proton#4515] opened 2020-12-30 23:30 UTC
Steam Play - Ubuntu 20.04.1 LTS (Focal Fossa). 
Fall Guys: Ultimate Knockout 

When I open the game I get an error that the Easy Anti-Cheat is not running. How can this be resolved?

**Comment by kisak-valve** [comment] 2020-12-30 23:42
Duplicate of https://github.com/ValveSoftware/Proton/issues/4123#issuecomment-752773123. Please do not intentionally open duplicate issue reports.

**Closed as completed by kisak-valve** 2020-12-30 23:42 UTC
