### ISSUE TITLE
Futex2

### ISSUE THREAD

**Issue by psychaos999** [ValveSoftware/Proton#5205] opened 2021-10-07 16:25 UTC
Hi,
my proton log starts with:
Proton: 1633354705 experimental-6.3-20211004
SteamGameId: 306130
Command: ['/mnt/500GB/steamapps/common/Zenimax Online/zosSteamStarter.exe']
Options: {'forcelgadd'}
depot: 0.20210907.26
pressure-vessel: 0.20210906.2
scripts: v0.20210818.0-0-gc6be089
soldier: 0.20210906.1 soldier 0.20210906.1
err:virtual:virtual_init Using kernel write watches (experimental).
fsync: up and running.

My kernel is a tkg kernel with futex2 enabled, but for what I can see proton enables only fsync.

What am I doing wrong?

Thank you in advance

**Comment by kisak-valve** [comment] 2021-10-07 16:45
Hello @psychaos999, my understanding is that both futex-wait-multiple and futex2 kernel patch sets will both show with the same `fsync: up and running.` line in Proton's log. Support for Futex2 is currently only enabled in Proton Experimental's patch set and if your kernel supports futex2, then it's used by default, so there's nothing actually wrong here.

From a broad level, you can compare your logs to some of the feedback on #4568.

Closing as not a bug.

**Closed as completed by kisak-valve** 2021-10-07 16:45 UTC
