### ISSUE TITLE
Life is Strange: Before the Storm requires PROTON_USE_WINED3D11 (554620)

### ISSUE THREAD

**Issue by Brisse89** [ValveSoftware/Proton#75] opened 2018-08-22 11:05 UTC
Life is Strange: Before the Storm will crash at startup.
Easily fixed by using PROTON_USE_WINED3D11
As far as I know, this game requires stream output which DXVK doesn't yet support.

**Comment by jarrard** [comment] 2018-08-22 11:07
STREAM output is a feature that is not supported in Vulkan, otherwise DXVK would use it. 

Maybe valve can put some pressure on the chronos group to push out a stream output support in the next release? that be neat!

**Comment by cjwijtmans** [comment] 2018-08-22 11:08
there are workarounds for stream functions to work on vulkan.

**Comment by jarrard** [comment] 2018-08-22 11:12
Yes but they CAN result in missing polygons and details for certain drivers/GPU's

**Comment by cjwijtmans** [comment] 2018-08-22 11:28
no i am talking about full functionality. There is a small performance impact tho.

**Comment by jarrard** [comment] 2018-08-22 11:33
well WineD3D11 is opengl so it should support it.

**Comment by cjwijtmans** [comment] 2018-08-22 11:35
`no i am talking about vulkan.

**Comment by jarrard** [comment] 2018-08-22 11:36
Well last time I checked AMD users were experiencing missing faces on certain characters with DXVK's stream output work around in Witcher3, so not sure if its improved since then (0.60 days)

**Comment by Brisse89** [comment] 2018-08-22 11:37
@jarrard @cjwijtmans 
The developer of DXVK has already been talking with Khronos about this.
I expect it will take some time to be implemented in Vulkan though, so this is a good workaround in the meantime.
I haven't tested the game extensively on Proton yet, but it runs very well in Wine with wined3d11, so I see no reason why it wouldn't work fine in Proton as well.
Only issues I've seen is my Xbox One controller is not working and mirrors are just plain black texture, but these things aren't exactly game-breaking.

**Comment by pierrep** [comment] 2018-08-22 12:00
You should all wait until Feral Interactive releases this game natively, unless you already have it in your library...

**Comment by jarrard** [comment] 2018-08-22 12:01
Yeah I'd hold off buying it until feral does their thing, then buy through them for Linux so the developers get the right message here!

**Comment by mirh** [comment] 2018-08-22 12:08
> [the normal algorithm is in effect, so if at the end of the two weeks you have more playtime on Linux, it'll be a Linux sale. Proton counts as Linux.](https://www.gamingonlinux.com/articles/valve-officially-confirm-a-new-version-of-steam-play-which-includes-a-modified-version-of-wine.12400)

**Comment by jarrard** [comment] 2018-08-22 12:10
Yes except I don't think Feral will get any money from that. Not sure how that works really.

**Comment by vanyasem** [comment] 2018-08-22 13:52
As a workaround (if you know what you're doing), you could rebuild DXVK with `fakeStreamOutSupport` set to `true` in `dxvk/src/d3d11/d3d11_options.cpp `. That doesn't magically implement steam output, but it makes DXVK advertise as if it was supported. This works with some games (tested with Overwatch and Mafia III)

**Comment by Brisse89** [comment] 2018-08-22 14:36
@vanyasem 
Probably not a good workaround for this game becouse the character models are invisible without stream output. Wined3d11 provides good performance and mostly correct rendering anyway. I'm capping the fps to 60 and it's pretty smooth on my R9 Fury with graphics maxed out.

**Comment by cjwijtmans** [comment] 2018-08-23 15:15
as far as i know that workaround is not fake as in it doesnt function its fake as in it doesnt use hardware capabilities. Its just a slight performance impact which isnt a big deal. I could be wrongtho.

**Comment by doitsujin** [comment] 2018-08-23 15:20
The workaround **does not** implement anything. It just returns a success code from a function where it would otherwise return an error code, which makes some games think that everything is fine.

Almost **all** Unity Engine games depend on this feature, but as mentioned in #233 already, it is currently unsupported, and for now there is no way to make it work other than using `PROTON_USE_WINED3D11=1`.

**Comment by cjwijtmans** [comment] 2018-08-23 16:41
That is an issue with DXVK as a chronos dev said it can be implemented.

**Comment by thermalthrottle** [comment] 2018-08-30 15:43
I'm having trouble with running Life is Strange: Before the Storm on Proton, even after using PROTON_USE_WINED3D11=1. Also I'm pretty new to Wine and Linux in general
The operating system I'm using is Linux Mint 19 "Tara".
System specs:
i7-4510U 2GHz
8GB RAM
GT 840M 2GB
1TB Hitachi HDD
On Windows 7 Ultimate I'm able to run it on 1920x1080 Ultra(Hella High) with around 40fps without any issues.
The Proton version is 3.7-3 but it doesn't work with 3.7-4 either
Edit:
In 3.7-5 doesn't  work either

Thanks in advance

Here's the log file: https://gist.github.com/batgo6o/5f4475a08a41bf420be00c2543ace9a2
Please, I'd really like to play this game on Linux

**Comment by TheRealCuran** [comment] 2018-09-01 16:39
I can confirm, that `PROTON_USE_WINED3D11=1` is required. Even without it, the game launches and runs (tested with Proton 3.7-5 Beta), but the character models are missing, only the environment is rendered. With PROTON_USE_WINED3D11=1 set, everything looks good so far.

**Comment by thermalthrottle** [comment] 2018-09-01 17:26
Ok, I know that. The problem is that I start the game, Steam shows it's running, but it doesn't actually run or make a sound.

**Comment by kisak-valve** [comment] 2018-09-13 14:37
Closing per https://twitter.com/feralgames/status/1040248513412706304.

**Closed as completed by kisak-valve** 2018-09-13 14:37 UTC
Labels: Game compatibility - Unofficial

**Comment by mirh** [comment] 2018-09-13 18:01
Does that kind of entail you are against https://github.com/ValveSoftware/steam-for-linux/issues/5638 ?

**Comment by kisak-valve** [comment] 2018-09-13 18:22
For the time being there is no value in tracking per game compatibility of games with native linux versions available via Steam. If that changes in the future we can reassess the value at that time.

It is a general question of what is in and out of scope for feedback on Proton with this issue tracker.

**Comment by lucifertdark** [comment] 2018-10-05 08:00
> Yes except I don't think Feral will get any money from that. Not sure how that works really.

Actually they (Feral) mentioned elsewhere that once they've announced they're working on a Linux port it's ok to buy the game as they WILL get their cut of the profits from that sale.

**Comment by JustCryen** [comment] 2023-06-03 15:41
Neither Proton or the natiive version work for me. Any ideas?  it's just not launching at all.
I've tried the `PROTON_USE_WINED3D11=1 %command%` launch option that everyone recommended and nothing improved.

**Comment by Brisse89** [comment] 2023-06-14 18:31
> Neither Proton or the natiive version work for me. Any ideas? it's just not launching at all. I've tried the `PROTON_USE_WINED3D11=1 %command%` launch option that everyone recommended and nothing improved.

Just stumbled on this comment by random chance more or less. Haven't tried this game in a long time, but decided to download it and see if this reproduces on my end as well.

It seems so. Tried native (Feral port) and it does not launch. Tried same but with Steam Play + Steam Linux Runtime. Not working. Don't know why.

Downloading for Proton as we speak. I'll update when I have the results.

Edit: Working for me when using Proton 8.0-2. It starts and I managed to load up one of my old saves and get into the game no problem.

Sidenote: `PROTON_USE_WINED3D11=1` should no longer be necessary. It was something we had to use back in 2018 because DXVK was still missing a feature needed by this game, but this is no longer the case and DXVK should probably be the preferred way to run the game now.

**Comment by JustCryen** [comment] 2023-06-15 06:35
> > Neither Proton or the natiive version work for me. Any ideas? it's just not launching at all. I've tried the `PROTON_USE_WINED3D11=1 %command%` launch option that everyone recommended and nothing improved.
> 
> Just stumbled on this comment by random chance more or less. Haven't tried this game in a long time, but decided to download it and see if this reproduces on my end as well.
> 
> It seems so. Tried native (Feral port) and it does not launch. Tried same but with Steam Play + Steam Linux Runtime. Not working. Don't know why.
> 
> Downloading for Proton as we speak. I'll update when I have the results.
> 
> Edit: Working for me when using Proton 8.0-2. It starts and I managed to load up one of my old saves and get into the game no problem.
> 
> Sidenote: `PROTON_USE_WINED3D11=1` should no longer be necessary. It was something we had to use back in 2018 because DXVK was still missing a feature needed by this game, but this is no longer the case and DXVK should probably be the preferred way to run the game now.

I tried over and over, constantly clearing the proton prefix, checking integrity of downloaded files and I re-downloaded the game a couple of times.
After doing all of this a couple of times, without doing anything differently, it finally worked with the same settings I had from the beginning. (I think that the third time I re-downloaded the game it actually clicked)

Quite a bizarre thing, at the end of the day, I did manage to get the Proton version working.
