### ISSUE TITLE
Button to play windows version instead of the linux one

### ISSUE THREAD

**Issue by Kryuko** [ValveSoftware/Proton#1481] opened 2018-09-16 10:50 UTC
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

There are a lot of steam games that are BROKEN and we are unable to play the game. 
So it will be usefull to add an option that let us to play the windows version of a game, and MAYBE, report that the game is no more working on linux, and send a request to remove the linux version from the store.
Thank you!

**Comment by Kryuko** [comment] 2018-09-16 11:32
And i add another point:
The linux version of ark is very graphically outdated if you look at the windows one.
The linux/osx version is still using opengl3.3 when we have opengl4.5 and vulkan, a lot of effects are missing or are too heavy.

Instead of this, can we play the windows version with dxvk?
Useful links: https://www.reddit.com/r/playark/comments/8l99ul/psa_to_linux_users_the_windows_version_of_ark_is/
https://www.youtube.com/watch?v=bRSSuJtafRg

**Comment by Kryuko** [comment] 2018-09-16 11:46
Sorry, duplicated issue of this:
https://github.com/ValveSoftware/steam-for-linux/issues/5638

**Comment by kisak-valve** [comment] 2018-09-16 12:59
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5638.

**Closed as completed by kisak-valve** 2018-09-16 12:59 UTC
