### ISSUE TITLE
Ghostbusters: The Video Game Remastered - Settings Aren't Saved After Exiting

### ISSUE THREAD

**Issue by RedSoxFan04** [ValveSoftware/Proton#7003] opened 2023-08-10 19:09 UTC
# Compatibility Report
- Name of the game with compatibility issues: Ghostbusters: The Video Game Remastered
- Steam AppID of the game: 1449280

## System Information
- GPU: RX 5600 XT
- Video driver version: Mesa 23.1.4
- Kernel version: 6.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/RedSoxFan04/4e5ba1d0c98a30684c5edf34e4d87736
- Link to Steam Runtime System Information: https://gist.github.com/RedSoxFan04/70416743cf87323e5708b60780babbad
- Proton version: 7.0-6

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

[ghost_d3d11.log](https://github.com/ValveSoftware/Proton/files/12316404/ghost_d3d11.log)
[ghost_dxgi.log](https://github.com/ValveSoftware/Proton/files/12316405/ghost_dxgi.log)

## Symptoms 
Settings aren't being saved to disk. Consequently, they have to be modified every time the game is launched. Well, unless you're happy with the base settings. Personally, I like to use the highest settings.

## Reproduction
1. Launch Game
2. Change Graphics Settings
3. Close Game
4. Re-Open Game
5. Check Graphics Settings to See if They Have Changed

## Solution
Through research and trial & error, I have found a solution which works: 
`mkdir ~/.steam/steam/steamapps/compatdata/1449280/pfx/drive_c/users/steamuser/AppData/Local/GHOSTBUSTERS`

**Comment by kisak-valve** [comment] 2023-08-10 19:25
Hello @RedSoxFan04, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/5087#issuecomment-1673785893.

**Closed as not planned by kisak-valve** 2023-08-10 19:25 UTC

**Comment by RedSoxFan04** [comment] 2023-08-10 19:35
> Hello @RedSoxFan04, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to [#5087 (comment)](https://github.com/ValveSoftware/Proton/issues/5087#issuecomment-1673785893).

Why have you closed it as "not planned"? It's such a simple solution!

**Comment by kisak-valve** [comment] 2023-08-10 21:28
Wording picked by Github for issue reports that are (from the mouse-over tooltip) "Won't fix, can't reproduce, duplicate, or stale." In this case, it's a duplicate compatibility report. Feel free to continue discussing how the game behaves with Proton on #5087.
