### ISSUE TITLE
Graphical issue with black squares on multiple games when using non-native resolutions

### ISSUE THREAD

**Issue by DNAmaster10** [ValveSoftware/Proton#8253] opened 2024-11-18 01:58 UTC
This is a duplicate bug report of [this issue](https://github.com/ValveSoftware/Proton/issues/6881). I'm opening this issue since no resolution seems to have been reached.

Although I've only attached screenshots for the game Foxhole, I've experienced this issue before on multiple other games. 

When changing from my monitor's native resolution to a lower resolution, a pattern of black squares appears at the bottom of the screen, often flickering rapidly. No amount of tweaking in-game settings beyond the resolution seems to affect this. The issue does not occur on windowed mode, but only appears when using full-screen. I'm unable to use my native resolution for performance reasons.

![PXL_20241118_013448112 MP](https://github.com/user-attachments/assets/0ce85ae6-429d-4075-8703-10e13b9369cb)
![PXL_20241118_013453777 MP](https://github.com/user-attachments/assets/681e2d21-58da-4427-8208-45690eacccd5)

The graphical artefacts did not appear in screenshots. This, along with what was mentioned in the previous bug report, makes me wonder whether this is actually an issue with RADV, although what to do to resolve this issue wasn't fully clarified. The previous poster seemed to indicate that switching to AMDVLK resolved the problem, however I'd prefer to avoid switching to this due to performance reasons.

I've attached the logs for Foxhole, in addition to some photos of my screen.

To reproduce this issue:
- Open Foxhole, or another game listed in the previous bug report
- Switch from your native resolution to a lower one
- Ensure the game is full screen

## System Information
- GPU: AMD Radeon RX 6700 XT
- Video driver version: Mesa 24.2.7
- Kernel version: 6.11.7-300.fc41.x86_64 (64-bit)
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/DNAmaster10/3e241754b6f268eb1f50f2ea69bb53f0
- Proton version: Proton Experimental and Proton 9.0-3

[steam-505460.log](https://github.com/user-attachments/files/17793372/steam-505460.log)

**Comment by kisak-valve** [comment] 2024-11-18 02:02
Hello @DNAmaster10, please do not intentionally open duplicate issue reports. This issue needs to be evaluated by video driver dev(s).

Closing as a duplicate of #6881.

**Closed as not planned by kisak-valve** 2024-11-18 02:02 UTC

**Comment by DNAmaster10** [comment] 2024-11-18 02:05
Thanks @kisak-valve for a quick response. Would you be able to point me towards the relevant place to submit this bug report instead? I'm quite unsure about where exactly the issue lies: Whether it's a Proton issue, Wayland issue, driver issue, etc.

**Comment by kisak-valve** [comment] 2024-11-18 02:39
https://docs.mesa3d.org/bugs.html is a starting point for mesa graphics issues.
