### ISSUE TITLE
> The V1.01 update is triggering an access violation for me too: https://imgur.com/a/4Yeu1o9

### ISSUE THREAD

**Issue by msmafra** [ValveSoftware/Proton#4085] opened 2020-07-19 13:22 UTC
> The V1.01 update is triggering an access violation for me too: https://imgur.com/a/4Yeu1o9
> 
> * Kernel version: pop-os 5.4.0-7634-generic
> * CPU: AMD Ryzen 3600
> * GPU: GTX 1660 Super
> * Nvidia driver: 440.100

And for me too.

- Distro: Fedora release 32 (Thirty Two) x86_64;
- Kernel: 5.7.8-200.fc32.x86_64;
- CPU: Intel i5-7300HQ (4) @ 3.500GHz;
- GPU: NVIDIA GeForce GTX 1050 Mobile;
- Nvidia driver version: 440.100
- Mesa: 20.1.3;
- wine-5.12 (Staging); if matters.

The same error, but now with kernel-5.7.8-fsync (GloriousEggRoll's one) and with Nvidia drivers 450.57 (Negativo17 repo).

_Originally posted by @msmafra in https://github.com/ValveSoftware/Proton/issues/4070#issuecomment-660289844_

**Comment by kisak-valve** [comment] 2020-07-19 13:24
Hello @msmafra, you've already posted this where it matters. Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/4070#issuecomment-660289844.

**Closed as completed by kisak-valve** 2020-07-19 13:24 UTC
