### ISSUE TITLE
For Hornor doesn't start

### ISSUE THREAD

**Issue by geekaia** [ValveSoftware/Proton#1269] opened 2018-09-05 23:57 UTC
I'm actually using ubuntu 18.04 and I've tried to use ubisoft For Honor, but the game doesn't start. 

Using nvidia driver -- version 390.87

**Comment by ghost** [comment] 2018-09-05 23:57
https://github.com/ValveSoftware/Proton/issues/462

**Comment by kisak-valve** [comment] 2018-09-06 00:12
Closing as a duplicate of #462.

**Closed as completed by kisak-valve** 2018-09-06 00:12 UTC
