### ISSUE TITLE
[whitelist] Fallout New Vegas

### ISSUE THREAD

**Issue by Hime0698** [ValveSoftware/Proton#814] opened 2018-08-28 11:27 UTC
Seems to work flawlessly.

**Comment by btegs** [comment] 2018-08-28 11:55
What are your specs? It can be hit and miss according to https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/htmlview?sle=true#gid=0

**Comment by kisak-valve** [comment] 2018-08-28 13:38
Closing as a duplicate of #356.

**Closed as completed by kisak-valve** 2018-08-28 13:38 UTC
