### ISSUE TITLE
VK9 should be added to Proton for Directx 9 games. Direct3D 9 to Vulkan.

### ISSUE THREAD

**Issue by setsunati** [ValveSoftware/Proton#505] opened 2018-08-25 09:42 UTC
Runs Direct3D 9 applications on Windows or Linux (/w Wine) over Vulkan.

https://github.com/disks86/VK9

**Comment by Zero86Sk** [comment] 2018-08-25 10:03
This could solve issues on a lot of older games

**Comment by jarrard** [comment] 2018-08-25 10:08
As its been pointed out before the project is not quite far enough along for integration, there are 39+ milestones needed to pass first and the chap is only at the 26th or so.

**Comment by vanyasem** [comment] 2018-08-25 11:01
Duplicate of #102

**Comment by kisak-valve** [comment] 2018-08-25 20:59
Closing as a duplicate of #102.

**Closed as completed by kisak-valve** 2018-08-25 20:59 UTC

**Comment by caioalarcon** [comment] 2021-11-27 14:18
bacana
