### ISSUE TITLE
Hearts of Iron III

### ISSUE THREAD

**Issue by Xeers** [ValveSoftware/Proton#994] opened 2018-08-30 16:28 UTC
The game is not launched, nothing comes out

Game removed: AppID 25890 "", ProcID 14072 
No cached sticky mapping in ActivateActionSet.ExecuteSteamURL: "steam://url/StoreAppPage/25890"
Generating new string page texture 142: 32x256, total string texture memory is 3.59 MB

Proton 3.7-3
Nvidia Geforce GTX 950
CPU AMD FX
Arch Linux

https://gist.github.com/Xeers/219b4b3e5eb10c6ec225d7cc8c61be44

**Comment by Dazarlin** [comment] 2018-08-30 18:54
Duplicate of an already open issue. Post there: https://github.com/ValveSoftware/Proton/issues/889

**Comment by kisak-valve** [comment] 2018-08-30 19:23
Closing as a duplicate of #889.

**Closed as completed by kisak-valve** 2018-08-30 19:23 UTC
