### ISSUE TITLE
Proton doesn't create compatdata folder when game launched from a NTFS disk

### ISSUE THREAD

**Issue by TheBolshe** [ValveSoftware/Proton#2540] opened 2019-04-15 02:25 UTC
## System Information
- GPU: GTX 960m
- Driver/LLVM version: nvidia 418.56
- Kernel version: 4.18.0-17
- Link to full system information report as [Gist](https://gist.github.com/TheBolshe/fd52f4420fc64cbdd53ad8e7c83b5c57):
- Proton version: 4.2

## I confirm:
- [x] that I have checked whether there are updates for my system available.

[steam-238960.log](https://github.com/ValveSoftware/Proton/files/3078211/steam-238960.log)

## Symptoms 
On a new install of linux i try to launch games installed through windows on a NTFS disk (set up with the FAQ). Nothing happens. The games launches and stops immediately. Proton downloaded only after i installed another game with linux so i could not get a proton log at first.
The compatdata directories are all empty and usually just not created

## Reproduction
- Install games on windows on a shared ntfs disk.
- On linux set up the disk following this : https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows
- On linux install Steam and set up games directory on the NTFS disk as principal and steam play options
- Try to launch game and accept Steam Play Warning
- Nothing happened here
- Proton did download when i tried to launch another game for the first time with steam play but then it just did nothing again

I moved Proton to the linux steam folder bub it didn't change anything.

I'm new to this whole thing so i may have omitted some things that i will be glad to add.

Edit : I thought that it could be because the default directory was on the NTFS disk so i changed it back to linux and downloaded a new game on the NTFS disk and tried to launch it. Still nothing happens.
Then i downloaded antoher game to the linux steam directory and tried to launch it. This time it created an entry in the compatdata directory and the game launched. I then moved it to the NTFS disk and it launched. So i guess that proton won't create prefixes if a game is launched from a NTFS disk.

**Comment by TheBolshe** [comment] 2019-04-15 11:46
Making it work once seems to have fixed the issue, but still that happened. Should i close ?

**Comment by kisak-valve** [comment] 2019-04-15 12:56
Hello @TheBolshe, it sounds like you encountered https://github.com/ValveSoftware/steam-for-linux/issues/6045. 

It's also worth noting , "Application files installed by Steam for Linux should not be shared (e.g. between Windows and Linux). This is a requirement of the Steam for Linux client." (from https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation) Please clarify if your experiments were with a shared Steam library, which can lead to unexpected behavior.

**Comment by TheBolshe** [comment] 2019-04-15 13:46
I have 2 installations for steam. One for windows located on the NTFS disk and one for linux located in the home folder of my linux installation. I added the NTFS steam library folder to the linux installation so i wouldn't have to redownload the games.

**Comment by kisak-valve** [comment] 2019-04-15 14:04
Thanks for clarifying, closing because shared Steam libraries is not supported.

**Closed as completed by kisak-valve** 2019-04-15 14:04 UTC

**Comment by cprn** [comment] 2021-09-22 20:17
Sorry for necro, hopefully commenting doesn't reopen. I wanted to add external library worked for me without issues up to a month ago or so and it's slightly different because:

1. I use EXT4, not NTFS,
2. `compatdata/{appid}` directories are getting created but `pfx` aren't. Fortunately it can be solved on a filesystem level with a few symbolic links.

And to document another use case: I keep library on the same drive, same partition (ext4) but outside of a user directory because I use family sharing to let other house residents play on my PC when I'm at work and it didn't make sense for me to keep big games on one drive multiple times (Witcher 3, Kingdom Come: Deliverance, Shadow of Mordor, Dying Light and Elite Dangerous take up over 200GB altogether and I have brother, cousin and girlfriend living with me - it'd be 800GB if they had their own copy each).
