### ISSUE TITLE
Rocket League (252950) crashes at start with 4.11-4

### ISSUE THREAD

**Issue by tyrohellion** [ValveSoftware/Proton#3061] opened 2019-09-15 18:23 UTC
# Compatibility Report
- Name of the game with compatibility issues: Rocket League
- Steam AppID of the game: 252950

## System Information
- GPU: RX 480
- Driver/LLVM version: Mesa 19.1.6
- Kernel version: 5.2.13-126
- Proton version: 4.11-4

## I confirm:
- [yes ] that I haven't found an existing compatibility report for this game.
- [ yes] that I have checked whether there are updates for my system available.

## Proton log
[steam-252950.log](https://github.com/ValveSoftware/Proton/files/3614112/steam-252950.log)

## Symptoms 
I have been testing out rocket league performance on proton 4.11-3 for a while and as soon as proton 4.11-4 came out rocket league crashes everytime it loads up. I have tried this on manjaro kde, xfce, openbox, and solus budgie.

**Comment by kisak-valve** [comment] 2019-09-15 18:42
Looks like the log hints there is a controller related issue with `warn:debugstr:OutputDebugStringA "[0011.80] Log: Detected new XInput controller 0\r\n"` immediately before hitting an access violation (c0000005) and falling over.

**Comment by aeikum** [comment] 2019-09-16 12:36
This looks very similar to #3059, see similar crash addresses.

**Comment by aeikum** [comment] 2019-09-16 20:22
This seems to be caused by having some kind of special input device attached. Can you confirm that you do? If so, a fix is available at #3059 and will be in the next release, due out very soon.

**Comment by tyrohellion** [comment] 2019-09-18 04:15
> This seems to be caused by having some kind of special input device attached. Can you confirm that you do? If so, a fix is available at #3059 and will be in the next release, due out very soon.

I have an xbox one controller plugged in. I will check out that fix for the time being. Thank you for all your help everyone!

**Comment by aeikum** [comment] 2019-09-18 17:41
Hello, 4.11-5 was released today and may have fixed your problem. Please retest!

**Comment by tyrohellion** [comment] 2019-09-19 22:11
Thank you everyone for the help. Just to put it out there Proton 4.11-5 has fixed this issue! <3

**Closed as completed** 2019-09-19 22:10 UTC
Labels: Game compatibility - Unofficial, Regression, XAudio2
