### ISSUE TITLE
Visual artifacts in multiple games, possibly related to a Mesa regression.

### ISSUE THREAD

**Issue by Siam-Lights** [ValveSoftware/Proton#6821] opened 2023-06-03 06:31 UTC
As I mentioned on #328, upon booting up the title, I noticed visuals were displaying incorrectly. I then booted up more games and noticed they also had the same problem. The following games started to show artifacts in my system ever since the Mesa 23.1.1 update. I tried reverting to stable Proton versions, but none of them changed anything. As far as I have tested, they're the only games in my library to show any issues at the moment.

- Guilty Gear XX Accent Core Plus R, 
- Guilty Gear Xrd -REV2-
- Under Night In-Birth[cl-r] 

I'm attaching a log for GGXXACR and screenshots.
[steam-348550.log](https://github.com/ValveSoftware/Proton/files/11641893/steam-348550.log)
![Screenshot from 2023-06-02 23-10-39](https://github.com/ValveSoftware/Proton/assets/97821031/99d3c480-2026-4c42-bdac-5b1941ab6ec5)
![Screenshot from 2023-06-02 23-06-13](https://github.com/ValveSoftware/Proton/assets/97821031/e012f665-ddd1-4773-b310-9dea5ca5d469)
![Screenshot from 2023-06-02 22-30-04](https://github.com/ValveSoftware/Proton/assets/97821031/f496e160-62bc-4cb8-a604-88f3c3fd8752)

**Comment by kisak-valve** [comment] 2023-06-03 13:35
Hello @Siam-Lights, since you suspect a video driver regression, this issue should be mentioned to your video driver vendor.

**Comment by Siam-Lights** [comment] 2023-06-04 10:58
I found that running the game with PROTON_USE_WINED3D=1 displays the image properly. Should I open a ticket on the dxvk issue tracker?
![Screenshot from 2023-06-04 03-52-32](https://github.com/ValveSoftware/Proton/assets/97821031/02cbd5d4-941e-4e5c-abd3-cd7ec1bf8543)

**Comment by mbriar** [comment] 2023-06-04 16:58
If it works with DXVK on older Mesa version then I would recommend to report the issue on the [Mesa gitlab bugtracker](https://gitlab.freedesktop.org/mesa/mesa/-/issues), and not to DXVK.

**Comment by hakzsam** [comment] 2023-06-21 13:07
@Siam-Lights Did you open https://gitlab.freedesktop.org/mesa/mesa/-/issues/9155 ? Both issues look really similar. If it's you, I suppose this one should be closed too.

**Comment by kisak-valve** [comment] 2023-07-22 00:59
Closing per the last comment.

**Closed as completed by kisak-valve** 2023-07-22 00:59 UTC
Labels: Mesa drivers, AMD RADV
