### ISSUE TITLE
Proton on steam forces vulkan for nouveau driver which breaks all 3D rendering

### ISSUE THREAD

**Issue by Kreyren** [ValveSoftware/Proton#4669] opened 2021-03-11 03:21 UTC
Vulkan is not implemented in nouveau.

Solution is to use `PROTON_USE_WINED3D=1 %command%` as a launch option.

**Comment by kisak-valve** [comment] 2021-03-11 03:23
Duplicate of #4629.

**Closed as completed by kisak-valve** 2021-03-11 03:23 UTC

**Comment by Kreyren** [comment] 2021-03-11 03:24
Did you meant # 1 7 4 9 ? I wasn't sure if nouveau should have it's own tracking as it's system capable of vulkan hardware-wise

**Comment by kisak-valve** [comment] 2021-03-11 03:29
You're repeating information you were already aware of.

Nouveau does not currently support Vulkan in any capacity, and it would need to grow a conformant implementation with at least enough features to satisfy DXVK's (and where appropriate, VKD3D's) needs. It doesn't matter if the hardware has potential if you can't use it with the drivers.

**Comment by Kreyren** [comment] 2021-03-11 03:30
noted
