### ISSUE TITLE
Doom (2016) has no audio after id Software logo (379720)

### ISSUE THREAD

**Issue by poperigby** [ValveSoftware/Proton#3339] opened 2019-12-19 01:53 UTC
# Compatibility Report
- Name of the game with compatibility issues: Doom (2016)
- Steam AppID of the game: 379720

## System Information
- GPU: GTX 1060 6GB
- Driver/LLVM version: nvidia 440.44-3
- Kernel version: 5.4.4.arch1-1
- [Link to full system information report as Gist](https://gist.github.com/PopeRigby/52e226ed161b375a7ce2881ae6762854) 
- Proton version: 4.11-9

## Symptoms 
After starting Doom (2016) the Bethesda logo and it's accompanying sound play, after that the id Software logo with its accompanying sound plays about half-way through, before the audio cuts out. Then the audio never comes back, even in-game.

[Proton log](https://github.com/PopeRigby/protonlog)

**Comment by kisak-valve** [comment] 2019-12-19 16:25
Hello @PopeRigby, friendly note that your attached log is for Proton 3.16-9 (the current whitelisted Proton version for this game). If you want to test a different Proton version, you need to set it in the per-game Steam Play tool override. (Steam -> Library -> Right click on the game -> Properties -> Check `Force the use of a specific Steam Play compatibility tool` -> Pick a Proton version from the dropdown)

That said, can you check if Proton 4.2 or 4.11 has better behavior for you?

**Comment by poperigby** [comment] 2019-12-19 16:57
* 4.2-9 didn't work ([Log file](https://github.com/PopeRigby/protonlog/commit/3355949d460aab14681e51453c7896b89a463914))
* 4.11-9 seems to have fixed the sound issue, but the entire screen is [letterboxed](https://user-images.githubusercontent.com/20866468/71192495-4093d100-223d-11ea-8e43-460e1fb82d63.jpg)
now, which is bizarre ([Log file](https://github.com/PopeRigby/protonlog/commit/0bbf805857b239ab2c146bc7aa893760544d13ce))

**Comment by parkerlreed** [comment] 2019-12-19 18:26
Proton scales resolutions automatically. Is the game set to the monitor's native resolution?

**Comment by parkerlreed** [comment] 2019-12-19 18:28
@kisak-valve Speaking of newer Proton, are there any plans of updating the compatibility for the "official" games? 3.16 for Doom is quite old and 4.11 has a significant performance increase in the loading times.

**Comment by kisak-valve** [comment] 2019-12-19 18:40
If there's a substantial improvement, we can request that the whitelisted Proton version for a game get an update here. It's handled in the same way we request a game get added to the whitelist, but using the [`Whitelist Update Request`](https://github.com/ValveSoftware/Proton/labels/Whitelist%20Update%20Request) label.

**Comment by poperigby** [comment] 2019-12-22 01:11
> Proton scales resolutions automatically. Is the game set to the monitor's native resolution?

It wasn't. It's fixed now. Thanks.

**Comment by kisak-valve** [comment] 2019-12-22 01:22
Hello @PopeRigby, let's keep this issue report open as a whitelist update request since the newer version helped.

**Comment by poperigby** [comment] 2019-12-22 03:30
Alright, my bad.

**Comment by Leopard1907** [comment] 2019-12-22 10:40
I've completed this game on 4.11-9.

It worked flawlessy. Sadly i finished and deleted it before raw input patches on 4.11-11 landed but assuming it is an fps shooter game and using 4.11 also helps some woes like it did with OP's problem ; a whitelist version bump really would be great.

**Comment by devonallie** [comment] 2020-02-10 15:56
I actually have a similar issue as OP on 3.16-9 but the audio comes back at the main menu.

**Comment by kisak-valve** [comment] 2021-09-01 16:10
Hello, please retest this game with Proton 6.3-6 and see if any regressions have crept in since this issue was last evaluated.

**Closed as completed** 2021-10-01 16:49 UTC
Labels: XAudio2, Whitelist Update Request
