### ISSUE TITLE
Sifu (2138710)

### ISSUE THREAD

**Issue by Edumadaluk** [ValveSoftware/Proton#7207] opened 2023-10-27 21:22 UTC
Compatibility Report

Name of the game with compatibility issues: Sifu
Steam AppID of the game: 2138710
System Information

Steam Deck (Beta Channel)
Proton version: GE 8-14, GE 8-20, Experimental and 8.0-4

I confirm:
 that I haven't found an existing compatibility report for this game.
 that I have checked whether there are updates for my system available.

[steam-2138710.log](https://github.com/ValveSoftware/Proton/files/13059466/steam-2138710.log)

Symptoms
Game freezes under certain conditions. Mostly on character tab in game menu.

Reproduction
One reproducible condition is after entering a map and being able to control the character, go into menu and switch between the menu tabs.
After a few actions of switching tabs, the game freezes around the CHARACTER tab.

**Comment by kisak-valve** [comment] 2023-10-27 21:28
Hello @Edumadaluk, please do not intentionally open duplicate issue reports. Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/6657#issuecomment-1773349392.

**Closed as not planned by kisak-valve** 2023-10-27 21:28 UTC

**Comment by Edumadaluk** [comment] 2023-10-27 22:14
So why don’t you answer previous reports?Att, EduardoEm 27 de out. de 2023, à(s) 18:28, kisak-valve ***@***.***> escreveu:﻿
Hello @Edumadaluk, please do not intentionally open duplicate issue reports. Closing as a duplicate of #6657 (comment).
