### ISSUE TITLE
Quake Live (282440) mouse lags and inverse-accel (negative accel) 5.0+

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#3685] opened 2020-03-25 04:14 UTC
# Compatibility Report
- Name of the game with compatibility issues: Quake Live
- Steam AppID of the game: 282440

## System Information
- GPU:  Intel HD Graphics 530
- Driver/LLVM version:  Mesa 19.2.8
- Kernel version:  5.3.0-42
- Link to full system information report as [Gist](https://gist.github.com/): (private)
- Proton version: 5.0

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

## Symptoms 
Same issue described as in the following ticket [#3529 (comment)](https://github.com/ValveSoftware/Proton/issues/3529#issuecomment-587539290) for Doom 2016 but for Quake Live.
Mouse sensitivity is registering different than on the Proton 4.0 branch.
[Edit: The default sensitivity and the feeling of it is overall 2x slower than the 4.0 branch and how the sensitivity should be. In addition to the inverse accel which I will mention below, the actual sens. is a lot slower in the game (2x).]

If you move the mouse quickly even with all acceleration parameters off and using raw input it will go a shorter distance than if you slowly move the mouse the same distance. Moving the mouse on the mat slowly results in a similar sensitivity like on the 4.0 branch and also makes it go twice as far in the game (in terms of 360's).

It's like some kind of reverse (negative accel) effect is going on in the game. Slow movements make the mouse travel further in the game and super fast one's are abrupt and short (for same distance).

I know this is a Proton bug b/c if I revert to the 4.0 branch the Quake Live sensitivity is not impacted by speed of my mouse movement as well it also matches a different game (which uses the same code = Quake III Arena, which I am playing natively on Linux outside of Steam).

## Reproduction
Use either Ubuntu 19.10 or the Daily branch of 20.04. Move the mouse slowly in Proton 5.0 for a set distance. Then move the mouse very fast over this same distance. Even with all OS acceleration turned off and the mouse will be two very different 360 degree turns in the game. Fast will give you ~ 2.5x less of a 360. Slowly moving the mouse will give you 2.5x more 360. Distance should be ==

**Comment by kisak-valve** [comment] 2020-03-25 12:37
Hello @username2222232, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/3406#issuecomment-603815301.

**Closed as completed by kisak-valve** 2020-03-25 12:37 UTC

**Comment by username2222232** [comment] 2020-03-25 14:47
Hi @kisak-valve 
What are my chances of getting a resolution on this? Mouse issues rarely occur in isolation but I couldn't find any complaints about similar issues in other games...

This game has 300 players on average on a daily basis playing.  If we are optimistic 5% of those are Linux players.  So I am maybe 1 out of these 15 people total.

It's a shame because I like the improved performance (higher frames) with ver. 5.0 but the mouse being off is very frustrating, the overall sensitivity is much lower than it should be (from all prior Proton versions as well as Windows when I played on Windows).

What can I do to help?

**Comment by wfstuff** [comment] 2020-03-26 13:41
Hi, I can't reproduce it. I'm running Quake Live with proton 5.0.5 and Ubuntu 19.04. Mouse sensitivity seems the same as in Proton 4.x
Do you use mouse acceleration in Quake Live? I'm not using any mouse acceleration in game and in Ubuntu at all.
I'm planning to update my Ubuntu installation the next weeks. Will check after the update if it happens for me with 19.10 or 20.04.

**Comment by username2222232** [comment] 2020-03-26 16:25
@wfstuff I was using stock Ubuntu 19.10 and it requested after installing steam-launcher to install (3):
libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6:i386.

I didn't install anything extra.  It is super noticeable that 5.0.5 has a much slower base sensitivity than 4.11.13 + negative accel.

Now for 20.04, the steam-launcher has a dependency to use python but its been deprecated.  So I had to reconfig. that Debian package to ignore that dependency and not install python2.  And the only thing extra I installed from stock Ubuntu was:  libgl1-mesa-glx:i386 (after enabling 32-bit dpkg's).
> Hi, I can't reproduce it. I'm running Quake Live with proton 5.0.5 and Ubuntu 19.04. Mouse sensitivity seems the same as in Proton 4.11.13

I never use mouse acceleration! I loath it! \seta cl_mouseAccel "0" on Ubuntu my desktop environment has acceleration completely turned off and I've tested it swinging my arm super fast :P
> Do you use mouse acceleration in Quake Live? I'm not using any mouse acceleration in game and in Ubuntu at all.

Please test it out.  I'm thinking maybe this is a mouse polling rate issue.  My Logitech is 1000 Hz by default, I am going to test a Microsoft Wheel Mouse Optical and get back to you.  I am very thankful for your reply!
> I'm planning to update my Ubuntu installation the next weeks. Will check after the update if it happens for me with 19.10 or 20.04.

**Comment by username2222232** [comment] 2020-03-26 16:54
Tested with a lower Hz mouse.  Microsoft Wheel Mouse Optical which is 125 Hz.  The negative accel is either gone or almost non-existent.  The base sensitivity is still 2x lower than it should be as intended and how it should be since Proton 4 and prior.

It seems that the negative acceleration is some kind of mouse polling issue.

**Comment by wfstuff** [comment] 2020-03-26 19:05
I'm using a Razer Abyssus 2014 which seems to have 1000Hz polling rate. In my config "in_mouse" is set to "2"

**Comment by wfstuff** [comment] 2020-03-26 19:21
I had a short research and it seems I set in_mouse to 2 for some good reason in the past ;) Perhaps you could try in_mouse 2 and see if there is still some negative acceleration. Of course you'll need to adjust the sensitivity, too.

Some quotes from my research:

New 'raw device' input mode. Set in_mouse 2 to bypass DirectInput and talk to your mouse device directly. We have seen bad interference from various software, and in general you might get more reliable / better quality mouse input with in_mouse 2.

-1 - Windows cursor input, subject to cursor ballistics
0 - No mouse input
1 - Dinput (direct input)
2 - WM_INPUT (raw)

**Comment by username2222232** [comment] 2020-03-26 20:53
Yes that is also the default value.  I've always played using 2 (even on Windows) to be extra sure that acceleration is off and should not interfere. I've noticed strange behaviors with some proton updates and had to actually switch from 2 to 1 (or in this case -1) to get sensitivity to behave appropriately.  Like the update that happened right after 4.11.9 that caused a lot of "mouse skipping" seemed to impact both raw and windows input but directInput was slightly more stable.

In general, when I'm discussing this issue, I'm using \seat in_mouse "2" which is the default behavior.
It looks like almost all the negative accel (or there's perhaps a lesser amount of it) when using the Windows cursor input in Proton.

I'm still looking forward if maybe you'll notice anything strange when you upgrade!

**Comment by username2222232** [comment] 2020-03-26 20:55
I also believe Razor Abyssus may default to 500 Hz (unless you made explicit changes).
Did you check the maximum ranges you reach on the ZOWIE rate checker tool?  Doesn't require any install, simply JavaScript from browser and click + move cursor.
https://zowie.benq.com/ja/support/mouse-rate-checker.html

**Comment by wfstuff** [comment] 2020-03-26 21:11
Seems to cap at 460 for me

**Comment by username2222232** [comment] 2020-03-26 21:27
Perhaps the negative accel, never kicks in on your end.  It might be part of the High Polling Rate regression fix they put in on 5.0.3 changelog and it might be only noticeable on a 1000 Hz freq.

I barely noticed or could see any negative accel when on the 125 Hz Wheel Mouse Optical.

wfstuff, thanks for being responsive btw.
