### ISSUE TITLE
Error when loading mods in Skyrim (72850)

### ISSUE THREAD

**Issue by valeth** [ValveSoftware/Proton#301] opened 2018-08-23 17:03 UTC
When trying to load mods in Skyrim an error message appears on the launcher with the message `Failed to extract plugin file from ckm!`.

This does not prevent the game from being launched, it just skips initializing any third party mods (the high resolution texture packs seem to work, they are at least listed in the `Data Files` menu).
![screenshot_20180823_185709](https://user-images.githubusercontent.com/3198362/44540304-b5690080-a706-11e8-9e2e-be4ec433d814.png)

[System Info](https://gist.github.com/valeth/3231d8ac2e593601015c90d27cd43288#file-steam-system-info-txt)

**Comment by kisak-valve** [comment] 2018-08-23 18:02
Hello @valeth, we'll be tracking game compatibility in one issue report per unofficially supported game so I've gone ahead and transferred this to https://github.com/ValveSoftware/Proton/issues/4#issuecomment-415512908.

**Closed as completed by kisak-valve** 2018-08-23 18:02 UTC

**Comment by jgysland** [comment] 2018-08-29 13:22
@kisak-valve I think this was merged into the wrong issue; it looks like (and is confirmed by my experience that) this is a problem with the non-SE version of Skyrim.

**Comment by kisak-valve** [comment] 2018-08-29 14:48
Indeed, it was. The current Skyrim non-SE issue report is at #460.
