### ISSUE TITLE
Proton 5.13: Games use some generic mouse cursor and not the one set in the window manager

### ISSUE THREAD

**Issue by M-Reimer** [ValveSoftware/Proton#4317] opened 2020-10-26 17:21 UTC
Since Proton 5.13 games use some kind of generic mouse cursor (could be the default Gnome cursor with default size).

Especially in "Among Us" this is an issue as the small black cursor is often difficult to see on the mostly dark maps. For this reason I changed my mouse cursor to a white cursor and made it a bit bigger.

Why is this so? Does Proton 5.13 bring own cursors? Is this fixed if I just delete them?

The issue not only exists for full screen games. If I have two windows open, one regular "native Linux" window and one "Proton" window, then the mouse cursor changes while just moving the mouse between the two windows...

**Comment by Newbytee** [comment] 2020-10-27 08:14
> Why is this so? Does Proton 5.13 bring own cursors? Is this fixed if I just delete them?

It is due to that Proton 5.13 runs in Pressure Vessel. ~~You get the same thing if you run Linux games in Pressure Vessel~~ Not any more? I'm not able to reproduce this with the games I checked out just now.

**Comment by M-Reimer** [comment] 2020-10-27 09:43
In this context it is actually quite impressive that Pressure Vessel already is that good. "Among Us" is a "non officially supported" game and actually works pretty good.

I hope this mouse cursor problem can be fixed. Until then I'll switch back to the Proton version, I've used before.

**Comment by Francehelder** [comment] 2021-01-27 22:35
Same here.

I'm on Ubuntu MATE 20.04.1 LTS
I followed a YouTube tutorial for disable Pressure Vessel because cursor theme.

**Comment by Kisamos** [comment] 2021-07-06 10:04
Same here on Manjaro KDE, moreover the cursor tends to disappear...
I didn't have this problem on Mate-desktop with compiz.

**Comment by kisak-valve** [comment] 2021-09-07 17:24
Noted at https://github.com/ValveSoftware/steam-runtime/issues/311#issuecomment-914475240, the behavior around this issue should have improved with the current `client_beta` release branch of `Steam Linux Runtime - Soldier`.

There's some instructions on switching runtime container versions at https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version and you can check what version of the runtime container is in use at `<Steam library folder>/common/SteamLinuxRuntime_soldier/VERSIONS.txt`.

Please retest with the `depot 0.20210907.26` version (or newer).

**Comment by kisak-valve** [comment] 2021-10-08 18:16
A Steam Linux Runtime - Soldier release with this has been promoted to the mainline update channel. Closing as fixed.

**Closed as completed by kisak-valve** 2021-10-08 18:16 UTC
