### ISSUE TITLE
Chronos: Before the Ashes (967390)

### ISSUE THREAD

**Issue by sevansup** [ValveSoftware/Proton#6369] opened 2022-12-08 20:37 UTC
# Compatibility Report
- Name of the game with compatibility issues: Chronos: Before the Ashes
- Steam AppID of the game: 967390

## System Information
- Steam Deck (Stable branch) - up to date
- Proton version: 7.0-5

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Sorry, this is my first compatibility report. I don't know if I need to give all the info, but I simply wanted to make Valve aware that this game seems to *only* work on  7.0-4. Anything later (currently) breaks it, and anything earlier has issues. 6.3-8 for example does not play intro cutscenes. Tested on Steam Deck in the Stable branch, up to date as of 12/8/2022.

**Comment by kisak-valve** [comment] 2022-12-08 20:39
Hello @sevansup, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by alasky17** [comment] 2022-12-09 15:49
@sevansup Thank you for reporting this regression!  We are investigating it currently.

**Comment by CSahajdacny** [comment] 2022-12-10 03:08
It  must be an specific Steamdeck failure, because on my Ubuntu 20.04 desktop, the game works fine with PROTON 7.0-5, including cutscenes..

**Comment by sevansup** [comment] 2022-12-11 18:03
[steam-967390.log](https://github.com/ValveSoftware/Proton/files/10202866/steam-967390.log)
Here is the requested log file. Crashes before menu, though once I managed to load (only once, can't reproduce). It didn't crash at all on 7.0-4

Here is gist: https://gist.github.com/sevansup/15fb1363b447247ec2d3d531dba91056

> Hello @sevansup, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression, and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.) Also, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by alasky17** [comment] 2022-12-12 15:07
@CSahajdacny @sevansup Yep - it turns out that it is a race condition and enabling logging can "fix" it.  This should now be fixed in the "bleeding-edge" beta branch, and the public beta of 7.0-6 (available as a beta for the 7.0-x branch).

**Closed as completed** 2023-02-24 17:37 UTC
Labels: Game compatibility - Unofficial, Regression, XAudio2
