### ISSUE TITLE
"Failed to request product key from Steam, please try again in a few minutes." when launching Assassins Creed games

### ISSUE THREAD

**Issue by boyddensmore** [ValveSoftware/Proton#4539] opened 2021-01-13 05:01 UTC
When launching either Assassins Creed II (AppID 33230) or Assassins Creed Revelations (AppID 201870) I get the error "Failed to request product key from Steam, please try again in a few minutes." I've tried several times over the past 3 days and still get the same error.

I logged a ticket with Steam Support (HT-67B9-4J7R-HDPK) and Kelson let me know that since these games aren't verified yet I should log an issue with you folks.

Proton Experimental
[System Information](https://gist.github.com/boyddensmore/1b4506a250f15ddd1dbc39e064155a8f)

I have searched and haven't found any solutions and I don't have any updates for my system.

Thanks!

**Comment by ghost** [comment] 2021-01-13 09:21
@boyddensmore I had the same issue (as have lots of others I believe), and the reason is apparently because it's trying to download the Mac OS key, as well as the Window one (and it's the Mac one that's failing). The solution is to patch the `appinfo.vdf` file to tell it to ignore the Mac key. This comment has a link to the file you should use, but please also read the surrounding comments for context: https://github.com/ValveSoftware/Proton/issues/190#issuecomment-735877518

And maybe this issue should be closed as a duplicate of that one...

**Comment by kisak-valve** [comment] 2021-01-13 12:32
Hello @boyddensmore, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/212 / https://github.com/ValveSoftware/steam-for-linux/issues/5649. Closing as a duplicate.

**Closed as completed by kisak-valve** 2021-01-13 12:32 UTC
