### ISSUE TITLE
Proton 5.13.5 freeze with every game

### ISSUE THREAD

**Issue by Somamint** [ValveSoftware/Proton#4591] opened 2021-02-04 19:02 UTC
# Compatibility Report
- Name of the game with compatibility issues: Age of Empires 2
- Steam AppID of the game: 813780

## System Information
- GPU: <RTX 2060-->
- Driver/LLVM version: <NVIDIA  455.38->
- Kernel version: <5.8.0-7630-generic>
- Link to full system information report as [Gist](https://gist.github.com/Somamint/63caeb672acd55b875b818dab838a0e9/):
- Proton version: 5.13.5

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

Log: https://paste.ubuntu.com/p/ktNPVSxcsN/

## Symptoms 
Every game i want to start with Proton 5.13.5 will freeze in the first seconds and then crash.

**Comment by kisak-valve** [comment] 2021-02-04 19:18
Hello @Somamint, looking at your log, it looks like the Intel GPU is getting used, even though you've configured the system to use nVidia's prime render offload. I suspect that you're seeing the same issue as https://github.com/ValveSoftware/steam-runtime/issues/312. Can you give the workaround in https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559 a try?

**Comment by Somamint** [comment] 2021-02-04 19:34
Ok wow that worked!

**Comment by kisak-valve** [comment] 2021-02-04 19:38
Glad to hear it helped. Let's treat this as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/312. Closing.

**Closed as completed by kisak-valve** 2021-02-04 19:38 UTC
