### ISSUE TITLE
proton: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by jadbox** [ValveSoftware/Proton#139] opened 2018-08-22 18:58 UTC
Client: Steam Beta, though flatpak

Game(s) tested with bug:
Quake (original)

System:
Linux Fedora 28
Kernel 4.17.14
nvidia 1080 gtx

Issue: Game crashes upon startup.

Log:
```
JS method call WebChat.BSuppressPopupsInRestore with 1 arguments
Generating new string page texture 110: 512x256, total string texture memory is 2.07 MB
Generating new string page texture 111: 1024x256, total string texture memory is 3.12 MB
Generating new string page texture 112: 384x256, total string texture memory is 3.51 MB
Generating new string page texture 113: 8x256, total string texture memory is 3.52 MB
GameAction [AppID 2310, ActionID 1] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 2310, ActionID 1] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 2310, ActionID 1] : LaunchApp continues with user response "0"
GameAction [AppID 2310, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
sh: /home/jdunlap/.var/steamapps/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: bad interpreter: No such file or directory
sh: /home/jdunlap/.var/steamapps/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: bad interpreter: No such file or directory
sh: /home/jdunlap/.var/steamapps/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: bad interpreter: No such file or directory
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 2310
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 2310
GameAction [AppID 2310, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 2310, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 2310, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 2310, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 2310, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 70
Game update: AppID 2310 "", ProcID 227, IP 0.0.0.0:0
ERROR: ld.so: object '/home/jdunlap/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: /home/jdunlap/.var/steamapps/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: bad interpreter: No such file or directory
>>> Adding process 227 for game ID 2310
GameAction [AppID 2310, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 228 for game ID 2310
GameAction [AppID 2310, ActionID 1] : LaunchApp changed task to Completed with ""
Game removed: AppID 2310 "", ProcID 227 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1534892652)
```

flatpak list
```
Ref                                                    Options               
com.valvesoftware.Steam/x86_64/stable                  system (extra),current
org.libretro.RetroArch/x86_64/stable                   system (extra),current
org.freedesktop.Platform.Compat.i386/x86_64/18.08      system (extra),runtime
org.freedesktop.Platform.GL.nvidia-396-51/x86_64/1.4   system (extra),runtime
org.freedesktop.Platform.GL32.nvidia-396-51/x86_64/1.4 system (extra),runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08      system (extra),runtime
org.freedesktop.Platform.html5-codecs/x86_64/18.08     system (extra),runtime
org.freedesktop.Platform/x86_64/18.08                  system (extra),runtime
com.github.fabiocolacio.marker/x86_64/stable           system,current       
org.freedesktop.Platform.Compat32/x86_64/1.6           system,runtime        
org.freedesktop.Platform.GL.nvidia-396-24/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL.nvidia-396-45/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL.nvidia-396-51/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL32.nvidia-396-24/x86_64/1.4 system,runtime        
org.freedesktop.Platform.GL32.nvidia-396-45/x86_64/1.4 system,runtime        
org.freedesktop.Platform.Icontheme.Adwaita/x86_64/1.0  system,runtime        
org.freedesktop.Platform.ffmpeg/x86_64/1.6             system,runtime        
org.freedesktop.Platform/x86_64/1.6                    system,runtime        
org.gnome.Platform/x86_64/3.28                         system,runtime
```

**Comment by tfaller** [comment] 2018-08-22 19:06
> /usr/bin/python2.7: bad interpreter: No such file or directory 

It seems that you don't have Python 2.7 installed. Python 2.7 will be not shipped through steam. You have to install it.

**Comment by kisak-valve** [comment] 2018-08-22 19:21
Hello @jadbox, this is being discussed on the Flatpak'd steam side. Closing in favor of https://github.com/flathub/com.valvesoftware.Steam/issues/152.

**Closed as completed by kisak-valve** 2018-08-22 19:21 UTC

**Comment by ghost** [comment] 2018-08-22 19:23
Operating system:
Fedora release 28 (Twenty Eight)

Steam client:
(Beta client with Steam Play enabled for all titles.)

```
Ref: app/com.valvesoftware.Steam/x86_64/stable
ID: com.valvesoftware.Steam
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-22 17:36:55 +0000
Subject: Remove leftover file from NSS (2587e941)
Commit: 6f89e8e1d5055e51ddf74445d8687a509d872a7bff8977d7eab5a78e820e7b1d
Parent: cee6aa772a026794d0664f24e80ce7d47ea3b5adb8ecf10c3de37235df8b5e18
Location: /var/lib/flatpak/app/com.valvesoftware.Steam/x86_64/stable/6f89e8e1d5055e51ddf74445d8687a509d872a7bff8977d7eab5a78e820e7b1d
Installed size: 3,3 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
```

Games:
https://store.steampowered.com/app/473690/ (Absover)
https://store.steampowered.com/app/242920/ (Banished)
But seems to be a general problem with similar setups.

Error log:
```
No cached sticky mapping in ActivateActionSet.GameAction [AppID 473690, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
sh: /home/dima/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden
sh: /home/dima/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden
sh: /home/dima/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden
installscript_posix.cpp (416) : Assertion Failed: Standalone evaluator returned error code for app 473690
GameAction [AppID 473690, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 473690, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 473690, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 473690, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 473690, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask: 70
Game update: AppID 473690 "", ProcID 334, IP 0.0.0.0:0
>>> Adding process 334 for game ID 473690
GameAction [AppID 473690, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/dima/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: /home/dima/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton 3.7/proton: /usr/bin/python2.7: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden
GameAction [AppID 473690, ActionID 3] : LaunchApp changed task to Completed with ""
>>> Adding process 335 for game ID 473690
Game removed: AppID 473690 "", ProcID 334
```

@tfaller In my setup the python binary is at the right location and executable.

I think it could be that /usr/bin/python2.7 on the host is not accessible by the flatpaked client

**Comment by nanonyme** [comment] 2018-08-22 20:39
Since there's still ongoing questions in this closed ticket, I'd want to make an official explanation of what's going on as one of the maintainers of bundle where Valve's Steam is shipped through Flatpak:

First of all, the way Flatpak works the application does not have access to your system executables. It does not matter whether or not you have Python 2 installed. Everything that the application needs has to be shipped through runtime, runtime extensions or the application itself. The system is by design isolated for reproducible deployments across different distros.

Secondly, we just recently migrated to a new Flatpak runtime that does not have Python 2 anymore. Any applications that need Python 2 simply do not run.

Finally we made a judgment call that it doesn't make sense to currently wait for Proton to be ported to be Python 3 compatible so we instead decided to ship Python 2 inside the Flatpak application itself. Some trivial changes were done to Proton to make it support the setup better.

As @kisak-valve said above, please direct all further questions about the Flatpak package to the linked issue instead of this one.
