### ISSUE TITLE
Proton not starting, vrclient.dll not found

### ISSUE THREAD

**Issue by Ryhon0** [ValveSoftware/Proton#2585] opened 2019-04-22 14:32 UTC
Hello, I'm trying to play Doom 2016 with Proton 4.2 but when I start a game it doesn't open, the console outputs this:
```
>>> Adding process 3829 for game ID 379720
Traceback (most recent call last):
  File "/run/media/ryhon/5E62D9CA62D9A755/Program Files (x86)/Steam/steamapps/steamapps/common/Proton 4.2/proton", line 366, in <module>
    try_copy(basedir + "/dist/lib/wine/fakedlls/vrclient.dll", dst)
  File "/run/media/ryhon/5E62D9CA62D9A755/Program Files (x86)/Steam/steamapps/steamapps/common/Proton 4.2/proton", line 131, in try_copy
    shutil.copy(src, dst)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/ryhon/5E62D9CA62D9A755/Program Files (x86)/Steam/steamapps/steamapps/common/Proton 4.2/dist/lib/wine/fakedlls/vrclient.dll'
JS method call SharedConnection.SendMsgAndAwaitResponse with 3 arguments
Game removed: AppID 379720 "", ProcID 3827 
Exiting app 379720
```
I'm using the latest version of Manjaro with 4.20 kernel and GTX 1050Ti with 418.56 proprietary driver
The partition with Proton and Doom is NTFS and the options for it in fstab are `ntfs-3g defaults,exec,uid=1000,gid=1000 0 0`
Older versions of Proton don't start because it says the game executable file does not exist

Full log: [steam-log.txt](https://github.com/ValveSoftware/Proton/files/3103637/steam-log.txt)

**Comment by MollyMaclachlan** [comment] 2019-04-22 15:48
I'm no expert, so this could be wrong, but I checked and my Proton 4.2 contains that file.

You could try verifying the integrity of the files for Proton 4.2

If you don't know how to do that: go into your library menu and click on "Tools", just above "Downloads", you should be able to scroll down and find Proton 4.2.
![verifyintegrity](https://user-images.githubusercontent.com/47920497/56509392-c2045980-651e-11e9-8d2f-64feb35e758f.png)

Right click on it and go into "Properties"
![verifyintegrity2](https://user-images.githubusercontent.com/47920497/56509233-54f0c400-651e-11e9-94d4-92d3cdf0b853.png)

Now switch to the "Local Files" tab, then "Verify Integrity of Tool Files". 
![verifyintegrity3](https://user-images.githubusercontent.com/47920497/56509247-5f12c280-651e-11e9-88a2-017e600c3e8d.png)

This will check through the files for Proton 4.2 and download any that are missing.

This tends to work with a lot of missing files in games, so it's worth a shot for ones in Proton as well. Hopefully, this helps, but as I said, I'm not an expert so I could be totally off. Either way, it can't do any harm to try.

**Comment by Ryhon0** [comment] 2019-04-22 16:07
I've verified the integrity of files and no issues were found, the Proton 4.2/dist/lib folder just does not exist

**Comment by MollyMaclachlan** [comment] 2019-04-22 16:15
The entire lib folder doesn't exist? 

![verify4](https://user-images.githubusercontent.com/47920497/56510508-e9105a80-6521-11e9-9ab0-2ff9b5805cc8.png)

That's most of Proton that's missing (375.1MB/480MB, so ~78%). I've no idea why that hasn't been flagged by the verify, but at least now we know the problem is larger than just the one file.

**Comment by Ryhon0** [comment] 2019-04-22 16:38
I've looked in the Proton folder and there's a file called `proton_dist.tar.gz`, I've exported it and renamed the folder to dist and all the files are there. Looks like steam has issues with installing Proton. Also, Proton weights 1,3 GB and steam is saying it's 480 MB, `proton_dist.tar.gz` itself is 504 MB

**Comment by MollyMaclachlan** [comment] 2019-04-22 17:28
Hm, that's interesting. Perhaps the installing and size calculation issues should be flagged as a separate issue?

**Comment by ghost** [comment] 2019-04-22 23:18
Verify requires proper support for any files (example: config files are not marked to verify because they would then be overwritten and user settings reset). Don't know how Valve has it set up here but if its not working then that seems to answer that.

[Besides Steam thinking files exist when they don't, or something else but then that would mean verify needs to be fixed as well or the problem causing verify to fail in a way not wanted needs to be fixed, etc..]

Perhaps switching the global Proton version in use and restarting Steam will trigger a change? Can't tell if you did that or setting for each game.

Of course, a reset of Steam might work as well, etc. Probably something will at some point even if its nuking the Steam install.

Obviously though you have a problem to be fixed.

**Comment by aeikum** [comment] 2019-04-23 12:39
We package all of the Wine files into a tarball for Steam distribution reasons. We then unpack the tarball when Proton is first run for a given update. We decide whether to unpack based on the presence and contents of the `dist/version` file. If it doesn't exist or differs from the `version` file, then we remove the `dist` folder and unpack the tarball. I don't know what would cause the `dist` folder to be unpacked incorrectly. Perhaps you ran out of disk space at some point? I think we don't handle that case particularly well.

**Comment by lexmortis** [comment] 2019-04-27 22:08
I have the same issues. I went through the same steps to try and fix it, like verifying files, un/reinstalling proton. Verifying passes without a problem, but the whole `lib` thing is still missing.

Uninstalling doesn't work, due to an error something about missing shared resourced? I switched to a different proton version, then I could delete 4.2 (from within Steam), and reinstalled it. The problem persisted about missing `lib` and unable to play.

I browsed to the Proton dir and extracted `proton_dist.tar.gz`, got the following error:
![extract_bug](https://user-images.githubusercontent.com/36314565/56855451-aa2a3c80-6947-11e9-968d-bf067a7ceb74.png)

I can extract`lib` and `lib64` fine, but it goes wrong with `share`. However, after putting both lib dirs into 
`dist`, Proton works!

My guess: something in `share` breaks extraction, so `lib` and `lib64` don't get extracted?

Potentially 2 new/related bugs:
Is it a bug that I cannot uninstall a broken install?
How come verification passes when entire directories are missing?

**Comment by joder666** [comment] 2019-04-27 22:35
Got hit by this one too, similar set up.

I have ~/Games/steamapps set as a symblolic link to my Windows Steam/steamapps folder added as another Steam Library.

Closing steam,  Deleting Proton4.2 its corresponding manifest and compatdata folder from and trying again with both 4.2 and 3.16 ended up with the same problem.

I copied the game files to the linux system, deleted the proton, manifest, compatdata, opened steam ran the game proton 4.2 downloaded and it ran OK.

Disk space at least for me its not the issue, my windows and linux drive have over 100GB of free space. May be its a filesystem issue?

**Comment by dreamer** [comment] 2019-04-27 23:21
@joder666 double check if your Windows partition is not mounted read-only (not by looking at fstab, but by trying to actually write a file). [Here's long and detailed explanation.](https://askubuntu.com/questions/145902/unable-to-mount-windows-ntfs-filesystem-due-to-hibernation)

**Comment by ghost** [comment] 2019-04-27 23:22
> I browsed to the Proton dir and extracted `proton_dist.tar.gz`, got the following error:
> ![extract_bug](https://user-images.githubusercontent.com/36314565/56855451-aa2a3c80-6947-11e9-968d-bf067a7ceb74.png)

If you cannot extract a tar.gz file then either you have a problem with your system or the compressed file is corrupted. You might want to solve that first before jumping onto something else.

(There can only be those 2 situations here)

**Comment by joder666** [comment] 2019-04-28 00:32
> @joder666 double check if your Windows partition is not mounted read-only (not by looking at fstab, but by trying to actually write a file). [Here's long and detailed explanation.](https://askubuntu.com/questions/145902/unable-to-mount-windows-ntfs-filesystem-due-to-hibernation)

Yes my NTFS drive it is write-able.

**Comment by smirgol** [comment] 2019-05-29 12:19
I have the same problem, where extracting the proton_dist.tar.gz on a NTFS drive won't work for me, it will abort with the same error as described above. It works without problems on an EXT drive, though.

**Closed as completed** 2020-04-09 13:58 UTC
