### ISSUE TITLE
Proton 3.7-4 Beta still seems to need Python 2.7

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Proton#772] opened 2018-08-27 20:20 UTC
I had Python version 3.6.5 installed and I had Steam set to the Proton 3.7-4 beta but my games would not load. Clicking play would do nothing, the games simply closed upon launch. The changelog says that 3.7-4 now supports python3 as well as python2, but that doesn't seem to work correctly.

I was only able to make the games work by installing Python 2.7 which then allowed the games to launch. This was tested with games all officially supported.

OS: Ubuntu 18.04 64bit (Stared with a minimal install)
GPU: Nvidia GeForce GTX 970
Driver Version:  4.6.0 NVIDIA 396.54
RAM: 16 GB
CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

**Comment by Elkasitu** [comment] 2018-08-27 20:56
Duplicate of #532

**Closed as completed** 2018-08-28 04:47 UTC
