### ISSUE TITLE
Games cannot launch if Virtual Desktop option is applied.

### ISSUE THREAD

**Issue by Blayer98** [ValveSoftware/Proton#7411] opened 2024-01-15 20:01 UTC
Hi there, I originally posted this issue in Protontricks’s GitHub repo as I thought it was to do with that, but it seems to be that it’s actually related to Proton’s wine version.

Somehow it seems that the Enable Virtual Desktop option is no longer working as it will give the following error if PROTON_LOG=1 is specified on any game (Steam/Non-Steam) or if I try and run winecfg, regedit, or Explorer through protontricks after enabling it:

“err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.”
“err:winediag:nodrv_CreateWindow L”The explorer process failed to start.””

I can confirm this was previously working fine with no issues sometime around Jan-Feb last year as I had attempted to use it for SimCity 3000 Unlimited (a non-Steam game).

Another user on Reddit about 2 years ago needed to use a Virtual Desktop for Divinity II, a Steam game. https://www.reddit.com/r/wine_gaming/comments/v0aglb/virtual_desktop_with_proton_using_protontricks/

This bug was seemingly caught back in June 2023 but was not fixed and solved until August 2023 in wine-staging’s 8.10 version.
https://bugs.winehq.org/show_bug.cgi?id=55085

For now, using an older Proton version like 7.0.6 works fine.

**Comment by ivyl** [comment] 2024-01-16 11:51
Hi!

We don't actively support virtual desktop in this downstream. There are no controls exposed to enable it and as you have noted, you have to use third party tools. From my point of view it's a leftover from upstream. It's not actively tested or cared for so it just bit rots.

IIRC virtual desktop was in a rough shape in upstream Wine 8.0 release which we are based on and only got fixed over time in minor releases. We haven't picked up those patches. That's likely why 7.0 works but 8.0 not.

We also carry a large downstream patchset called fshack that integrates deep into winex11.drv and can break features that are not actively supported in this area.

May I ask what's your usecase for virtual desktop?

**Comment by Blayer98** [comment] 2024-01-16 12:01
Hi thanks for replying!

My use case was for a non-Steam game ran through Proton, The Sims 1, but I just managed to get it working without the need to use virtual desktop as a workaround. :)

I did see other people using virtual desktop like in my post for Divinity II to get around issues when Alt Tabbing however. :)

**Comment by cubimon** [comment] 2024-01-18 00:02
@Blayer98 how did you solve your issue? I recently got a similar issue for guild wars 2, the launcher freezes, in virtual desktop mode it works though, but I can use virtual desktop only from wine, proton refuses to open a virtual desktop. I basically have to use it only once to enter and save credentials and setup Autologin, after that setup I don't mind if it freezes

**Comment by Blayer98** [comment] 2024-01-18 00:10
> @Blayer98 how did you solve your issue? I recently got a similar issue for guild wars 2, the launcher freezes, in virtual desktop mode it works though, but I can use virtual desktop only from wine, proton refuses to open a virtual desktop. I basically have to use it only once to enter and save credentials and setup Autologin, after that setup I don't mind if it freezes


@cubimon 
In my use case (the sims 1) I think I just ended up re-creating it as a non-Steam game to get a brand new prefix folder including default settings and I just left it as is, I think I was trying to set the renderer to GDI which didn’t work, but when I reset the prefix and got a brand new one, that change was reverted and the game ended up running like normal on both Gaming and Desktop mode on Proton Experimental without the need to use a Virtual Desktop :)

What proton version are you using? Since I had to downgrade to Proton 7.0.6 in order to get the Virtual Desktop to even show up since 8.0.4 and above (as of writing this post) doesn’t work due to a bug that yet hasn’t been ported into Proton’s wine build. I just double checked and the virtual desktop does run in Proton 7.0.6 in Gaming Mode for me as well as Desktop Mode :)

**Comment by cubimon** [comment] 2024-01-18 22:26
Thanks :)  Proton 7 with the virtual desktop made it working, unluckily I couldn't just switch to proton 8 after login, I guess it uses a different wine prefix with different windows profiles

**Comment by Blayer98** [comment] 2024-01-19 13:29
> Thanks :) Proton 7 with the virtual desktop made it working, unluckily I couldn't just switch to proton 8 after login, I guess it uses a different wine prefix with different windows profiles

Glad you got it working! I think the registry entries get wiped if you switch to a different Proton version so it might be worth backing them up first before upgrading, that’s what happened to me at one point. :)

**Comment by cubimon** [comment] 2024-01-28 21:49
Gamescope seems to fix this issue as well, so I don't need the virtual desktop feature

**Comment by alasky17** [comment] 2024-04-16 14:12
@Blayer98 @cubimon There is a fix for the virtual desktop in 9.0-experimental.  It would be greatly appreciated if you could let me know if virtual desktop behavior there now matches 7.0-6 :)  Y'all probably already know this, but I would recommend getting a backup of your prefix first so that if 9.0-experimental isn't working you don't have to do any prefix setup again.

**Comment by Techwizz-somboo** [comment] 2024-05-04 20:59
> @Blayer98 @cubimon There is a fix for the virtual desktop in 9.0-experimental. It would be greatly appreciated if you could let me know if virtual desktop behavior there now matches 7.0-6 :) Y'all probably already know this, but I would recommend getting a backup of your prefix first so that if 9.0-experimental isn't working you don't have to do any prefix setup again.

It seems to work for me, but offsets my game far right. Thanks for your work on this issue!
![Screenshot from 2024-05-04 14-58-17](https://github.com/ValveSoftware/Proton/assets/44146804/6f104033-516e-4cd1-a766-fa8df54ebe4f)

**Comment by Techwizz-somboo** [comment] 2024-05-04 22:00
It actually seems that the whole desktop is shifted. Also, the wine desktop appears on my non-primary monitor, but that might be because of flatpak, not sure. My other monitor is of a different resolution (1920x1080) while my primary is 2560x1080.  
![Screenshot from 2024-05-04 15-57-37](https://github.com/ValveSoftware/Proton/assets/44146804/510d9095-125a-44ba-8f49-ada23400bc01)

**Comment by alasky17** [comment] 2024-05-06 12:51
@Techwizz-somboo Have you tried Proton 7.0-6?  Could you see if the behavior of shifting to the far right is a new behavior, or if it is the same as 7.0-6?

**Comment by Techwizz-somboo** [comment] 2024-05-06 14:41
> @Techwizz-somboo Have you tried Proton 7.0-6? Could you see if the behavior of shifting to the far right is a new behavior, or if it is the same as 7.0-6?

Same as 7.0-6. Vanilla WINE handles it fine, though.

**Comment by RW74** [comment] 2024-07-17 20:08
About the shifting it seems related to the primary monitor not being on the left side. it started with version 9. If I put the primary on the left all works fine but on some games I get the max resolution of the primary even if I move the window on the right side :(

**Comment by alasky17** [comment] 2024-08-26 13:37
@RW74 @Techwizz-somboo We have tweaked some things for virtual desktop in experimental-9.0-bleeding-edge that should help with the behavior.  Hopefully this improves the experience of virtual desktop + proton :)  The fixes will be in the next experimental release as well, but right now they live only in bleeding-edge.

**Comment by alasky17** [comment] 2024-12-13 01:53
The fix for the virtual desktop behavior when the primary monitor is on the right has shipped with Proton 9.0-4.  I'm going to close this issue for now under the assumption that it is fixed universally (since it is fixed in my local testing).  If anyone is still experiencing this regression, please let me know :)

**Closed as completed by alasky17** 2024-12-13 01:53 UTC

**Comment by Techwizz-somboo** [comment] 2024-12-29 19:54
> @RW74 @Techwizz-somboo We have tweaked some things for virtual desktop in experimental-9.0-bleeding-edge that should help with the behavior. Hopefully this improves the experience of virtual desktop + proton :) The fixes will be in the next experimental release as well, but right now they live only in bleeding-edge.

Hey, sorry for the long response time. It seems to be working much better! The only quirk I see is it doesn't go into "full screen", only a separate window. Which is still a lot better, but stock WINE will make the wine desktop "full screen" if the resolution matches the resolution of the monitor. It allows for emulating borderless full screen on games that don't support it. 

Good work!
