### ISSUE TITLE
Support non-steam games

### ISSUE THREAD

**Issue by Raj2032** [ValveSoftware/Proton#260] opened 2018-08-23 11:29 UTC
Could we please try and support non-steam games as well?

**Comment by thunder1410** [comment] 2018-08-23 12:24
Would be nice, maybe first make sure most of the steam games already work?

**Comment by fazo96** [comment] 2018-08-23 12:50
I think @Raj2032 meant adding a windows game to steam as a non-steam game like you do on Windows and then running it with Proton on Linux

**Comment by Raj2032** [comment] 2018-08-23 13:06
I meant see how Proton only supports Steam games? I want Proton to also
support non-steam games without using the Steam client.

**Comment by do-m-en** [comment] 2018-08-23 14:27
Proton is using Wine under the hood and wine works without the steam client. This feature request is more sutable for wineHQ bug tracker (or for playonlinux project that is like proton a wine wrapper). That being said if valve will contribute back to wine other games will work better as a side effect so they are essentially already working on your request.

**Comment by IceAmaura** [comment] 2018-08-23 15:33
~~@do-m-en Installing and configuring a separate wine instance, especially with having to pick what wine builds and what patches and what winetricks, creates a large complication for people who would like to run non-steam games on Linux. Being able to add a non-steam game to the native Linux client and have Photon run it is much more user friendly (and also a lot less time-consuming). Though, this has the downside of having a lesser chance of the game working due to the Photon instance not being manually tweaked for the game.~~

~~TL;DR I think it should be added anyway for ease of use and avoiding time waste.~~

EDIT: I didn't read Raj's clarification correctly. Outside of Steam, just using Wine should work because of upstreaming. You can use Lutris as a wrapper for that.

**Comment by cjwijtmans** [comment] 2018-08-23 17:01
steam allows adding game shortcuts outside of steam. maybe something can be done with adding a proton option. this should be moved to steam-for-linux?

**Comment by kisak-valve** [comment] 2018-08-23 17:58
Closing as a duplicate of #122.

**Closed as completed by kisak-valve** 2018-08-23 17:58 UTC

**Comment by Raj2032** [comment] 2018-08-24 00:01
So is Valve actually going to contribute back to Wine though?

**Comment by r4-broadcast** [comment] 2018-09-04 10:42
I tried 2 Non-Steam games:

Warcraft 3 & Frozen Throne: Run without issues, only Videos got an error. fur running them I'm using:

`STEAM_COMPAT_DATA_PATH=~/.proton/ ~/.steam/steam/steamapps/common/Proton\ 3.7/proton run whatever.exe`

**Comment by gagoalaverdyan** [comment] 2018-10-06 21:31
You don't have to do terminal stuff that much. Here's my guide on how to use Proton outside Steam and install any game into it:
1. Install Steam on your Linux PC
2. Open Steam, login to your account.
3. Go to Settings, Steam Play and tick all the checkboxes. Press OK, Steam will require a restart, agree with that.
4. Now find any free Windows-only game (e.g. Trove) add it to your library and install it. Steam will warn you that the game will try to launch using Steam Play. Agree with that, too.
5. Once your game is installed, launch it. Wait until it launches, then close it, and exit Steam.
6. Now install PlayOnLinux, launch it so it creates all basic needed directories, then exit.
7. Navigate to "/home/YOURUSERNAME/.steam/steam/steamapps/common/".
8. You will see a folder named "Proton x.y" here (at the moment of writing this guide, the latest available version is 3.7). Open it, and you will see a folder named "dist" there.
9. Move the "dist" folder to "/home/YOURUSERNAME/.PlayOnLinux/wine/linux-amd64/" then rename the folder to "Proton".
10. Open PlayOnLinux, try to install any Windows game by manual method, you will see "Proton" in available 64-bit Wine versions.
I tried my own method with The Sims 4, and everything works perfectly. I had a Wine-Staging prefix before and the game worked awful and dropped framerates once in 5 seconds. With proton all lags are gone! Anyway, it depends on game. You still may need to install all required libraries by game manually to your Proton prefix.

**Comment by bugz8unny69** [comment] 2018-10-09 12:10
Thanks for the great guide however my experiences over years with PlayOnLinux. The other solutions are just more simpler. From Ubuntu, OpenSuSE, Fedora, to ArchLinux. Getting a game to register and run successfully always spew out Python errors. PlayOnLinux developers, wait for the next version of PoL2. I'll see if I can get a Lutris (Sometimes fails) or Q4Wine (Works nearly 100% of the time) setup working instead.

**Comment by gagoalaverdyan** [comment] 2018-10-15 21:25
> Thanks for the great guide however my experiences over years with PlayOnLinux. The other solutions are just more simpler. From Ubuntu, OpenSuSE, Fedora, to ArchLinux. Getting a game to register and run successfully always spew out Python errors. PlayOnLinux developers, wait for the next version of PoL2. I'll see if I can get a Lutris (Sometimes fails) or Q4Wine (Works nearly 100% of the time) setup working instead.

Thank you for the reply! What any other methods of using Proton do you know? I didn't find anything before my own study.

**Comment by bugz8unny69** [comment] 2018-10-17 16:31
Besides what I mentioned above, no, I don't know of any other. :) BTW, if you are on ArchLInux, seems on AUR there is https://aur.archlinux.org/packages/proton/. I haven't gotten around to testing myself yet. Perhaps, it would be unnecessary to install Steam at all if you only interested in playing games not directly purchased from Steam.

**Comment by losthope0076** [comment] 2018-11-07 16:26
>     9. Move the "dist" folder to "/home/YOURUSERNAME/.PlayOnLinux/wine/linux-amd64/" then rename the folder to "Proton".

Why dont  do a symbolic link? 

If Valve will update Proton you have to move it again.

if you do a symbolic link the Proton version of PlayOnLinux will be up to date.

please correct me if i am wrong

**Comment by milroneth** [comment] 2019-02-25 13:43
As an update to these, there is a way to run any game with nothing but the Steam client. I tried it with my old Unreal Tournament 99 installation still on my windows drive and worked like a charm while regular wine failed, LowMemSky (a PICO-8 cartridge compiled to Windows .exe), a little freeware Unity game and the Windows version of AssaultCube Portable from PortableApps to also try an installer.

Do these steps once:
--------------------
- Go to your Steam settings, "Steam Play" on the left and Enable Steam Play. Optionally, Enable it for all titles too, so that you need fewer steps for each game you want to add (though I suggest against it, see below).
- After Steam restarts go to the "Tools" section of your Library and install any Proton versions you are going to use. If you don't know, select the most recent one (currently Proton 3.16 Beta is the latest).

For each game:
--------------
- Go to Steam's main window, on the left-down corner click "Add a Non-Steam Game...", "Browse...", change the File type to "All Files", find your game's Windows executable and add it to your library.
- (Optional) Right-click the new entry, go to its Properties, name it as you please in the first field and select "Force the use of a specific Steam Play compatibility tool".
  - Note that if you didn't choose to Enable Steam Play for all titles in the settings, this step if REQUIRED otherwise it's going to run using your system's wine version.
  - Even if you selected that, you may want to try different versions for each game and see what works better. Remember to have the corresponding Proton version installed from Tools, otherwise, it falls back to system wine again.
- Launch and enjoy.

Additional notes:
-----------------
- I did happen to encounter a game (LowMemSky) that run fine with normal wine but not with Proton, so that's why I don't suggest you enable Proton for all games, as this will give you more control over each game separately.
- There is a known bug while adding a non-Steam game, the Steam client messes up at the first space in the path and puts the rest in the launch options. So, if there are spaces in your game's path it won't launch unless you go to its Properties, click "Set launch options..." and clear that out (since it has been auto-filled with the rest of your game's path and might cause errors) and then click "Change..." and select the executable again so the "Target" field gets populated properly.
- The above method assumes that your game is already installed or is portable. If you only have an installer, you can add the installer as a game, install it and then change that shortcut to point to the installed .exe instead.
  - If you install a game using the above method, the installer's Browse function will let you install either to a Linux path (like /home/user/games/), that will also show up as drive Z:, or a local C: drive. Always choose the former so that you actually know where your game files go and for future proofing because that C: drive is tied to the specific Proton version currently running.
