### ISSUE TITLE
Star wars Republic Commando(6000)

### ISSUE THREAD

**Issue by BaconFootBallYT** [ValveSoftware/Proton#4927] opened 2021-06-28 16:23 UTC
KooName of the game with compatibility issues: Star Wars Republic Commando
Steam AppID of the game:6000
Proton version:Expermentail
system info: https://gist.github.com/BaconFootBallYT/801e95c9cb600ffce988f7dbe33dda28 
Issue;it gets stuck in a relaunch loop and then the window closes and nothing opens
[steam-6000.log](https://github.com/ValveSoftware/Proton/files/6727843/steam-6000.log)

`

3
#

**Comment by kisak-valve** [comment] 2021-06-28 16:32
Hello @BaconFootBallYT, please do not intentionally open duplicate issue reports. Closing as a duplicate of #4926.

**Closed as completed by kisak-valve** 2021-06-28 16:32 UTC
