### ISSUE TITLE
Proton 5.13 refuse to work on my Ubuntu 20.04 machine

### ISSUE THREAD

**Issue by CSahajdacny** [ValveSoftware/Proton#4313] opened 2020-10-24 23:40 UTC
Games doesn't work via Proton 5.13 and Proton Logs are not created... 
Previous Proton versions works fine with most of my games.

[This is my system](https://gist.github.com/CSahajdacny/07a4c2e835804bb7368673bd8035d8f4).

And [this is the steam console output](https://gist.github.com/CSahajdacny/261d51ce2f47ed757d98a261ed0e0e4b).

**Comment by kisak-valve** [comment] 2020-10-25 00:03
Hello @CSahajdacny, `ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.` might be a line of interest from your log and your issue might be related to https://github.com/ValveSoftware/steam-runtime/issues/286. Please check your system log for similar segfault messages.

**Comment by CSahajdacny** [comment] 2020-10-25 00:19
The only segfault messages I got in my system log are these:


```
Oct 24 21:10:04 Benitez-PC kernel: [ 5726.844662] pressure-vessel[13768]: segfault at 0 ip 0000000000000000 sp 00007ffe1869bdf8 error 14 in pressure-vessel-launch[400000+14000]
Oct 24 21:10:04 Benitez-PC kernel: [ 5726.844666] Code: Bad RIP value.
Oct 24 21:10:04 Benitez-PC kernel: [ 5726.850624] pressure-vessel[13811]: segfault at 0 ip 0000000000000000 sp 00007ffe827d1cf8 error 14 in pressure-vessel-launch[400000+14000]
Oct 24 21:10:04 Benitez-PC kernel: [ 5726.850628] Code: Bad RIP value.
Oct 24 21:10:04 Benitez-PC kernel: [ 5726.987430] pressure-vessel[13875]: segfault at 0 ip 0000000000000000 sp 00007ffef6af0828 error 14 in pressure-vessel-launch[400000+14000]
Oct 24 21:10:04 Benitez-PC kernel: [ 5726.987433] Code: Bad RIP value.
Oct 24 21:10:04 Benitez-PC assert_20201024211004_26.dmp[13889]: Uploading dump (out-of-process)#012/tmp/dumps/assert_20201024211004_26.dmp
Oct 24 21:10:04 Benitez-PC kernel: [ 5727.276915] pressure-vessel[13891]: segfault at 0 ip 0000000000000000 sp 00007ffd7d00e2b8 error 14 in pressure-vessel-launch[400000+14000]
Oct 24 21:10:04 Benitez-PC kernel: [ 5727.276919] Code: Bad RIP value.
Oct 24 21:10:05 Benitez-PC kernel: [ 5728.171858] pressure-vessel[13905]: segfault at 0 ip 0000000000000000 sp 00007fff81a75238 error 14 in pressure-vessel-launch[400000+14000]
Oct 24 21:10:05 Benitez-PC kernel: [ 5728.171862] Code: Bad RIP value. 
```

**Comment by kisak-valve** [comment] 2020-10-25 00:29
Thanks, that confirms it's the same issue. You should be able to work around the issue with something like `sudo apt purge gtk3-nocsd` (do not let this command go ahead if it wants to remove a bunch of unexpected packages).

Closing as a duplicate of https://github.com/ValveSoftware/steam-runtime/issues/286.

**Closed as completed by kisak-valve** 2020-10-25 00:29 UTC
