### ISSUE TITLE
The speed of games broke after latest updating the proton experimental


### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/Proton#4724] opened 2021-04-02 09:04 UTC
In-game time accelerated very much.  Nvidia GTX 1060 SteamOS 2.0

**Comment by rbernon** [comment] 2021-04-02 09:23
Most like likely a duplicate of https://github.com/ValveSoftware/Proton/issues/4719

**Comment by kisak-valve** [comment] 2021-04-02 11:40
Closing as a duplicate of #4719.

**Closed as completed by kisak-valve** 2021-04-02 11:40 UTC
