### ISSUE TITLE
How to use Wine installed in the system ?

### ISSUE THREAD

**Issue by Bulbyzarr** [ValveSoftware/Proton#594] opened 2018-08-25 21:54 UTC
Hi,

I'm on Gentoo and i installed on my system wine 3.14 with Staging/d3d9/esync patches and i would like to know if it's possible to use this version of wine instead of wine 3.7.

If i go to Settings -> SteamPlay, i have only Proton 3.7 version.

I tried to compile only `lsteamclient` and move the dll.so file (32/64 bits) in their respective folder but without effects.

Thanks,

**Comment by OpenProgger** [comment] 2018-08-25 22:20
As far as I understand the proton script, it uses hardcoded paths for wine and his libs. I don't know if the build-script provides an option to detect installed wine versions and simply symlink them. It could be a solution to add a config to choose which wine binary should be used.

**Comment by mirh** [comment] 2018-08-25 23:05
Duplicate of #22

**Comment by kisak-valve** [comment] 2018-08-26 00:53
Closing as a duplicate of #22.

**Closed as completed by kisak-valve** 2018-08-26 00:53 UTC
