### ISSUE TITLE
Network Not Responding

### ISSUE THREAD

**Issue by BigDaddyJ1569** [ValveSoftware/Proton#3381] opened 2019-12-28 15:49 UTC
Hello,

When I launch warframe I am unable to login even when I use the right credentials and enter in the 2fa correctly. When waiting for the credentials to authorize, the Network Not Responding icon appears and disappears several times. I have downloaded the xboxdrv, I'm using Directx11, I'm not using fullscreen. I just slapped on this Ubuntu 18.04.3 LTS distro yesterday, and I'm still going through the initial bugs. Any help would be appreciated.

**Comment by kisak-valve** [comment] 2019-12-28 15:54
Closing as a duplicate of #3380.

**Closed as completed by kisak-valve** 2019-12-28 15:54 UTC
