### ISSUE TITLE
Regression: SDL_GAMECONTROLLERCONFIG Environment Variable Ignored

### ISSUE THREAD

**Issue by nezd5553** [ValveSoftware/Proton#5667] opened 2022-03-12 05:50 UTC
## System Information
- GPU: GTX 1660Ti Mobile
- Driver/LLVM version: NVIDIA 510.47.03
- Kernel version: 5.16.12-200.fc35.x86_64
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/nezd5553/03b3ec2276e5027dcc6d36d4ec19efc0
- Proton version: Experimental (experimental-7.0-20220310)

When Steam Input is disabled, controller mappings from the environment variable SDL_GAMECONTROLLERCONFIG are no longer used. This was tested with a Nintendo Switch Pro Controller with the hid-nintendo kernel module loaded. The environment variable is needed to fix controller mappings, [as suggested by the Arch Linux wiki](https://wiki.archlinux.org/title/Gamepad#Using_hid-nintendo_with_SDL2_Games). To fix this I needed to create a registry entry at `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\winebus` and add a new DWORD called `DisableHidraw` with a value of `1`. I found this thanks to #4775 ([this comment](https://github.com/ValveSoftware/Proton/issues/4775#issuecomment-829906423)).

**Comment by kisak-valve** [comment] 2022-03-12 13:55
Hello @nezd5553, without providing a known working reference point, this issue can't be investigated as a new regression, and it looks like a duplicate of #4775. Feel free to add your experience to the older issue report.

Closing in favor of the older issue report.

**Closed as completed by kisak-valve** 2022-03-12 13:55 UTC
