### ISSUE TITLE
Helldivers 2 kernel32.dll.heapsummary crash to desktop

### ISSUE THREAD

**Issue by pr0nstache** [ValveSoftware/Proton#8106] opened 2024-09-18 21:38 UTC
# Compatibility Report
- Name of the game with compatibility issues: Helldivers 2
- Steam AppID of the game: 553850

## System Information
- GPU: <AMD RX 6650 XT>
- Video driver version: <Mesa 24.2.1-1.fc40>
- Kernel version: <6.10.7-200.fsync.fc40.x86_64>
- Link to full system information report as [Gist](https://gist.github.com/pr0nstache/18a3892d46fa12c4405292918260ffa2)
- Proton version: Multiple: 9.0-2 / Experimental / GE-Proton9-13 / GE-Proton8-26

## I confirm:
- [X ] that I haven't found an existing compatibility report for this game.
- [X ] that I have checked whether there are updates for my system available.

[steam-553850.log](https://github.com/user-attachments/files/17050517/steam-553850.log)

## Symptoms 
There is a constant reproducible crash to desktop when launching the game.  Using various launch options the game always exits to destop reliably between immediately to 20 minutes from this error: `wine: Call from 00006FFFFFC1CF07 to unimplemented function KERNEL32.dll.HeapSummary, aborting`

## Reproduction
This CTD happens when using no launch options, with simple launch options like gamemoderun and mangohud, it happens with X11 session on gnome and plasma, it happens on wayland with gnome and plasma, and it happens when using gamescope launch options.

This is a new error when running the game with proton, since the latest patch as of yesterday, Sept 17th, patch 1.001.001

**Comment by kisak-valve** [comment] 2024-09-18 21:48
Hello @pr0nstache, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/7486#issuecomment-2359463646.

**Closed as not planned by kisak-valve** 2024-09-18 21:48 UTC

**Comment by MarcusSell** [comment] 2026-02-27 02:46
This issue is still actively occurring on Proton Experimental 10.0-20260210 (Feb 2026) with NVIDIA driver 590.48.01 (RTX 5090), Ubuntu 24.04, kernel 6.17.

The crash is 100% reproducible under heap pressure — specifically Helldivers 2 Eradicate missions on Terminid maps, where hundreds of enemy spawns cause the game to call `HeapSummary` for heap diagnostics.

Journal logs showing 4 consecutive crashes in one session:

```
Feb 25 22:54:17 wine: Call from 00006FFFFFC0D157 to unimplemented function KERNEL32.dll.HeapSummary, aborting
Feb 25 22:55:22 wine: Call from 00006FFFFFC0D157 to unimplemented function KERNEL32.dll.HeapSummary, aborting
Feb 25 22:56:54 wine: Call from 00006FFFFFC0D157 to unimplemented function KERNEL32.dll.HeapSummary, aborting
Feb 25 22:58:23 wine: Call from 00006FFFFFC0D157 to unimplemented function KERNEL32.dll.HeapSummary, aborting
```

The game runs fine for 60-75 minutes on other mission types, then crashes deterministically the moment heap pressure peaks on Eradicate Terminid. Relaunching into the same in-progress mission crashes within ~1 minute because the enemy count is already at maximum.

A trivial 6-byte binary patch to `kernelbase.dll` (`mov eax, 1; ret` replacing the stub) resolves this completely. The proper implementation exists as Wine MR !8237 (https://gitlab.winehq.org/wine/wine/-/merge_requests/8237) but has been unmerged since June 2025.
