### ISSUE TITLE
Fall Guys: Ultimate Knockout

### ISSUE THREAD

**Issue by JonathanCarpenter** [ValveSoftware/Proton#4516] opened 2020-12-30 23:31 UTC
Steam Play - Ubuntu 20.04.1 LTS (Focal Fossa). 
Fall Guys: Ultimate Knockout 

When the game starts I am only able to play the game for the first few seconds when I get the message "You have been disconnected".

**Comment by kisak-valve** [comment] 2020-12-30 23:43
Duplicate of https://github.com/ValveSoftware/Proton/issues/4123#issuecomment-752773123. Please do not intentionally open duplicate issue reports.

**Closed as completed by kisak-valve** 2020-12-30 23:43 UTC
