### ISSUE TITLE
Darksiders 2 Deathinitive Edition freezes after selecting to start a new game (388410)

### ISSUE THREAD

**Issue by Cuddlypuff** [ValveSoftware/Proton#736] opened 2018-08-27 03:29 UTC
sys info: https://gist.github.com/Cuddlypuff/a518019d119623d9a1b7552e284c1f6d
after logos, autosave warning, and choosing a new game slot, game freezes on what looks like a loading screen.

Nothing special in steam's terminal window, nothing obvious in the game's log but I'll add it here in case it helps:
https://gist.github.com/Cuddlypuff/aff55debb4d4d51192272006e32f4e15

**Comment by ziabice** [comment] 2018-08-27 10:16
this is a duplicate of: [https://github.com/ValveSoftware/Proton/issues/325](https://github.com/ValveSoftware/Proton/issues/325)

That, said you can run the game using some launch options (check the linked issue).

**Comment by kisak-valve** [comment] 2018-08-27 14:37
Closing in favor of #325.

**Closed as completed by kisak-valve** 2018-08-27 14:37 UTC
