### ISSUE TITLE
Fallout 4 regression with 4.11-6

### ISSUE THREAD

**Issue by namarrgon** [ValveSoftware/Proton#3090] opened 2019-09-27 11:03 UTC
# Compatibility Report
- Name of the game with compatibility issues: Fallout 4
- Steam AppID of the game: 377160

## System Information
- GPU: RX580
- Driver/LLVM version: mesa 19.2.0-1; llvm 8.0.1-3
- Kernel version: 5.3.1-arch1-1-ARCH
- Link to full system information report: [systemreport](https://gist.github.com/namarrgon/d40a6da02bf852fd827203547d69b588)
- Proton version: 4.11-6

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

[proton log](https://gist.github.com/namarrgon/510ee6cebb1bf67565ddf2860063803e)

## Symptoms 
A dark overlay is covering the screen except for a slim line at the top of the screen.
This is most likely a regression with dxvk v1.4. https://github.com/doitsujin/dxvk/issues/872 describes the same issue but in my case the overlay covers the majority of the screen.

![2019-09-27-125333_1920x1200_scrot](https://user-images.githubusercontent.com/3209906/65764841-d5979a00-e126-11e9-8bb9-479819588029.png)

camera moved up by a few pixels (attention to top of the picture):
![2019-09-27-125334_1920x1200_scrot](https://user-images.githubusercontent.com/3209906/65764842-d5979a00-e126-11e9-896a-2a6697f99a17.png)

EDIT: This was not an issue with any previous proton versions until 4.11-6; 4.11-5 didn't exhibit this and downgrading to any other version "fixes" it.

## Reproduction
The overlay is (dis)appearing when rotating the camera and is most noticeable indoors, at night, close to bright dynamic lights like lanterns/lamps.

**Comment by doitsujin** [comment] 2019-09-27 11:57
Can you post a savegame where this issue occurs, as well as your in-game settings? I *still* cannot reproduce this problem.

**Comment by namarrgon** [comment] 2019-09-27 12:03
This should be the scene that i took the above screenshot from:
https://paste.xinu.at/Zjg/ (~16MB)
But this bug is reproducible pretty much everywhere in my case. The ingame settings don't matter, i get them on the lowest possible settings, on the highest possible settings and everywhere in between.

**Comment by doitsujin** [comment] 2019-09-27 12:11
Still cannot reproduce on my RX 480. Any chance you're using mods that might break it?

**Comment by namarrgon** [comment] 2019-09-27 12:13
No, this is all vanilla. All DLC included but the game is unmodified.

**Comment by doitsujin** [comment] 2019-09-27 12:16
Hm, I don't have any of the DLCs. Wonder if one of those is causing the issue.

**Comment by namarrgon** [comment] 2019-09-27 12:27
Uninstalling the DLC didn't change the result.

**Comment by kisak-valve** [comment] 2019-09-27 13:29
Hello @namarrgon, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/308#issuecomment-535939265.

**Closed as completed by kisak-valve** 2019-09-27 13:29 UTC
