### ISSUE TITLE
GTAV launcher doesn't end/game does not start

### ISSUE THREAD

**Issue by rkunschke** [ValveSoftware/Proton#375] opened 2018-08-24 10:09 UTC
If i use the online mode the launcher says i am logged in but the launcher does not close. After some time time everything crashes. 
In offline mode the launcher does not crash but it does not end too. The GTAV .exe launches but it does nothing.
No errors just nothing.

**Comment by arzardk** [comment] 2018-08-24 10:19
You need to attach game log file and your system specs via [github gist](https://gist.github.com) to this issue. You can obtain log file if you running Proton with user settings, which you can find in your /home directory. Path to this folder is something like this `/home/arzardk/.steam/steam/steamapps/common/Proton 3.7`. In this folder you find file called `user_settings.example.py` or something similar. Just rename it to `user_settings.py` and run your game again. You can find log file in your /home directory after that. For system specs just copy-paste your system information from Steam to github gist and paste link here.

**Comment by rkunschke** [comment] 2018-08-24 10:30
Okay thnk you:
[https://gist.github.com/rkunschke/7dd1b363bd572d8cdb50b53090e16181](https://gist.github.com/rkunschke/7dd1b363bd572d8cdb50b53090e16181)
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3700 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Linux 4.x (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.18.4-zen1-1-zen
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12001000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 980 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.54
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x17c8
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 6270 x 2160
    Primary Display Size: 20.51" x 11.54" (23.50" diag)
                                            52.1cm x 29.3cm (59.7cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: 20K2

Memory:
    RAM:  11954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  C
    Total Hard Disk Space Available:  225582 Mb
    Largest Free Hard Disk Block:  14577 Mb
    VR Headset: None detected

Recent Failure Reports:

**Comment by vanyasem** [comment] 2018-08-24 10:38
Install corefonts using winetricks to workaround that issue

**Comment by vanyasem** [comment] 2018-08-24 10:39
Seems like a duplicate of https://github.com/ValveSoftware/Proton/issues/37

**Comment by rkunschke** [comment] 2018-08-24 10:41
Yes it is as you say so. Will installing something with winetricks change it for proton? I don't even have installed wine

**Comment by kisak-valve** [comment] 2018-08-24 14:11
Hello @rkunschke, we'll be using one issue report per unofficially supported game title, so I've gone ahead and transferred this to https://github.com/ValveSoftware/Proton/issues/37#issuecomment-415770558.

**Closed as completed by kisak-valve** 2018-08-24 14:11 UTC
