### ISSUE TITLE
Assetto Corsa Competizione (Early Access)

### ISSUE THREAD

**Issue by leillo1975** [ValveSoftware/Proton#1421] opened 2018-09-12 21:18 UTC
# Whitelist Request
- Name of the game to be whitelisted:Assetto Corsa Competizione
- Steam AppID of the game: 805550

## System Information
- GPU: NVIDIA GTX 1050Ti
- Driver/LLVM version: nvidia 396.54
- Kernel version:  4.15
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/leillo1975/bd9c738c5d2aae6b44ef0569c2c218c7
- Proton version:3.7.6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [x] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [x] Although I consider the gaming experience equal to Windows there are
      remaining issues: Maybe the game is a bit slower than in Windows, but it is normal with the performance of games with Proton

**Comment by kisak-valve** [comment] 2018-09-12 23:15
Closing as a duplicate of #1420.

**Closed as completed by kisak-valve** 2018-09-12 23:15 UTC
