### ISSUE TITLE
[Whitelist] Duck Tales Remestered (237630)

### ISSUE THREAD

**Issue by Zero86Sk** [ValveSoftware/Proton#597] opened 2018-08-25 22:31 UTC
Game runs flawlesly

[My Steam Information](https://gist.github.com/Zero86Sk/d629f657c1ae861c36657cdf238a7765)

**Comment by ghost** [comment] 2018-08-28 04:57
Seems to work great for me too.

[Hardware Info](https://gist.github.com/QuirkyTechie/26be9007c0dbe0f932424980e19b4b9f)

**Comment by kisak-valve** [comment] 2018-08-28 12:52
[Whitelist] Ducktales: Remastered (237630)

Issue transferred from https://github.com/ValveSoftware/Proton/issues/803.
@jstuder-gh posted on 2018-08-28T03:52:27:

I'd like to recommend [Ducktales: Remastered](https://store.steampowered.com/app/237630/DuckTales_Remastered/) as a possible candidate for whitelisting. It worked flawlessly for me.

Played the game through to completion with a wired XBox 360 controller. Rumble, Achievements, Steam Cloud sync all worked for me. I did not notice any graphical glitches or slowdown.

The only issue I encountered was https://github.com/ValveSoftware/Proton/issues/287 but that was only a mild annoyance.

[Hardware Info](https://gist.github.com/jstuder-gh/f9b766c94e5e93c70528d2d27982a86f)
***
@QuirkyTechie commented on 2018-08-28T04:46:04

Duplicate of #597

**Comment by shaphanpena1** [comment] 2018-08-28 19:59
White list request. DuckTales remastered works on steamos. Steam controller works. My system specs are: Intel core i3 4170, 8gb ram, gigabyte 2gb ddr5 gt 1030

**Comment by jonlap** [comment] 2018-09-15 14:08
# Whitelist Request
- Name of the game to be whitelisted: DuckTales: Remastered
- Steam AppID of the game: 237630

## System Information
- GPU: RX480
- Driver/LLVM version: Mesa 18.2/6.0.1
- Kernel version: 4.18.7
- Link to full system information report as [Gist](https://gist.github.com/): [System info](https://gist.github.com/skry/1c6460bd766638632fcb7e3d63a446e7)
- Proton version: 3.7-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options)
      are necessary to run the game.
- [x] that no workarounds other than the mentioned ones are necessary.

## Issues
- [x] I haven't experienced any issues.
- [x] There are no issues left open for this game.
- [ ] Although I consider the gaming experience equal to Windows there are
      remaining issues:

## Notes
Everything works without issues, including Xbox 360 controller, and performance is perfect. Finished tutorial and two levels, and tried everything hub offers, all OK.

**Comment by hzulla** [comment] 2018-11-23 09:42
There is no controller rumble effects with my (cheap) gamepad (0079:0006 DragonRise Inc. PC TWIN SHOCK Gamepad). I can confirm that the gamepad's fx work with [`fftest`](http://manpages.ubuntu.com/manpages/cosmic/man1/fftest.1.html).

**Comment by hzulla** [comment] 2018-11-27 15:23
Can confirm, this game works surprisingly well.

**Comment by kisak-valve** [comment] 2019-01-01 13:17
DuckTales: Remastered crashes during final cutscene

Issue transferred from https://github.com/ValveSoftware/Proton/issues/2173.
@drcouzelis posted on 2019-01-01T05:27:57:

# Compatibility Report
- Name of the game with compatibility issues: DuckTales: Remastered
- Steam AppID of the game: 237630

## System Information
- GPU: RX 560
- Driver/LLVM version: Mesa 18.3.1
- Kernel version: 4.20
- Link to full system information report as [Gist](https://gist.github.com/): [Gist](https://gist.github.com/drcouzelis/69cfe1457c9520f2dae862fd1ca29295)
- Proton version: 3.16-6 Beta

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

[steam-237630.log](https://github.com/ValveSoftware/Proton/files/2719128/steam-237630.log)
[steam-bash.log](https://github.com/ValveSoftware/Proton/files/2719129/steam-bash.log)

## Symptoms
Upon beating the final boss (Dracula Duck) and escaping from the volcano, the final cutscene will begin (Scrooge McDuck escaping in a helicopter). After a few seconds, the game will close.

## Reproduction
I have experienced this crash 3 out of 3 times when completing the game and attempting to view the final cutscene.
***
@drcouzelis commented on 2019-01-01T05:40:38

This is the one and only issue I experienced in playing DuckTales: Remastered on Linux. Everything else has been perfectly functional, no bugs, 100% just "click and play".

**Comment by ugly95** [comment] 2019-06-16 17:23
I was able to play through the game to completion.  This game should be whitelisted.  It works flawlessly.

The game does have a major bug at the end of the game as reported by @drcouzelis.  On my first playthough, I did not have any crashes.  I was able to beat the final boss, watch the cutscene and then beat the final scene.  Even on multiple (failed) attempts, the game did not crash.  But on a second playthough I am unable to complete the game because the game will crash at some point during the final boss battle, or the end sequence.

However, this is not a Linux/Proton bug.  This is a longstanding issue with the game.  [Fighting Dracula crashes the game - every time (Steam Discussion)](https://steamcommunity.com/app/237630/discussions/0/864976115482880816/)

[My Steam Info](https://gist.github.com/ugly95/d75ee8378c70be12a334a784dead74c2)

[Proton Log](https://gist.github.com/ugly95/b5c4b318f1820cc564608546e5b62326)

**Comment by drcouzelis** [comment] 2019-06-16 19:58
@ugly95 Oh wow, I had no idea the bug was THAT widespread and longstanding!

I agree, everything else in the game works flawlessly for me.

**Comment by kisak-valve** [comment] 2019-07-31 16:49
This game was found in the 2019-07-31 whitelist update.

If you encounter an issue with this game, please search the open issues for 237630, and report any issues encountered with this game in separate issue reports, one issue per issue report.

**Closed as completed by kisak-valve** 2019-07-31 16:49 UTC
Labels: Whitelist Request
