### ISSUE TITLE
Fullscreen with Proton Experimental or 7.0-1 makes the window stretching wildly

### ISSUE THREAD

**Issue by DarkSwan86** [ValveSoftware/Proton#5666] opened 2022-03-11 21:15 UTC
# Compatibility Report

-Dead Space
-Mortal Kombat 9
-Bayonetta
-DOOM (2016)

## System Information
Output of INXI command

System:
  Host: thinkpadt470 Kernel: 5.15.25-1-MANJARO x86_64 bits: 64 compiler: gcc
    v: 11.2.0 Desktop: KDE Plasma 5.24.2 tk: Qt 5.15.2 wm: kwin_wayland
    dm: SDDM Distro: Manjaro Linux base: Arch Linux
CPU:
  Info: dual core model: Intel Core i5-7300U bits: 64 type: MT MCP
    arch: Amber/Kaby Lake note: check rev: 9 cache: L1: 128 KiB L2: 512 KiB
    L3: 3 MiB
  Speed (MHz): avg: 900 min/max: 400/3500 cores: 1: 900 2: 900 3: 900
    4: 900 bogomips: 21607
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3
Graphics:
  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel
    ports: active: eDP-1 empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2 bus-ID: 00:02.0
    chip-ID: 8086:5916
  Device-2: Acer Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:3
    chip-ID: 5986:111c
  Display: wayland server: X.org v: 1.21.1.3 with: Xwayland v: 22.1.0
    compositor: kwin_wayland driver: X: loaded: modesetting
    alternate: fbdev,vesa gpu: i915 display-ID: 0
  Monitor-1: eDP-1 res: 1366x768 size: N/A
  OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 21.3.7
    direct render: Yes

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.

Attaching logs, all starting fullscreen in native laptop resolution
[Bayonetta-steam-460790.log](https://github.com/ValveSoftware/Proton/files/8235762/Bayonetta-steam-460790.log)
[DeadSpace-steam-17470.log](https://github.com/ValveSoftware/Proton/files/8235764/DeadSpace-steam-17470.log)
[MortalKombatKompleteEdition-steam-237110.log](https://github.com/ValveSoftware/Proton/files/8235765/MortalKombatKompleteEdition-steam-237110.log)

## Symptoms 

My laptop fullscreen resolution is 1366x768, if i try Proton Experimental (updated as 11 March 2022) on all these games the fullscreen window stretch very fast but if i use a fullscreen resolution slightly smaller (1280x720) i have no such problem. 

Proton 7.0-1 has the same problem. 

Using Proton 6.3-8 doesn't have this problem with fullscreen and native resolution.

## Reproduction
Start any of these games and watch the fullscreen windows stretching.

**Comment by alasky17** [comment] 2022-03-11 21:34
@DarkSwan86 Could you upload a screenshot or video of the problem?

**Comment by DarkSwan86** [comment] 2022-03-12 00:36
This is a capture of Dead Space when launched fullscreen native resolution.

https://user-images.githubusercontent.com/24975273/157995697-5dfddd78-c3f5-4fc8-ad54-5b2e08eee2e2.mp4

**Comment by alasky17** [comment] 2022-03-15 20:56
@DarkSwan86 Thank you! This seems to be a wayland specific regression.  We'll look into it :)

**Comment by DarkSwan86** [comment] 2022-04-18 17:58
@alasky17 i'm happy to report that all games except Doom (2016) are fixed with Proton Experimental from April 18th! 

Doom shows a lot of flicker but goes ingame fullscreen. I'm using the vulkan render.

**Comment by alasky17** [comment] 2022-04-25 18:19
@DarkSwan86 Thank you for the update!  Unfortunately, it looks like the fix didn't get in stable -2, so I'll wait to close the issue until it is fixed in stable.  

I took a look at DOOM 2016 and I see the flicker that you are talking about, but I saw the same behavior with 6.3-8, so it looks like this is not a regression, just a Wayland problem :(

**Comment by DarkSwan86** [comment] 2022-09-16 12:53
Hi, i've recently tested on my laptop and now it works perfectly with the latest experimental and stable. Thanks!

**Closed as completed** 2022-09-16 12:54 UTC
Labels: Regression
