### ISSUE TITLE
Warframe fails on launch, launcher is not present.

### ISSUE THREAD

**Issue by nerd7473** [ValveSoftware/Proton#1406] opened 2018-09-11 22:23 UTC
# Compatibility Report
- Name of the game with compatibility issues:
- Steam AppID of the game:

## System Information
- GPU: 
- Driver/LLVM version: 
- Kernel version: 
- Link to full system information report as [Gist](https://gist.github.com/):
- Proton version:

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

**Comment by kisak-valve** [comment] 2018-09-11 22:25
Closing as a duplicate of #167.

**Closed as completed by kisak-valve** 2018-09-11 22:25 UTC
