### ISSUE TITLE
Blades of Time (208670) fails to launch with Proton 4.2-1

### ISSUE THREAD

**Issue by louisvd** [ValveSoftware/Proton#2470] opened 2019-03-28 21:45 UTC
# Compatibility Report
- Name of the game with compatibility issues: Blades of Time
- Steam AppID of the game:  208670

## System Information
- GPU: GeForce GTS 450
- Driver/LLVM version: NVIDIA 390.116
- Kernel version: 5.0.3-200.fc29.x86_64
- Link to full system information report as [Gist](https://gist.github.com/):  https://gist.github.com/louisvd/697b1909c65e95690c17229ddeed55e0
- Proton version: 4.2-1

## I confirm:
- [x ] that I haven't found an existing compatibility report for this game.
- [x ] that I have checked whether there are updates for my system available.

NO LOG is generated.  Even running directly from the command line generates none.

## Symptoms 
Upon clicking "Play", the grey window pops up stating "Preparing to Launch Blades of Time".  This disappears, and nothing else happens.

If I change to Proton 3.16-4 then the game launches successfully.

## Reproduction
Consistently.  Restarting Steam makes no difference.

**Comment by kisak-valve** [comment] 2019-03-28 21:52
Closing due to poor quality. If you fill out the template, give me a ping and I can re-open.

**Comment by louisvd** [comment] 2019-03-28 22:09
I ran "steam" from the command line, and the attached log was produced.

[BladesOfTime.log](https://github.com/ValveSoftware/Proton/files/3020298/BladesOfTime.log)

[assert_20190329000235_25.dmp.gz](https://github.com/ValveSoftware/Proton/files/3020304/assert_20190329000235_25.dmp.gz)

**Comment by kisak-valve** [comment] 2019-03-28 22:11
Hello @louisvd, please go to Steam -> Library dropdown -> Tools and install Proton 4.2 from the list. (Making this a duplicate of #2459)

**Comment by louisvd** [comment] 2019-03-28 22:40
Thank you ... I thought it installed the needed Proton files automatically.  It launches now.

**Comment by kisak-valve** [comment] 2019-03-28 22:41
Glad to hear, closing as a duplicate of #2459.

**Closed as completed by kisak-valve** 2019-03-28 22:41 UTC
