### ISSUE TITLE
Controller support in Proton 7.0-1

### ISSUE THREAD

**Issue by massatt212** [ValveSoftware/Proton#5578] opened 2022-02-16 13:24 UTC
New proton 7.0-1 has no controller support.
PS4 Controller
PS3 Controller
X-input Controller

No controller is working for me, idk if others having the same problem.

**Comment by kallestrop** [comment] 2022-02-16 13:37
~~I have no force feedback effects with my Logitech G29 wheel. In previous Proton 6.3-8 ffb was functional.~~

After rebooting the system and deleting the old prefix, ffb is working again. Game was Euro Truck Simulator 2 (227300)

**Comment by aeikum** [comment] 2022-02-16 14:02
Please list some specific games that are affected.

**Comment by massatt212** [comment] 2022-02-16 14:16
So far all my names, Mortal Kombat 11, injustice 2, ultimate marvel vs capcom 3, dirt5, grid 2019, dragon ball fighterz, jump force, titanfall, tekken7, street fighter 5, controller, fighting layer rx, killer instinct, marvel vs capcom.infinite, nba 2k22 I would say my entire library.

**Comment by massatt212** [comment] 2022-02-16 14:27
Ok so 7.0-1 seems to be broken with game scope, was working on proton 6 and experimental, after disabling gamescope games seem to be working.



So I entered -e and the controller work with gamescope now, sry for the time wasting.

**Comment by aeikum** [comment] 2022-02-16 14:31
What do you mean by "entered -e"?

**Comment by massatt212** [comment] 2022-02-16 14:41
gamescope -U -f -e -h 2160 -r 60 -- %command%

gamescope commands

**Comment by aeikum** [comment] 2022-02-16 14:44
Got it, thanks. Closing as not a bug.

**Closed as completed by aeikum** 2022-02-16 14:44 UTC

**Comment by rbernon** [comment] 2022-02-16 15:06
Looks like it's actually an issue, but more something that could be easier to fix from gamescope side, and I opened https://github.com/Plagman/gamescope/issues/416 to track this. In the meantime using -e should hopefully fix most issues.
