### ISSUE TITLE
Alt-Tab switching to fullscreen game sometimes restricts mouse movement

### ISSUE THREAD

**Issue by joshua-stone** [ValveSoftware/Proton#579] opened 2018-08-25 18:30 UTC
The following titles I've played have had excellent compatibility so far:

* [Crysis 2 - Maximum Edition](https://store.steampowered.com/app/108800/Crysis_2__Maximum_Edition/)
* [Deus Ex: Human Revolution](https://store.steampowered.com/app/238010/Deus_Ex_Human_Revolution__Directors_Cut/)

There is however a bug that I've encountered where if I press Alt-Tab to switch back and forth, sometimes the mouse is restricted to about 90° of rotation. This could go away if I press a specific key that triggers an action, but would obviously pose a problem in the middle of an in-game battle and break immersion.

**Hardware/software info:**

OS: Fedora 28 64-bit
CPU: AMD Ryzen 5 1600
GPU: Radeon RX 580
Kernel: 4.17.9-200.fc28.x86_64
X Window Manager: GNOME Shell 3.28.1
Steam Runtime Version: steam-runtime-beta-release_2018-06-14
Driver: X.Org Radeon RX 580 Series (POLARIS10 / DRM 3.25.0 / 4.17.9-200.fc28.x86_64, LLVM 6.0.0)
Mesa version: 18.0.5

**Comment by KayKay91** [comment] 2018-08-25 20:30
I can confirm this. This happens in every game, it's really troublesome in FPS or strategy games.

**Comment by edn9** [comment] 2018-08-26 02:45
Happen to me too in Dark Souls 2 and Dead Space.

**Comment by d10sfan** [comment] 2018-08-26 03:19
This happened to me in Witcher 3

**Comment by Giant3** [comment] 2019-08-25 09:44
Can confirm for Hitman 2

**Comment by at46** [comment] 2019-08-25 11:59
I've the same problem with Deus Ex: Human Revolution and also Batman Arkham Origins and Batman Arkham Asylum GOTY are affected. Pressing an action key does not solve it. I haven't found any solution or workaround and always have to restart the game.

**Comment by ryao** [comment] 2019-08-26 07:33
I hit a similar issue in Sword Art Online: Fatal Bullet. It is #1178.

**Comment by Kiltenth** [comment] 2019-08-30 00:00
Having the exact same issue in World of Warships. Opening the scoreboard resets the cursor position and after closing it, it takes that view as a reference point and does the 90 degree thing again, midpoint being the point where you closed the scoreboard.

E : Apparently pressing Ctrl during a match to enable in-game mouse cursor also acts the same as opening scoreboard.

E.2 : For those who are trying to recreate the same problem, a quick alt-tab and back to the game don't always break it. Alt-tabbing and using Google Chrome to browse internet for few seconds seems to trigger it almost always.

E.3 : Ok, so I thought of a way to maybe prevent this from happening, but I'm not sure if It works. I also don't have the knowledge to program something like this. But my idea is : Can we write something like a macro to let's say choose a reference point on screen, and whenever mouse moves, it makes the cursor to snap back to that point? And then we can make a toggle on/off button for that macro so whenever we are alt-tabbed we can toggle it off. This doesn't fix the issue tho, it might just be a way around. I would like to try this if this is possible but as I said I don't have enough knowledge program something like this.

**Comment by Kiltenth** [comment] 2019-08-30 21:35
Just confirmed, same thing also happens with Just Cause 4, exact same thing.

E : I just came up with this idea but I don't know how mouse pointer input behaves at screen borders. Let's say cursor is at right border of screen. Does OS still get right cursor movement input? Or does it ignore like "cursor is at right border, no right movement input needed"? If It does ignore, maybe we can make a program to force it to keep getting inputs. If It doesn't ignore, this idea will also not work then.

**Comment by ryao** [comment] 2019-09-06 04:04
A Hat In Time is affected. I just noticed on proton 4.11-3.

**Comment by at46** [comment] 2019-12-26 17:12
Proton 4.11-4 brought `More improvements to mouse capture and window focus loss behavior.` and 4.11-10 added `Major improvements to mouse handling.`. I didn't had problems with mouse focus since 4.11-4. Maybe someone who previously had the problem can confirm that the bug still occurs or that it is also fixed for him?

**Comment by kisak-valve** [comment] 2020-01-31 13:44
Closing pending feedback.

**Closed as completed by kisak-valve** 2020-01-31 13:44 UTC
