### ISSUE TITLE
Max Payne - no audio

### ISSUE THREAD

**Issue by FiXIDeA** [ValveSoftware/Proton#252] opened 2018-08-23 11:03 UTC
Max Payne starts without sound

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3800 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 18.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-32-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 396.51
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1187
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.08" x 11.42" (23.07" diag)
                                            51.0cm x 29.0cm (58.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  15947 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Total Hard Disk Space Available:  224317 Mb
    Largest Free Hard Disk Block:  18805 Mb
    VR Headset: None detected

**Comment by ghost** [comment] 2018-08-23 11:52
Assuming you're talking about the original 2001 Max Payne there is a well known issue that it has problems with audio on versions of Windows from Vista and later. I'm going to assume these same issues have carried over to WINE\ Proton. 

Thankfully a user over on Steam made a fix for this problem which patches the sound files so they work properly in later versions of Windows. He also provides sound files which are already patched for download over [here](https://steamcommunity.com/sharedfiles/filedetails/?id=945164243). Hopefully these files will fix your issue.

**Side note**: It would appear the issue is caused by Max Payne using calls to the now deprecated DirectSound API. I'm not sure how WINE\ Proton handles DirectSound API calls, but you may be able to fix this issue by using [IndirectSound](http://www.indirectsound.com/).

**Comment by mirh** [comment] 2018-08-23 11:58
It should work [since ages](https://bugs.winehq.org/show_bug.cgi?id=21196). 
Is it fine with latest wine?

**Comment by rea987** [comment] 2018-08-23 12:45
I can confirm that lack of DirectSound causes no sound in Quake Live as well.

Edit: Latest QL update enabled DirectSound for the game, thus the game has sound now.

**Comment by vanyasem** [comment] 2018-08-23 13:15
`MaxPayne (RU)`, no sound as well

**Comment by vanyasem** [comment] 2018-08-23 15:15
I can confirm that using IndirectSound mentioned in https://github.com/ValveSoftware/Proton/issues/252#issuecomment-415387882 fixes the issue

**Comment by mirh** [comment] 2018-08-23 15:26
Check #54 or #263

**Closed as completed** 2018-08-23 16:33 UTC

**Comment by Houtworm** [comment] 2018-08-25 12:42
For me the game, including sound works right out of the box on Arch

**Comment by FiXIDeA** [comment] 2018-08-25 14:42
Latest proton update fixes sound problem and some more...
