### ISSUE TITLE
Update to Wine 3.18 or 3.19

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/Proton#1854] opened 2018-10-30 10:14 UTC
# Feature Request

## I confirm:
- [x] that I haven't found another request for this feature.
- [x] that I have checked whether there are updates for my system available that
      contain this feature already.

## Description 

I wish to make you by to make a quick migration on wine 3.19 because there is too much regression on the version 3.16 which works really bad for proof most of the games which works in 3.7-8 does not work any more or badly in 3.16!

If I make this request is that I have a certain visibility of what I said having tested a lot of games steam around 80 in 3.7 I did the same test in 3.16 but I had more often problems and regressions too common on 3.16 even worse I have not had any evolution on games that was not working very well or not at all it is still the case in 3.16 so this version does not bring any real improvement on many games tested that it is at the level of performance than compatibility level is really not great.
That's why I make this request in order to aim higher and improve proton with what it does best!

## Justification [optional] 

The version of wine 3.19 brings a more extensive support of the net framwork which can help the compatibility of the old games.

 What's new in this release:

    Support for file I/O completion modes.
    WaitOnAddress synchronization primitives.
    Better support for 32-bit .NET binaries on 64-bit.
    Improved recovery on broken RPC connection.
    Various bug fixes.
in : https://www.winehq.org/news/2018102601

## Risks [optional]

We can not speak of risk strictly speaking what I suggest is a beta version of proton in wine 3.19 while allowing access version 3.7-8 and 3.16-3 to make a comparison but I'm pretty sure that many 3.16 wine problems are fixed in version 3.19

## References [optional] 

Honestly it is enough just to see my last report obliged to stay in 3.7-8 because version 3.16 works badly!

**Comment by aeikum** [comment] 2018-10-30 12:14
Can you list some games that were working before but are no longer?

**Comment by liberodark** [comment] 2018-10-30 13:50
> Can you list some games that were working before but are no longer?

Yes : 
Shiness: The Lightning Kingdom https://github.com/ValveSoftware/Proton/issues/1842
Kingdoms of Amalur: Reckoning https://github.com/ValveSoftware/Proton/issues/783

I'm going to extend the list but I do not remember all my notes at home and I'm at work !
but there is another problem more complicated tweaks some games we need small tweaks but proton applies only basic settings which also reduces the compatibility of some games!
And also the fact that I have Mesa and Nvidia so they are two opposite!
On the mesa 18.x test works better in general than nvidia 410.x.
But I think proton have to take a big step forward to apply tweaks easily something like lutris but more simple!

**Comment by aaronfranke** [comment] 2018-10-30 18:44
And can you confirm that those games work again in 3.19?

**Comment by liberodark** [comment] 2018-10-31 10:54
Yes for 3.18 in lutris have test somes  games work great i like play and use proton !
But lutris have tweaks... Proton no tweaks :(

**Comment by Dexter9313** [comment] 2018-10-31 12:09
You should test this by replacing wine within Proton, not using Lutris. Results between Proton tests and Lutris tests aren't comparable.

**Comment by liberodark** [comment] 2018-10-31 14:51
> You should test this by replacing wine within Proton, not using Lutris. Results between Proton tests and Lutris tests aren't comparable.

That's why I do not mention it in my request!
What I emphasize is a finding a significant regression in the games!
So for me it is essential to pass on a higher version which surely settled this kind of problem.

**Comment by aeikum** [comment] 2018-10-31 15:27
Yes, reporting regressions is useful, thank you.

Amalur's resolution handling seems buggy, but that problem was reported on 3.7, too. Can you be more specific about what is broken in 3.16?

I noticed the character textures in Shiness seem to be missing in 3.16. It uses DXVK for d3d11 so possibly it's a DXVK regression? Ping @doitsujin if you have a moment to look into this.

**Comment by liberodark** [comment] 2018-10-31 20:51
For my 1050ti in fresh install on manjaro 18 x64 nvidia driver 410.73 is not running, but on 3.7 game run !

**Comment by liberodark** [comment] 2018-10-31 23:15
Shiness: The Lightning Kingdom : 
Proton 3.7 :+1: 
[steam-366640.log](https://github.com/ValveSoftware/Proton/files/2537738/steam-366640.log)
<a href="https://i.imgur.com/4qU5nTx.png">
  <img src="https://i.imgur.com/4qU5nTx.png" />
</a>

Proton 3.16-4 :-1: 1: 
[steam-366640.log](https://github.com/ValveSoftware/Proton/files/2537755/steam-366640.log)
<a href="https://i.imgur.com/m76BI5t.png">
  <img src="https://imgur.com/m76BI5tl.png" />
</a>

**Comment by kisak-valve** [comment] 2018-10-31 23:25
Hello @liberodark, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and drag and drop the generated $HOME/steam-$APPID.log into the comment box.

**Comment by liberodark** [comment] 2018-11-01 08:36
Kingdoms of Amalur: Reckoning : 
[steam-102500.log](https://github.com/ValveSoftware/Proton/files/2537770/steam-102500.log)

**Comment by jomarocas** [comment] 2018-11-02 21:33
i need wine 3.19 for various game and a patch https://bugs.winehq.org/attachment.cgi?id=57994 that no be apply to none of beta version, only in staging

**Comment by aaronfranke** [comment] 2018-11-03 02:42
Realize that if Valve updated the Wine version that Proton uses constantly, there would be more fixes, but also more regressions and more versions to test. Valve can't update Wine constantly, for stability reasons. 

I wouldn't be surprised if Valve decides to use Wine LTS versions down the road (3.0.x and 4.0.x etc).

**Comment by liberodark** [comment] 2018-11-03 09:34
> Realize that if Valve updated the Wine version that Proton uses constantly, there would be more fixes, but also more regressions and more versions to test. Valve can't update Wine constantly, for stability reasons.
> 
> I wouldn't be surprised if Valve decides to use Wine LTS versions down the road (3.0.x and 4.0.x etc).

IS not LTS version : https://www.winehq.org/news/2018091401 is dev version !
And is Wine 3.0.3 the last stable version

**Comment by shrinivas17081997** [comment] 2018-11-05 10:44
Yeah wine staging 3.19 plays many old games.than proton 3.16 to avoid regression set different wine version for different games like playonlinux

**Comment by lucifertdark** [comment] 2018-11-05 13:19
> Yeah wine staging 3.19 plays many old games.than proton 3.16 to avoid regression set different wine version for different games like playonlinux

Not exactly an ideal solution, you could easily end up with 15-20 different version of Wine installed at once, that's a recipe for disaster.

**Comment by kisak-valve** [comment] 2018-11-05 15:16
Hi folks, so general requests to rebase wine is going to be a recurring topic. In general, this is going to happen when Proton devs are ready to do it and not in any particular cadence.

New issues and regressions in games need to be discussed on a per-game basis because there are many ways where similar symptoms can come from completely unrelated issues. I can tag those games with the Regression label if I get the following info:
- Known good proton version
- Regressed proton version
- Proton log of the regression

Short posts with things like "this doesn't work anymore" simply isn't actionable by itself.

If there are known issues fixed with specific games that have gotten into vanilla wine, but not in Proton, feel free to open a pull request with references to the commits in vanilla wine and the individual fixes can be considered for backport into Proton on a per-case basis.

**Closed as completed by kisak-valve** 2018-11-05 15:16 UTC
