### ISSUE TITLE
Hard Reboot when playing Proton games

### ISSUE THREAD

**Issue by leggettc18** [ValveSoftware/Proton#3213] opened 2019-11-12 00:37 UTC
My system hard reboots when playing any Proton games. I know for sure it happens on Linux Kernel version 5.0.0 and 5.3.8, doesn't happen on Kernel 4.16, and only happens when playing games via Proton. My system is up to date and there are no firmware updates available either.

My System:
- OS: Fedora 31
- GPU: XFX AMD RX580 (8GB version)
- CPU: AMD Ryzen 3 1200 quad-core processor
- RAM: 15.6GiB DDR4
- PSU: Corsair CX750M

I've already gone through some logs, so far nothing I've posted elsewhere has any relevant errors that anyone has noticed, it just hard reboots out of nowhere while playing this games. I'm not sure where else to turn, but I figured this was a good place to start. If this belongs elsewhere, please feel free to point me in the right direction.

EDIT: I have also confirmed it does not happen with native vulkan games, such as the vulkan-beta for Feral's port of Shadow of Mordor.

**Comment by ghost** [comment] 2019-11-12 16:18
I don't know but Steam/Proton cannot hard reboot a computer. Something else is doing that.

You need to narrow down why your computer is hard rebooting. I don't think you will ever get a fix with a problem only happening for you without any log entries that are specifically for Steam/Proton. The only way is if a problem is fixed that no one knew was related.

**Comment by leggettc18** [comment] 2019-11-12 17:22
I understand that but I don't know where else to go. Considering this issue ONLY happens when playing games with Proton on Kernels 5.0.0-5.3.8 I figured the Proton Github might at least have some insight on what could be causing it. All I know is that my system crashes when I play games with Proton, and as far as I can tell from `journalctl` and using the `PROTON_LOG=1` flag, no errors are logged. The most I saw were some errors that appeared to be related to VR.

[This](https://pastebin.com/9pEixtud) is from PROTON_LOG when playing Bloodstained: Ritual of the Night via proton. I see a couple of errors related to gameoverlay, and when I posted this in a tech support thread on /r/linux_gaming, they didn't notice any problems. By all means if you see something they missed let me know.

Below is the last few lines of journalctl for one of the boots where a crash occured. I don't see any errors logged here either.

```Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamNetworking005 / Networking
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMHTTP_INTERFACE_VERSION002 / HTTP
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001 / UnifiedMessages
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamController005 / Controller
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMUGC_INTERFACE_VERSION009 / UGC
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMMUSIC_INTERFACE_VERSION001 / Music
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMHTMLSURFACE_INTERFACE_VERSION_003 / HTMLSurface
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMINVENTORY_INTERFACE_V001 / Inventory
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMVIDEO_INTERFACE_V001 / Video
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamUser019 / User
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamFriends015 / Friends
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamUtils008 / Utils
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamMatchMaking009 / Matchmaking
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamMatchMakingServers002 / MatchmakingServers
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMAPPS_INTERFACE_VERSION008 / Apps
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamNetworking005 / Networking
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMHTTP_INTERFACE_VERSION002 / HTTP
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001 / UnifiedMessages
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamController005 / Controller
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMUGC_INTERFACE_VERSION009 / UGC
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMMUSIC_INTERFACE_VERSION001 / Music
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMHTMLSURFACE_INTERFACE_VERSION_003 / HTMLSurface
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMINVENTORY_INTERFACE_V001 / Inventory
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): STEAMVIDEO_INTERFACE_V001 / Video
Nov 05 18:57:37 battlestation steam.desktop[2400]: Created OPUS PLC voice encoder
Nov 05 18:57:37 battlestation steam.desktop[2400]: warning: The VAD has been replaced by a hack pending a complete rewrite
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamUtils008 / Utils
Nov 05 18:57:37 battlestation steam.desktop[2400]: RecordSteamInterfaceCreation (PID 4986): SteamController005 / Controller
Nov 05 18:57:41 battlestation gnome-shell[2400]: Window manager warning: Window 0x5000001 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
Nov 05 18:57:41 battlestation gnome-shell[2400]: Window manager warning: Treating resize request of legacy application 0x5000001 as a fullscreen request
Nov 05 18:57:41 battlestation steam.desktop[2400]: Installing breakpad exception handler for appid(gameoverlayui)/version(20191105015040)
Nov 05 18:57:41 battlestation steam.desktop[2400]: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Nov 05 18:57:41 battlestation steam.desktop[2400]: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Nov 05 18:57:41 battlestation steam.desktop[2400]: [1105/185741.790406:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Nov 05 18:57:41 battlestation steam.desktop[2400]: Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Nov 05 18:57:41 battlestation steam.desktop[2400]: [1105/185741.954465:ERROR:frame_sink_video_capturer_impl.cc(197)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
Nov 05 18:57:42 battlestation steam.desktop[2400]: OnFocusWindowChanged to game window type: AppID 692850, 692850
Nov 05 18:57:42 battlestation steam.desktop[2400]: Controller 0 mapping uses xinput : false
Nov 05 18:57:42 battlestation steam.desktop[2400]: Loaded Config for Local Override Path for App ID 692850, Controller 0: /home/chris/.local/share/Steam//controller_base/empty.vdf
Nov 05 18:57:42 battlestation steam.desktop[2400]: Controller 0 mapping uses xinput : false
Nov 05 18:57:46 battlestation systemd[2231]: Starting Tracker metadata extractor...
Nov 05 18:57:46 battlestation systemd[2231]: Started Tracker metadata extractor.
Nov 05 18:57:56 battlestation systemd[2231]: tracker-extract.service: Succeeded.
Nov 05 18:58:04 battlestation systemd[2231]: Starting Tracker metadata extractor...
Nov 05 18:58:04 battlestation systemd[2231]: Started Tracker metadata extractor.
```

By all means if you can find anything here in these logs that other people haven't already found let me know. If there's any other logs I can get for you as well please let me know.

**Comment by OvermindDL1** [comment] 2019-11-12 17:29
If a hard reboot is happening it is almost always either a hardware fault or a driver fault (the rest of the time is exceptionally rarely a kernel bug), userland programs can't cause it, and proton is entirely userland.

You could try checking the kernel logs to get anything recorded out, or use another computer and hook a kernel debugger to potentially see where the fault happens (assuming not a hardware fault).

**Comment by leggettc18** [comment] 2019-11-12 17:36
I have my doubts about it being a hardware fault, especially since it DOES work fine on older kernels. However I think I recall checking the kernel logs earlier and was not able to find anything. I'll check again though.

**Comment by leggettc18** [comment] 2019-11-12 23:43
[Pastebin of Kernel Logs](https://pastebin.com/0fdX6ejK)

Fedora 31 had and update available to kernel 5.3.9, but issue was not resolved, this boot is after rebooting from installing the updated kernel, immediately started Steam and ran Bloodstained, and it crashed less than a minute into gameplay. I then rebooted and got these logs from `journalctl -k -b -1`.

**Comment by OvermindDL1** [comment] 2019-11-13 00:07
Kernel didn't report anything so I'd be instantly leaning to faulty drivers or hardware, hard to test, but sadly not even remotely uncommon...

**Comment by leggettc18** [comment] 2019-11-13 01:01
I seriously doubt its hardware, since this works fine with older versions of the linux kernel, I guess it COULD be drivers, but its still weird that it only happens with Proton. Should I file a bug at AMD's bug tracker or is this pretty much hopeless given that there's no errors logged whatsoever?

**Comment by kisak-valve** [comment] 2019-11-13 01:12
Hello @leggettc18, because you have a known working and broken reference points, you could try bisecting the kernel to reduce the scope of the issue.

**Comment by leggettc18** [comment] 2019-11-13 01:24
I suppose its worth a shot, but I don't have a lot of experience with this. Are you saying I would need to run `git bisect start [BAD] [GOOD]` on the kernel source code as per [this](https://www.kernel.org/doc/html/v4.15/admin-guide/bug-bisect.html), build the source, and then install that kernel?

**Comment by kisak-valve** [comment] 2019-11-13 01:49
That looks like a reasonable guide. If you encounter a failed build or strange results, you can always `git bisect skip` to try another split point between the known good and bad commit.

**Comment by ghost** [comment] 2019-11-13 14:42
On a side note, if it starts with a specific kernel and the kernel before that one is fine then you can put in a bug report (after seeing if one exists) at https://bugzilla.redhat.com/ and they will be able to help narrow it down more if not get it fixed should it be a kernel issue with Fedora.

I have Nvidia with Fedora 31 [and Ryzen] and haven't had a problem with the kernels as of late so it could be AMD GPU driver / kernel related.

**Comment by OvermindDL1** [comment] 2019-11-13 15:08
Just as a data point, I have an AMD RX 570, 4Gigs video RAM here (`Radeon RX 570 Series (POLARIS10, DRM 3.27.0, 5.0.0-31-generic, LLVM 8.0.0)`) with MESA 19.1.2 and kernel 5.0.0-31, and the CPU is a ryzen 8 core (16 ht) with 16Gigs system RAM on Kubuntu 19.10 and it's all running without issue (this is why I'm here though, if OP has an issue, then I don't want to experience it later either).

**Comment by leggettc18** [comment] 2019-11-14 00:00
@byte1024 I may look into doing this, but I think the issue is with the Linux kernel in general. I had the same issue on Elementary OS (based on Ubuntu 18.04 LTS) after installing the hardware enablement stack (which brings the kernel version up to 5.0.0) but not on the original kernel (4.16 I believe). So it at least is happening on both Fedora and Ubuntu kernels, not sure if any others, may try installing Manjaro and see if it happens there as well.

**Comment by ghost** [comment] 2019-11-15 13:46
> @byte1024 I may look into doing this, but I think the issue is with the Linux kernel in general. I had the same issue on Elementary OS (based on Ubuntu 18.04 LTS) after installing the hardware enablement stack (which brings the kernel version up to 5.0.0) but not on the original kernel (4.16 I believe). So it at least is happening on both Fedora and Ubuntu kernels, not sure if any others, may try installing Manjaro and see if it happens there as well.

It could be. You might need to then file a report with the Linux kernel devs (not distro kernel devs) maybe here if its gpu related https://bugzilla.kernel.org/buglist.cgi?component=Video%28DRI%20-%20non%20Intel%29&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&product=Drivers&query_format=advanced&resolution=---

Difficult to say. But if you let them know that it starts with this kernel after that kernel then someone can look to see what the changes were and find the regression. That also means that you should check any kernels between 4.16 and 5.0. 4.17 for instance has AMD GPU changes https://www.phoronix.com/scan.php?page=article&item=linux-417-features&num=1 so narrowing it down further will help and then it gets more complicated to narrow down from there.

Also if you can install another driver for the gpu it might narrow things down as well should it no longer have the problem that way.

**Comment by leggettc18** [comment] 2019-11-15 14:50
Just to update anyone who's watching this, I ended up installing Manjaro and used their kernel switching tool to determine that 4.19 also has that problem for me. I then installed Elementary (Ubuntu 18.04 based distro) which starts with Kernel 4.15, and have no problems. @byte1024 Mentioned 4.17 kernel had amdgpu changes, so I need to find a way to test that. This is the first time I've done a lot of messing with kernels so the going is not the fastest.

**Comment by kisak-valve** [comment] 2019-11-15 14:55
Hello @leggettc18, it's pretty clear that you're troubleshooting a video driver issue at this point and that there's no action to be taken by a Proton dev.

Feel free to continue discussing your issue, but I'm closing this issue as out-of-scope for this issue tracker.

**Closed as completed by kisak-valve** 2019-11-15 14:55 UTC
